### ISSUE TITLE
Switch to 1-name-per-line for name abbreviations

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/set.mm#1147]
@benjub noted in PR https://github.com/metamath/set.mm/pull/1144

> Also, it might be more robust to use the key at the beginning of set.mm for contributors' initials (rather than hardcoded in report-changes.py, l.160--175)? Maybe to make parsing easier, the key in set.mm can be changed to have one name per line (instead of three columns as is currently the case).

I'd prefer reading the author list from the mm file.  However, there is no way I'm going to try to parse the multi-line format currently in set.mm to make that work.  Names are just too complicated to robustly handle that way. So I think we *must* switch to "one name per line" if other tools are going to process it, and whether or not that happens is up to Norm.

@nmegill - are you willing to have set.mm be modified so that the author abbreviations are listed one per line, with a preceding "trigger text" to indicate where they start?

**Comment by nmegill** [comment]
> @nmegill - are you willing to have set.mm be modified so that the author abbreviations are listed one per line, with a preceding "trigger text" to indicate where they start?

TBH I'm not really thrilled by that.  Right now all contributors can be seen simultaneously in a normal editor window, and there is less scrolling to get to the frequently-used label change list.

**Comment by david-a-wheeler** [comment]
I understand.  It's *possible* to read from that, but it's a pain.  Most contributors (especially less common ones) have their full name in the "Contributed by...", so it's currently not important to do this.

**Comment by nmegill** [comment]
I looked at the .py file and also think that (currently) it's not too hard to maintain by hand.  Even if one is missed in the future, I assume the harm is no more than having initials instead of names displayed in the video (which some people might prefer anyway if they've chosen to use initials for acknowledgments).

If it is parsed from set.mm, even if we do reformat it to be one name per line, it becomes one more "standard" that we have to remember and maintain forever, just because of this one .py program.

Eventually we may have other needs for such parsing that we don't know about yet, and we can revisit this.  Before doing that, though, we'd want to establish an agreed-upon precise format and extend 'verify markup' to check it.  I would prefer to wait and see what our future needs might be before making such a commitment.
