### ISSUE TITLE
In Metamath 100, use "demoivreALT" not "demoivre"

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/set.mm#1161]
Metamath 100 #17 (chronologically 11/100) is De Moivre's Theorem.

We currently refer to label "demoivre", but that is a later proof in 2007 by Norman Megill. 

 propose that we instead refer to label "demoivreALT", an earlier proof in 2006 by Steve Rodriguez that does not use exponentiation. In our references we refer to Rodriguez and the earlier 2006 date.

@nmegill - any objection?  We could also swap names.

**Comment by nmegill** [comment]
Go ahead and change it to demoivreALT for the MM100 page, still credited to Steve.  demoivreALT also has a more elementary proof that might be better for the general public.

I don't think we want to swap names because demoivre is more general and its use should be preferred.  But I don't think demoivreALT will ever go away, because the proof is an interesting alternate.

Even though *ALT may seem an awkward name for the general public, we do reference the non-ALT version in its description, so people will still end up seeing both if they read the description.

**Comment by david-a-wheeler** [comment]
Sounds great! That's an easy fix.  I don't think ALT is particularly awkward; the names are clearly just a shorthand.
