### ISSUE TITLE
Should we change the set difference Unicode character?

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/set.mm#1180]
Should we change the "set difference" character we display in set.mm (and iset.mm also I presume)?

We are currently using Unicode hex code U+2216 (decimal 8726), which is the officially-correct set difference character:

~~~~
htmldef "\" as
    " <IMG SRC='setminus.gif' WIDTH=8 HEIGHT=19 ALT=' \' TITLE='\'> ";
  althtmldef "\" as ' &#8726; '; /* &setmn; */
    /* 2-Jan-2016 reverted sans-serif */
  latexdef "\" as "\setminus";
~~~~

However, it's small and more like the size of a plus character. E.g., look here: https://en.wikipedia.org/wiki/Mathematical_operators_and_symbols_in_Unicode

Should we change this to "\" instead? If you look at pages like this, the symbol seems to be larger in many cases:
http://mathworld.wolfram.com/SetDifference.html

**Comment by nmegill** [comment]
Yes, it is small compared to both the LaTeX version (see the ~ df-dif gif page for a LaTeX approximation) and what I found in a couple of set theory books.  I don't think it causes any confusion, it's just a minor aesthetic issue - maybe a "bug" in XITS and/or the Unicode spec?  Or maybe the Unicode people are trying to promote a smaller version, one that people might be less reluctant to use in place of a minus sign, since minus and this version are about the same size.  The LaTeX version is definitely quite a large, intrusive symbol.

I'm not worried about it, but if it bothers you, go ahead and change it to the big version if you prefer.

**Comment by benjub** [comment]
Actually I find the smaller one slightly better (I always thought the large one was too large).  I would keep it. Plus, it's more unique to set difference. For instance, the backslash is also used for biquotients.

**Comment by david-a-wheeler** [comment]
I'm certainly not *worried* about it, but I thought it looked a little funny. But since @benjub finds it slightly better, and it's purely aesthetic anyway, let's just leave it as-is.  I'll close this issue.
