### ISSUE TITLE
cqus / df-divs discrepancy

### ISSUE THREAD

**Issue by benjub** [metamath/set.mm#1444]
The syntax axiom for the token \` /s \`  is labeled cqus while its definition is labeled df-divs.  They should be harmonized.
I did not look at later theorems using \` /s \`.  Since it's about quotient structures, the more logical thing to do is to relabel df-divs to df-qus, and similarly use "qus" in later theorems that happen to use "divs".

More generally, is there a way to track similar discrepancies ?  By which I mean, exceptions to the convention
cxxx <---> df-xxx
wyyy <---> df-yyy

**Comment by nmegill** [comment]
Renaming to df-qus and using "qus" in associated theorems is ok with me.

However, we shouldn't get hung up on renaming the syntax definitions.  They are purposely chosen to be short to help save space in set.mm proofs, and it doesn't matter if they are cryptic.  They take up a lot of space in proofs but serve no human purpose because they aren't used in proof entry nor in proof display; they just have to be unique.  Aside from our practice of starting them with "c" or "w" (and even that isn't strictly required), the names have often been chosen by taking the definition name and removing as many characters as possible without becoming ambiguous.  Indeed, the fact that they are so short is often a good hint that they are syntax names and thus can be ignored in a compressed proof, for someone wanting to get a rough idea of what theorems the proof uses.  A few years ago, Mario and I looked at the possibility of changing all of them to optimize set.mm size but didn't have time to pursue it.  We should not make cxxx match df-xxx; it would make set.mm significantly larger.

While there isn't any written "short as possible" convention right now, they could easily be shortened automatically with an algorithm some day, so it hasn't been a pressing issue.

**Comment by benjub** [comment]
Understood. Here, there is also the semantic benefit of "qus" for "quotient structure" instead of "divs". Plus, there is one less character ! This is fixed in PR #1445
