### ISSUE TITLE
Magmas and Semigroups

### ISSUE THREAD

**Issue by avekens** [metamath/set.mm#1457]
This issue is a spin-off of #1389. According to the Google group discussion, see https://groups.google.com/d/topic/metamath/mnkBQV1_cXc/discussion, the definitions and theorems for magmas and semigroups (but not for "laws" and internal binary operations) can/should be moved from AV's mathbox to the main body of set.mm.

The definition and basic theorems for monoids should be cleaned up and adapted accordingly. Impacts of other sections shoud be avoided/minimized.

**Comment by avekens** [comment]
After PR #1465 was accepted, this issue is almost done. Two points remain open:

- According to Norm's comment in PR #1465, the justification for mndmgm, grpmgm, grpsgrp should be discussed:
> It seems like you are adding all possible links from less general to more general structures (which will grow quadratically with the number of layers). I don't see mndmgm, grpmgm, grpsgrp ever being needed for more than 1 or 2 theorems if at all. I think we only need sgrpmgm, mndsgrp, grpmnd, which can be chained with syl when necessary.
> Occasionally we have a frequent need to go down more than one layer, e.g. rngmnd, but that is justified because it is used 80 times. As with definitions, we should try to add theorems based on need or at least anticipated need.

- Should subsection "Examples and counterexamples for magmas, semigroups and monoids" be moved from my mathbox into main set.mm? I would recomment this, putting this subsection after subsection "Free monoids" (last subsection in section "Monoids").

@nmegill, @digama0, @david-a-wheeler , @benjub, @tirix : what's your opinion?

**Comment by avekens** [comment]
Current usage:
- mndmgm - 3 statements:  mndcl mndplusf srg1zr
- grpmgm - 1 statement: ringmgm
- grpsgrp -1 statement: grpmgm

Therefore, I think ~mndmgm should be kept, ~grpmgm and ~grpsgrp can be removed

**Comment by benjub** [comment]
I do not know about the examples section.
The TOC is currently:

PART 10  BASIC ALGEBRAIC STRUCTURES
- ​10.1  Monoids
- - 10.1.1  Magmas   cplusf 15738
- - 10.1.2  Semigroups   csgrp 15754
- - 10.1.3  Definition and basic properties of monoids   cmnd 15762
- - 10.1.4  Monoid homomorphisms and submonoids   cmhm 15812
- - 10.1.5  Ordered group sum operation   gsumvallem1 15850
- - 10.1.6  Free monoids   cfrmd 15875
- ​10.2  Groups

but it would seem more logical to have

PART 10  BASIC ALGEBRAIC STRUCTURES

- ​10.1  Magmas
- 10.2  Semigroups
- 10.3  Monoids
- 10.1.3  Definition and basic properties
- 10.1.4  Monoid morphisms and submonoids   cmhm 15812
- - 10.1.5  Ordered group sum operation   gsumvallem1 15850
- - 10.1.6  Free monoids   cfrmd 15875
- ​10.2  Groups

What do you think ?  Also, rename "ordered group sum operation" to "Ordered sums in a monoid" ? This is more explicit and removes ambiguity with "ordered group": here, it is the sum which is ordered (because the monoid is not necessarily commutative), and this has nothing to do with ordered monoids or groups.

**Comment by avekens** [comment]
> but it would seem more logical to have
> PART 10 BASIC ALGEBRAIC STRUCTURES
>     * ​10.1  Magmas
>     * 10.2  Semigroups
>     * 10.3  Monoids
>     * 10.1.3  Definition and basic properties
>     * 10.1.4  Monoid morphisms and submonoids   cmhm 15812
>     * * 10.1.5  Ordered group sum operation   gsumvallem1 15850
>     * * 10.1.6  Free monoids   cfrmd 15875
>     * ​10.2  Groups

Although I would like this structure in principle (by the way, your numbering seems to be mixed up a little bit: it should be "10.3.1 Definition and basic properties", ... "10.4 Groups", shoudn't it?), I think it is not appropriate for the time being. We should be happy that we have definitions for magmas and semigroups in main set.mm (as generalizations of monoids - and therefore it is adequate to have them in the section "10.1 Monoids"). If magmas and/or semigroups become more prominent in set.mm by being used in more theorems or by providing more related theorems in the future, we could restructure the sections without problems later. 

> What do you think ? Also, rename "ordered group sum operation" to "Ordered sums in a monoid" ? This is more explicit and removes ambiguity with "ordered group": here, it is the sum which is ordered (because the monoid is not necessarily commutative), and this has nothing to do with ordered monoids or groups.

I think subsection "ordered group sum operation" coud be moved upwards (and renamed to "Ordered sums in a magma", according your suggestion) , because it mainly does not depend on the definition of a monoid (the second theorem in this subsection, ~gsumvallem2, depens on Mnd, but this theorem/lemma itself is only used in ~gsumz, which is not used in this section). Therefore, ~gsumvallem2 and ~gsumz coud be moved into subsection "Group sum operation", the rest can actually be moved upwards without any impact.

**Comment by benjub** [comment]
You're right: I forgot to change the numbers in the TOC, but the order and indentation of the lines are the ones I meant.  Indeed, one could move the section about sums above, to have:
* ​10.1 Magmas
* * 10.1.1 Definition and basic properties
* * 10.1.2 Ordered sums in a magma
* 10.2 Semigroups
* 10.3 Monoids
* * 10.3.1 Definition and basic properties
* * 10.3.2 Monoid morphisms and submonoids
* * 10.3.3 Free monoids
* ​10.4 Groups
* * 10.4.1 Definition and basic properties
* * 10.4.2 Group morphisms
* * 10.4.3 Subgroups and quotient groups
...

Indeed, the sum as defined "associates to the left", so it is well-defined in a magma.  Later, in the section about semigroups, one will have to prove the general associativity property for sums, and in the section about monoids, one will have to prove that the empty sum is the unit.

By the way: c0g, cgsu, df-0g, df-gsum seem out of place and should be moved to that subsection.

Note that for the section "Groups" above, I did put morphisms before subobjects and quotients, since morphisms are more fundamental.

**Comment by avekens** [comment]
After PR #1471 was accepted, this issue is almost done. Two points remain open:
- Should subsection "Examples and counterexamples for magmas, semigroups and monoids" be moved from my mathbox into main set.mm? I would recomment this, putting this subsection after subsection "Free monoids" (last subsection in section "Monoids"), see comment on 8-Feb-2020.
- Should subsection "ordered group sum operation" be moved upwards (and renamed to "Ordered sums in a magma", according to @benjub`s suggestion). I would recomment this, see comment on 9-Feb-2020.

If there are no objections, I'll perform the moving with my next PR. Afterwards, this issue can be closed.

**Comment by avekens** [comment]
> By the way: c0g, cgsu, df-0g, df-gsum seem out of place and should be moved to that subsection.

That's absolutely right - I'll move these also to more appropriate places...

**Comment by avekens** [comment]
> c0g, cgsu, df-0g, df-gsum seem out of place and should be moved to that subsection.

Unfortunately, the "Axiom df-gsum has failed the definitional soundness check. The previous axiom df-prds uses the symbol being defined in this axiom." according to mmj2 after I moved df-gsum. Metamath.exe did not complain.

Therefore, I have to move it back :( .

**Comment by tirix** [comment]
I believe they may have been moved ahead because the definitions ~ df-imas, df-ress are using them.

**Comment by avekens** [comment]
Yes, it is not sufficient to have the constant definitions "$c gsum $." and "cgsu $a class gsum $." earlier (for metamath.exe it is, for mmj2 it isn't).
And since df-gsum uses 0g, I also have to move the corresponding definitions back :( :( .
But I think there was already a discussion in the Google group about this topic, see https://groups.google.com/d/msg/metamath/t68Dkr0euMw/XYE6unS5BwAJ . We can continue discussing this example there.

**Comment by benjub** [comment]
So if one introduces in Part 23 smooth manifolds, one will create a new "slot" for the smooth atlas, and of course there is a notion of product manifold, so one will want to integrate it in the definition of a product structure (df-prds, in Part 7), and in order to do that, one will have to move the definition of a smooth atlas to that Part 7 instead of Part 23 ?
If I understand this correctly, this is another example of the problems with defining extensible structures as "as rich as possible" (there are also advantages to this, of course, but I'm not sure how they balance).

**Comment by avekens** [comment]
Before I close this issue (which is done already with PR #1473 latest), I want to comment some remarks from PR #1459:

> > nmegill, 5-Feb-2020:    
ismgmn0 - I'm not sure whether this one or ismgm will be more useful, but requiring the base set to be nonempty to avoid "M e. V" makes it somewhat less general. Of course, in practice empty base sets can't exist in more specialized structures such as monoids that require existence of a special element like an identity element.

> avekens, 5-Feb-2020:  
This theorem is useful for proving that a concretely given structure is a magma (see ~mgm2nsgrplem1 and ~sgrp2nmndlem1 - I have additional cases in mind...). I do not know if there is already a theorem providing conditions for an extensible structure to be a set, but to show that the base set is not empty is almost always easy.

ismgmn0 is currently used 9 times!

> > > nmegill, 5-Feb-2020:   
isnmgm - This is kind of an odd theorem, which I don't see being used enough to justify its overhead. We don't have, for example, "is not a group"; we would just prove that directly for the special case we want to show.

> > avekens, 5-Feb-2020: 
Like ~ ismgmn0, this theorem is useful for proving that a concretely given structure is not a magma. I think it would pay off if there are 2-3 cases in which it is used (currently, it isn't used, but I have some cases in mind).

> digama0, 5-Feb-2020: 
There is no such thing as "not a magma". The +g slot should always contain a binary operation satisfying the constraints of a magma, unless it is not used at all. Otherwise, it's not a well formed structure, and operations like df-ress will not work properly on it. This is one more reason why "Magma" is not a useful class, because it is equivalent to "has a correct +g slot" with no constraints.

isnmgm is used for proving that the structure of all odd integers together with the addition of complex numbers is not a magma (see ~oddinmgm). This disproves the statement "There is no such thing as "not a magma".
Maybe "The +g slot **should** always contain a binary operation satisfying the constraints of a magma", but it needs not. If this was really a requirement, then it had to be reflected formally in the definitions, which is actually not the case. But I see no need for such a restriction, as the example with the odd numbers shows.

**Comment by digama0** [comment]
> > There is no such thing as "not a magma". The +g slot should always contain a binary operation satisfying the constraints of a magma, unless it is not used at all. Otherwise, it's not a well formed structure, and operations like df-ress will not work properly on it. This is one more reason why "Magma" is not a useful class, because it is equivalent to "has a correct +g slot" with no constraints.
> 
> isnmgm is used for proving that the structure of all odd integers together with the addition of complex numbers is not a magma (see ~oddinmgm). This disproves the statement "There is no such thing as "not a magma".
> Maybe "The +g slot **should** always contain a binary operation satisfying the constraints of a magma", but it needs not. If this was really a requirement, then it had to be reflected formally in the definitions, which is actually not the case. But I see no need for such a restriction, as the example with the odd numbers shows.

It is reflected formally in the definitions of *every single class* that deals with extensible structures. We're working in ZFC here, so the input argument a priori has no restrictions and there is nothing we can do about that. (It's not even necessarily a set.) But whenever you talk about an extensible structure, you are going to want to prove it is well formed and in one of the extensible structure classes such as `Grp`, and when you do so, closure will be one of the things you prove.

The odd integers with complex multiplication is not an extensible structure, at least, not one that uses the `+g` field. It is a malformed set that evaluates to some known but bogus value when applying `+g`.

Now you can say that this well formedness property ought to be defined as a definition in its own right, and it so happens in this case that this is extensionally identical with `Magma`. But we would need a different one for each slot, and it is currently easier to just bake these implicitly or explicitly into the structures that use the slots.

Just to be more concrete about it, here are the well formedness conditions for the slots:

* Base: No restriction. (Should be a set, but that's automatic.)
* `+g`: Should be a function Base x Base -> Base when functionalized on Base x Base. (That is, `Magma`)
* `.r`: Should be a function Base x Base -> Base when functionalized on Base x Base.
* `*r`: Should be Base -> Base when functionalized.
* Scalar: No restriction. (Should be a set.)
* `.s`: Scalar x Base -> Base when functionalized.
* `.i`: Base x Base -> Scalar when functionalized.
* `TopSet`: No restriction. (Should be a subset of ~P Base when restricted to ~P Base.)
* `le`: No restriction. (Should be a subset of Base x Base when restricted to Base x Base.)
* `oc`: Should be Base -> Base when functionalized.
* `dist`: Should be Base x Base -> RR for metric spaces (although one use takes Base x Base -> _V so no restriction)
* `UnifSet: No restriction. (Should be a subset of ~P (Base x Base) when restricted.)
* `Hom`: No restriction. (Should be Base x Base -> _V when restricted.)
* `comp`: Should be (x,y),z e. Base -> (x Hom y) x (y Hom z) -> (x Hom z) when functionalized.

These are basically just the "closure" parts of the respective structures that deal with these slots. They are not so useful on their own. A set that does not not satisfy a property for one of the slots is not eligible for any structures that use that slot. So while many of these restrictions are not "no restriction" so obviously you can contravene them, if you do, it will not be a structure (using that slot).

Clearly your example has a garbage slot for `.r` since it doesn't have one at all, but maybe less obviously it also has a garbage slot for `+g` because you put garbage in the slot deliberately. We don't have any structures using the Base set exclusively, but your slot for `le` for example is perfectly fine (it's empty) and so you have a valid `Poset`, just not anything group-like.
