### ISSUE TITLE
~thema3 used by minimize

### ISSUE THREAD

**Issue by avekens** [metamath/set.mm#1462]
I observed already several times that theorem ~thema3 of subsection "Stoic logic non-modal portion (Chrysippus of Soli)" is used/introduced by minimize several times. I have to remove it by hand each time (and it will be re-introduced by an automatic full run of minimize!?).  Since theorems of this subsection are very special (for a special purpose only), I think these should not be used elsewhere, especially not beyond part 1. Maybe this holds for the whole section "Other axiomatizations of classical propositional calculus".
What can we do to handle such cases? Is this an indication that theorem3 should become a theorem of a previous section (with a name according to our conventions)? Shall such theorems be marked as discouraged?

**Comment by david-a-wheeler** [comment]
While thema3 was originally created for a specific purpose, to prove assumptions of Stoic logic, if minimize finds it helpful then I don't see any special reason to avoid its use. It has been proven true! Presumably it was chosen by the Stoics because it was "obviously true" and useful for further reasoning, and if it has later uses, that seems like a good reason to keep it.

**Comment by david-a-wheeler** [comment]
While we have a naming convention, we do use the "traditional" names of some theorems when it has a well-known name. thema3 is just another example.

**Comment by nmegill** [comment]
We have no policy regarding theorems like thema3.  I don't feel strongly one way or the other, but if pressed I would say we should allow its use by minimize.  The next global minimize will show us how useful it is.  If we decide against using it in the future for some reason, it is simple to eliminate with "expand thema3" in each proof.

While "thema3" may be the statements's name in the literature, it is somewhat obscure and would be unfamiliar to most people.  If it becomes heavily used and people complain that it's confusing, in principle we could alias it with a more conventional name earlier in set.mm and discourage thema3, but I don't think we have to worry about that now.

We do have a policy for theorems in "Other axiomatizations of classical propositional calculus" in the following cases.  They should be marked as usage discouraged if (1) axioms other than ax-1,2,3,mp are used (currently there is only one foreign axiom, ax-meredith, in the main part, although there are many others in various mathboxes) or (2) the theorem reproduces an already-existing theorem or axiom as part of the section's equivalence proof (e.g. tbw-ax2, retbwax2, re1tbw2 all reproduce ax-1).

Possibly ax-meredith doesn't belong in the main set.mm (I added it years ago), but with discouraged tags and the avoidance of new axioms in minimize, it hasn't caused a problem.

**Comment by avekens** [comment]
> We have no policy regarding theorems like thema3. I don't feel strongly one way or the other, but if pressed I would say we should allow its use by minimize. The next global minimize will show us how useful it is. If we decide against using it in the future for some reason, it is simple to eliminate with "expand thema3" in each proof.

OK, let's wait for the next global minimize and see how often thema3 is used afterwards.

> While "thema3" may be the statement's name in the literature, it is somewhat obscure and would be unfamiliar to most people. If it becomes heavily used and people complain that it's confusing, in principle we could alias it with a more conventional name earlier in set.mm and discourage thema3, but I don't think we have to worry about that now.

I think this would be a good idea to provide an alias.

**Comment by avekens** [comment]
After the global minimization, 3 "thema" theorems are used in other proofs:

- 70 times thema3
- 12 times thema1a
- 2 times thema1b

I strongly recommend to provide these three theorems with another, more convenient name (in a previous section) and to tag these three  "thema" theorems with "(Proof modification is discouraged.)" and maybe also with "(New usage is discouraged.)". References should be provided in the comments of the new theorems to the "thema" theorems.

**Comment by david-a-wheeler** [comment]
@avekens - I disagree that the themata names should be renamed or restated. I think it's fine as it is. Here's my rationale.

First, these have been the standard names for these statements for about 2300 years (since the 3rd century BC). These standard names long predate modern logic. We use standard names or their abbreviations in other contexts, e.g., "ax-mp" for "modus ponens", "mto" for "modus tollens", "exmid" for "excluded middle", and "mvth" for "mean value theorem". We could rename "modus ponens" to something else, but since there *is* a standard name for it, we should use the standard name. I think the same principle applies here: where there's a standard name, we should use it.

Second, it's true that not everyone knows the names of these themata, but that's true for any name. Mathematics is full of sub-specialties. A statistician might not know what modus ponens or modus tollens are either. That doesn't mean they are bad names. Indeed, the power of set.mm is that if you don't know what something means, a click of a mouse or quick search will give you its exact definition.

Third, are the alternative names - whatever they are - really that much better? I think the name "thema3" is no less convenient than whatever you want to replace it with. What would be that "more convenient name"? And why would that name be so much more convenient that it would justify not using its standard name? Our naming conventions focus on the expression of the goal, but these are the sort of expressions where the naming convention is less helpful. The final statement is just 3 ANDs with an implication; that's not enough to disambiguate it. I'm focusing on thema3 (as the most common), but that applies to them all.

I expect Norm will end up adjudicating :-). If we *do* have second names for them, there's no need to discourage modification of the *proofs* of these themata; shortening the proofs of the themata is fine. Historically these themata were axioms; proving them merely shows that the system we use is at least as powerful as Stoic logic. You could just restate the themata with new names, and then declare "(New usage is discouraged.)" on the themata.

**Comment by nmegill** [comment]
"modus ponens" has an entry in Wikipedia, in the dictionary, and matches the usual meaning in almost all Google hits.

"thema" is a vague word meaning "theme", in the dictionary it has multiple meanings, including the first meaning "a topic or subject of discourse or of a written dissertation".  I have never heard it before in the context of stoic logic, and I would guess that most people haven't.  Hardly any Google matches are for the stoic logic meaning.

Perhaps the "thema3" name could be given a less vague name like "stoic3"?  "Stoic logic" is much less ambiguous than "thema".

**Comment by david-a-wheeler** [comment]
@nmegill - Good point, it's true that the word "thema" has multiple meanings.

I like "stoic3", it's a clear abbreviation. In the comments we can say "Stoic logic thema 3" or something like that. It's consistent with how we abbreviate other common names; we say "ax-mp" as the abbreviation for "axiom Modus Ponens". If that would be an improvement, let's do it. I'd be happy to do the rename, but I think we should do the minimizations first.

Oh, I have a related story about a case where the "name is too general to find it" - there's software developed in France named "Why". It has a website <http://why.lri.fr/> , but unless you knew its website already it was completely impossible to find it. They later replaced it with a new version of the software, thankfully now called "Why3", which is something you can find via Google instead of having to know the website http://why3.lri.fr/

Naming is hard :-).

**Comment by benjub** [comment]
> "thema" is a vague word meaning "theme", in the dictionary it has multiple meanings, including the first meaning "a topic or subject of discourse or of a written dissertation".

"thema" also means "proposition", in the etymological sense of "thing put forth". So basically, thema3 mean "Proposition 3". Not very descriptive. For another example, if I'm talking with cohomologists and I say "Theorem A", people will understand which theorem I'm refering too. To a wider audience... not so sure.

**Comment by avekens** [comment]
It is not only the name which bothers me, but that this theorem is in a section called "Other axiomatizations of classical propositional calculus" - this gives me the feeling that this theorem (and the others in this section) is something special or unusual (actually it isn't, I know). As I mentioned in my first comment, I am concerned about this section in general: in my opinion, all later theorems should be independent from this section, because it provides alternatives only, no extensions of classical propositional logic.

**Comment by benjub** [comment]
I do not have a strong opinion, so it can stay as is, but it is true that, as @avekens notes, there is a hiatus in the presentation: if these theorems are used outside that section, then it would be more natural to relabel and move them to the earlier sections where they belong in the logical development of set.mm, and they may even shorten more theorems this way.  The present section could stay as a historic presentation (hence restate the theorems with labels like "stoic3" and discouragement tags). Mixing both is a bit strange. Actually, this holds for all of Section 1.3.  But again: no strong opinions.

**Comment by avekens** [comment]
I made another observation which could contribute to our discussion: I develop new theorems in a separate file av.mm, which includes set.mm at the beginning, before I add these theorems into my mathbox. On performing "improve all", often (or always?) lines like "( Base ` X ) = ( Base ` X )" are unified using ~frege54c (from RP's mathbox) instead of ~eqid, and also minimize does not replace frege54c by eqid automatically - I have to replace it by hand. If RP's section "Propositions from _Begriffsschrift_" was also moved into section "Other axiomatizations of classical propositional calculus" (where it would belong textually), then it could be used also in the rest of set.mm. But would we really be happy with ~frege54c be used instead of ~eqid? ~frege54c is actually only an alias for ~eqid:

  frege54c $p |- A = A $=
    ( eqid ) AB $.

And the comment of ~eqid points to Frege's work: "This is part of Frege's eighth axiom per Proposition 54 of [Frege1879] p. 50; "

**Comment by david-a-wheeler** [comment]
I think those are different. Theorem frege54c is *exactly* the same as theorem eqid; as you note, it's an alias. The theorem formerly known as "thema3" is *not* an alias. Its proof is short, but the fact that it minimizes so many theorems shows that it's useful by itself.

We've renamed "thema3" to "stoic3", so the name is not as generic. That's doesn't completely resolve your concern, but does that help?

**Comment by avekens** [comment]
Renaming "thema3" to "stoic3" is an improvement, but I am still not (completely) satisfied - I still would prefer to have an alias following the usual naming conventions. But if nobody else has problems with it, we can leave it as it is (for the moment). I'll close this issue...
