### ISSUE TITLE
dots in labels

### ISSUE THREAD

**Issue by avekens** [metamath/set.mm#1671]
I saw that we have theorems ($p statements) in main set.mm with dots in their labels (e.g. rtrclreclem.min), coming from Drahflow's mathbox recently. Is this according to the conventions of set.mm? I thought that dots "." should be used only in labels for hypotheses ($e statements).

These labels should be cleaned up, shouldn't they?

**Comment by digama0** [comment]
Well, it is legal, but against set.mm conventions. But it's in a mathbox so I wouldn't do much more than inform @Drahflow of the convention and let them do what they like with that information. We don't usually enforce naming conventions until they are getting merged into the main part.

**Comment by avekens** [comment]
@digama0 maybe you looked at an older version of set.mm, but such theorems were moved to main set.mm on 5-Jun-20! That's why I complained about it.

**Comment by nmegill** [comment]
I believe these were moved to main by @arpie-steele. 

I agree that our informal practice has been to reserve the dot (period) for use in hypotheses.  While there is no specific requirement for this, it is nice to be consistent. 

To keep the names to a reasonable length, I would suggest rtrclreclem.refl be changed to  rtrclreclem1, rtrclreclem.subset changed to rtrclreclem2, etc. as is our custom with lemmas.  Although in a sense we are losing information, the comment of the lemmas already indicate that they are about reflexive properties, etc.  In ~ conventions, we state, "Labels are not a 1-to-1 mapping, because that would create long names that would be difficult to remember and tedious to type. Instead, label names are relatively short while suggesting their purpose."

@arpie-steele or anyone who wants to volunteer can rename these in a future PR.  Since they are already in main and will have the renames documented in the list at the top of set.mm, there is no need to notify Drahflow.

Thanks.

**Comment by nmegill** [comment]
BTW we don't want to make this a formal requirement because the early theorems ~ pm\*.\* and ~ 19.\* would violate it.  Over the years we have slowly been renaming a few of them more meaningfully, like ~ notnot1 instead of ~ pm2.12, but that is hard to do in general (with names that are easy to remember).

**Comment by digama0** [comment]
Don't forget the colorfully-named `0.999...`

**Comment by arpie-steele** [comment]
The naming change was adopted in #1689

**Comment by david-a-wheeler** [comment]
I think we can make an exception for `0.999...`. It's memorable, and since it *ends* in a period, it can't conflict with the "normal" user.

**Comment by avekens** [comment]
Done with  PR #1691.
