### ISSUE TITLE
General Logarithm (to an arbitrary base)

### ISSUE THREAD

**Issue by avekens** [metamath/set.mm#1672]
Currently, only the natural logarithm is definded in main set.mm ("14.3.4  The natural logarithm on complex numbers").

In my current PR #1670, I provide a lot of theorems based on the definition of the general logartithm. This definition (df-logb) and related theorems are contained in TA's mathbox, so they should be moved to the main part, according to our conventions.

I could do that, but I have two questions:
* In the corresponding section header comment, an alternative notation is discussed:
` ( ( logb `` B ) `` X ) ` instead of ` ( B logb X ) `.
Although there are good reasons to use the alternative notation, I think the current notation is easier to use, and more similar to other definitions in set.mm. Therefore, I propose to leave this definition as it is.
* Where should the section "Logarithm laws generalized to an arbitrary base" of TA's mathbox be moved? I would propse to insert it after "14.3.4  The natural logarithm on complex numbers" (the moved section renamed "Logarithms to an arbitrary base"), but section ​14.3 is titled "Basic trigonometry", and I wonder if the logarithms belong to trigonometry. Shouldn't both subsections be better placed in section 5.11  "Elementary trigonometry", or even in 5.9  "Elementary real and complex functions" instead, should they?

**Comment by avekens** [comment]
PS: Although this section is in TA's Mathbox, there are several contributors (besides @tirix there is @david-a-wheeler and indirectly @sorear).

**Comment by tirix** [comment]
Actually I moved the logarithm generalised to an arbitrary base to my mathbox because I wanted to use it for dyadic numbers (e.g. ~ [dya2ub](http://us2.metamath.org:88/mpeuni/dya2ub.html)), so this section would already fulfil the condition to be used by several mathboxes.

The complex logarithm needs to be inside or after trigonometry, because _pi is used in its definition, and that's also where the exponential function is defined. Maybe that section "Elementary Trigonometry" could be renamed to something more general which would indicate it includes exp and log ? And that would be where the logarithm generalised to an arbitrary base could logically be placed.

**Comment by digama0** [comment]
I think it is reasonable to consider "trigonometry" to be the analytic theory of the complex exponential function (including associated functions like log, sin, cos, arcsin, sec, cosh, etc.). Most of these functions exist only for historical reasons anyway, but "the analytic theory of exp" is fairly well defined.

I would put general log and the complex power function in the same group of functions.

**Comment by tirix** [comment]
@david-a-wheeler The two theorems mentioned by @avekens still remaining in my mathbox are from you. Would you like to move them back into your mathbox?

**Comment by david-a-wheeler** [comment]
Sure! Proposal here: https://github.com/metamath/set.mm/pull/1680

**Comment by avekens** [comment]
Essentially done with #1681, although cleanup of mathboxes is still in progress (see #1680).
