### ISSUE TITLE
Replacing "10" by "; 1 0"

### ISSUE THREAD

**Issue by avekens** [metamath/set.mm#2118]
In PR #2117, @nmegill raised the following question: 
> do we really need "10" at all, or should it be considered an obsolete relic of pre-Mario days? Right now, "10" is used by only 45 $p statements, and 6p4e10/6p4e10b etc. are essentially duplicated theorems. df-dec would become slightly more complex with "( 9 + 1 )" instead of "10", but things like 10p10e20 "( 10 + 10 ) = ; 2 0" seem like an awkward mixture of two notations. In a few cases "10" makes a theorem slightly nicer to read, but two notations for it is one more thing to confuse newcomers.

@digama0 replied:
> One issue with eliminating "10" is that it is used in the definition of ; A B; you wouldn't be able to use ; 1 0 there because it would be circular (and it would also be true in any base, so you wouldn't know what base is being described. As the joke goes, every base is base 10.)
> EDIT: Using 9 + 1 there directly would probably be fine. There are a bunch of special cases in the numeric normalizer to deal with 10, so I would not be against eliminating it.

I agree with Norm and I think it would be more consistent to remove the definition of "10" (df-10) and to rigorously use "; 1 0" instead. In addition to replacing "10" in the 45 $p statements Norm mentioned, a lot of work would be necessary to revise the proofs which are using these statements. Even the one theorem ~1lt10 is used in 42 proofs.

The following tasks have to be done to replace "10" by "; 1 0" (number of concerned theorems based on the results of @nmegill , see below):

- [x] Replace df-dec (renaming it dfdecOLD) by dfdec2
- [x] Replace 10 by ; 1 0 in all theorems using dfdecOLD (about 50), being replaced by dfdec10 or directly by (the new) df-dec
- [x] Mark df-10 (renaming it df-10OLD) as deprecated
- [x] Replace 10 by ; 1 0 in all theorems (about 90), marking the former versions as deprecated
- [x] Replace all occurrences of deprecated theorems by the corresponding not deprecated theorem (in about 70 theorems). Maybe some proofs can be additionally improved.
- [x] Delete dfdecOLD, df-10OLD and all related deprecated theorems

**Comment by nmegill** [comment]
Usually a quick way to get an approximate usage for a symbol is to use the syntax constructor:

```
MM> show statement c10
36630 c10 $a class 10 $.
MM> show usage c10
Statement "c10" is directly referenced in the proofs of 140 statements:
  10re 10pos 9p1e10 5p5e10 6p4e10 7p3e10 8p2e10...
...
```
showing 140 uses.  However, this doesn't pick up cases like baseltedgf, where 10 is hard-coded in a hypothesis of declti used in its proof, meaning it matches directly with no syntax construction.   Actually it looks like declt* cause dozens of misses because of this.

So, to get a better estimate, I searched the mpegif directory on us2:

.../mpegif$ grep -m 1 "'_10.gif'" * | grep -v '^mm' | wc -l

which gives 209 matches.

These matches also include statements whose comments have the symbol 10.   However, since the comments will have to be updated anyway (and because it would take extra work for me to identify them) I left them in the list.   When changing "\` 10 \`" in a comment, it might be friendliest to the reader to use "10" as ordinary text instead of "\` ; 1 0 \`".  If the 10 is inside of an expression like "\` 2 + 8 = 10 + 0 \'", the math string would have to be broken up to take out the 10 as ordinary text, and whether to do that or to use "\` ; 1 0 \`" I'll leave up to the judgment of the person making the change.  Note that "verify markup" will identify any occurrences of the math symbol 10 that remain in comments, once the htmldef for "10" is deleted.

Here is the list of the 209 matches:

0.999... 0pos 10nn 10nn0 10nprm 10p10e20 10pos 10re 11prm 1259lem1 1259lem2 1259lem3 1259lem4 1259lem5 139prm 13prm 163prm 17prm 19prm 1lt10 1t10e1p1e11 23prm 2503lem1 2503lem2 2503lem3 2503prm 257prm 2exp16 2expltfac 2lt10 317prm 37prm 3dec 3decltc 3dvds 3dvds2dec 3dvdsdec 3exp4mod41 3lt10 4001lem1 4001lem2 4001lem3 4001lem4 4001prm 41prothprm 41prothprmlem1 43prm 4lt10 5lt10 5p5e10 5p5e10b 5prm 5t2e10 5t3e15 5t4e20 5t5e25 631prm 6lt10 6p4e10 6p4e10b 6p5e11 6t5e30 6t6e36 7lt10 7p3e10 7p3e10b 7p4e11 7prm 83prm 8lt10 8p2e10 8p2e10b 8p3e11 8t5e40 8t6e48 9lt10 9p1e10 9p1e10b 9p2e11 9t11e99 ax-bgbltosilva ax-hgprmladder ax-tgoldbachgt baseltedgf bclbnd bgoldbachlt bgoldbtbndlem1 bpoly4 bpos1 bposlem4 bposlem5 bposlem8 bposlem9 c10 catstr cnfldstr dec0h dec0u dec10 dec10p dec2dvds dec2nprm dec5dvds dec5nprm decadd decaddc decaddc2 decaddci2 deccarry deccl deceq1 deceq2 decex declt decltc declti decma decma2c decmac decmul1 decmul10add decmul1c decmul2c decnncl decnncl2 decsplit decsplit0 decsplit0b decsplit1 decsubi decsuc decsucc df-10 df-dec df-dig df-dp2 df-ple digit1 digit2 dp2cl dpfrac1 dpval eengstr evengpoap3 fmtno4nprmfac193 fmtno4prmfac193 fmtno5faclem2 fmtno5nprm fsumcube imasvalstr ipostr isposix jm2.27dlem2 karatsuba log2le1 log2ub log2ublem1 log2ublem3 mgpds mndodcongi ndxid odrngstr odubas oppcbas oppgle opsrbas opsrbaslem opsrmulr opsrplusg opsrsca opsrvsca otpsbas otpsle otpsstr otpstset pleid plendx problem2 rescabs rescbas ressco ressds resshom ressle ressunif rmydioph setsmsds slotsbhcdif sq10 sq10e99m1 srads tgblthelfgott tgoldbach tgoldbachlt thlbas thlle tmslem tngds tnglem trkgstr ttgbas ttgplusg ttgvsca tuslem zlmds znadd znbas2 znbaslem znmul

**Comment by nmegill** [comment]
Here is the list of 209 labels sorted by statement number in set.mm, if that is more useful:

c10 df-10 10re 10pos 9p1e10 5p5e10 6p4e10 7p3e10 8p2e10 5t2e10 10nn 9lt10 8lt10 7lt10 6lt10 5lt10 4lt10 3lt10 2lt10 1lt10 10nn0 df-dec decex deceq1 deceq2 decnncl deccl dec0u dec0h decnncl2 declt decltc decsuc 3decltc declti decsucc dec10p dec10 6p4e10b 9p1e10b decma decmac decma2c decadd decaddc decaddc2 decaddci2 decsubi decmul1 decmul1c decmul2c decmul10add 6p5e11 7p4e11 8p3e11 9p2e11 10p10e20 5t3e15 5t4e20 5t5e25 6t5e30 6t6e36 8t5e40 8t6e48 9t11e99 digit2 digit1 sq10 sq10e99m1 3dec 0.999... bpoly4 fsumcube 3dvds 3dvdsdec 3dvds2dec dec2dvds dec5dvds dec5nprm dec2nprm decsplit0b decsplit0 decsplit1 decsplit karatsuba 2exp16 2expltfac 5prm 7prm 10nprm 11prm 13prm 17prm 19prm 23prm 37prm 43prm 83prm 139prm 163prm 317prm 631prm 1259lem1 1259lem2 1259lem3 1259lem4 1259lem5 2503lem1 2503lem2 2503lem3 2503prm 4001lem1 4001lem2 4001lem3 4001lem4 4001prm ndxid df-ple plendx pleid otpsstr otpsbas otpstset otpsle ressle odrngstr ressds resshom ressco slotsbhcdif imasvalstr oppcbas rescbas rescabs catstr 0pos isposix odubas ipostr mndodcongi mgpds srads opsrbaslem opsrbas opsrplusg opsrmulr opsrvsca opsrsca cnfldstr znbaslem znbas2 znadd znmul thlbas thlle ressunif tuslem setsmsds tmslem tnglem tngds log2ublem1 log2ublem3 log2ub log2le1 bclbnd bpos1 bposlem4 bposlem5 bposlem8 bposlem9 trkgstr ttgbas ttgplusg ttgvsca eengstr oppgle zlmds problem2 jm2.27dlem2 rmydioph 5p5e10b 7p3e10b 8p2e10b 1t10e1p1e11 deccarry 257prm fmtno4prmfac193 fmtno4nprmfac193 fmtno5faclem2 fmtno5nprm evengpoap3 bgoldbtbndlem1 ax-bgbltosilva bgoldbachlt ax-hgprmladder tgblthelfgott tgoldbachlt ax-tgoldbachgt tgoldbach 3exp4mod41 41prothprmlem1 41prothprm baseltedgf df-dig df-dp2 dp2cl dpval dpfrac1

**Comment by digama0** [comment]
>  However, this doesn't pick up cases like baseltedgf, where 10 is hard-coded in a hypothesis of declti used in its proof, meaning it matches directly with no syntax construction. Actually it looks like declt* cause dozens of misses because of this.

Actually, for matches like this, where a `10` shows up in a hypothesis and is directly matched against a theorem, it's okay to ignore these uses, because if the hypothesis and the theorem are both changed to use `; 1 0`, then the downstream use that plugs one into the other will continue to work with exactly the same compressed proof text (although the generated HTML will differ).

**Comment by avekens** [comment]
With PR #2119 , I provided theorem ~dfdec2 which could become the definition of the "decimal constructor" if the symbol 10 becomes deprecated, based on Norm's suggestion (using ( 9 + 1 ) instead of 10). To provide theorem ~dfdec10, which could/should be used instead of ~df-dec if ~df-dec is replaced by ~dfdec2, theorem 9p1e10b had to be revised not using ~dec10, or indirectly ~df-dec. 
Based on these theorems, I revised  some of the theorems of my latest contribution using "; 1 0" instead of "10": ~sq10, ~sq10e99m1, ~3dec : the proofs are not only more elegant, but also shorter (I kept the previous versions as OLD theorems).

My experiences so far show that we can do without the symbol 10. We could replace it step by step, using theorem ~defdec10. Maybe we should mark some definitions as "discouraged" (e.g. ~df-10, ~df-dec, ~dfdec2) to avoid a growth of their usage.

But maybe we should get some feedback from others: @david-a-wheeler (esp. because of ~df-dp2 ), @spolu (esp. because of ~9p1e10b, ~5p5e10b, ~7p3e10b, etc.)  what is your opinion?

**Comment by jkingdon** [comment]
I guess `; 1 0` makes sense to me. It certainly is more consistent and I'm not sure there's a compelling reason for a special case here (for one thing, ten shouldn't be as common as, say, `0` or `1` or even `2`).

In case anyone is curious, there should be no obstacle to having iset.mm do whatever set.mm chooses on this point - http://us.metamath.org/ileuni/df-dec.html is already present and in general this sort of integer/rational arithmetic works just the same without excluded middle as with it.

**Comment by nmegill** [comment]
> guess `; 1 0` makes sense to me. It certainly is more consistent and I'm not sure there's a compelling reason for a special case here (for one thing, ten shouldn't be as common as, say, `0` or `1` or even `2`).

The original reason for `10` was that Mario's df-dec was not invented yet, and df-10 provided a way to express a large number with digits multiplied by a power of 10 that was slightly less ugly than digits multiplied by a power of (9 + 1).  Note that df-10 was added in 2007 whereas the digits df-2 through df-9 were added in 1999.  It was a compromise I made after I abandoned an earlier attempt to introduce decimal numbers using new variable types that didn't seem to fit with set.mm's philosophy of simplicity (among other things, soundness justification became more complicated).  With df-dec, there is no longer a reason to have df-10, and in hindsight it probably should have been deleted with the df-dec introduction.

**Comment by avekens** [comment]
@nmegill @digama0 @david-a-wheeler Shall we start to work on this issue now? I added the required tasks to the description, and would start with the first two tasks. I think at least the four first tasks should be done soon, to avoid an increase of additional usages of the symbol 10.

**Comment by avekens** [comment]
> These matches also include statements whose comments have the symbol 10. However, since the comments will have to be updated anyway (and because it would take extra work for me to identify them) I left them in the list. When changing "` 10 `" in a comment, it might be friendliest to the reader to use "10" as ordinary text instead of "` ; 1 0 `". If the 10 is inside of an expression like "` 2 + 8 = 10 + 0 '", the math string would have to be broken up to take out the 10 as ordinary text, and whether to do that or to use "` ; 1 0 `" I'll leave up to the judgment of the person making the change. Note that "verify markup" will identify any occurrences of the math symbol 10 that remain in comments, once the htmldef for "10" is deleted.

If the 10 is inside of an expression like "` 2 + 8 = 10 + 0 '", then there should be a space character between 1 and 0: "` 2 + 8 = 1 0 + 0 '" (see, for example, the "25" in the comment of ~prmlem2). The math string needs not be broken up to take out the 10 as ordinary text, which would show the 10 in a different style.

**Comment by nmegill** [comment]
> If the 10 is inside of an expression like "` 2 + 8 = 10 + 0 '", then there should be a space character between 1 and 0: "` 2 + 8 = 1 0 + 0 '" (see, for example, the "25" in the comment of ~prmlem2). The math string needs not be broken up to take out the 10 as ordinary text, which would show the 10 in a different style.

You are right, that is a simpler and better solution.

**Comment by avekens** [comment]
With PR #2179 (if accepted), the first two tasks will be done. 50 items of Norm's list (with 209 items) will be revised.  There seems to be no principle problem with the replacement of 10 by ; 1 0 : all existing theorems could be transformed easily (so far). Many proofs, however, become a little bit longer, but the reason for this seems to be the longer representation of ; 1 0 compared with the symbol 10 only. 

I would countinue with task 3 (and 4) then...

**Comment by avekens** [comment]
With PR #2180 (if accepted), tasks 3 and 4 will be done. 99 items of Norm's list (with 209 items) and 2 additional theorems will be revised. The symbol 10 is not used anymore (in not deprecated definitions and theorems).

The remaining 110 items of Norm's list can be revised successively now, i.e. the OLD theorems in their proofs must be replaced by the corresponding not deprecated theorems.

**Comment by avekens** [comment]
With PR #2193, task 5 is done. Task 6 (and the whole issue) can be closed in about a year after the obsolete OLD definitions/theorems are removed.

**Comment by benjub** [comment]
@avekens : it looks like the only remaining task is deleting the OLD theorems. If they are indeed signaled with "obsolete as of..." then they will be deleted after a year, as you noted. So I think we can mark the task as done (or remove the checkbox) and close this issue ?

**Comment by avekens** [comment]
The year is almost over (only two months left), and I think the theorems are somehow nested. Therefore I should do the cleanup in September by myself, and therefore want to keep this issue as reminder.

**Comment by avekens** [comment]
One year is over now, so I will delete all corresponding OLD theorems (there are about 100 of them) in the next days. @wlammen since you also often delete due OLD theorems, I want to ask you not to do that until I am finished, to avoid merge conflicts.

**Comment by wlammen** [comment]
Ok.  I will wait for your 'finished' signal before resuming deleting OLD theorems.

**Comment by benjub** [comment]
@avekens : with the latest PR mentioned above (#2827), I guess that the final checkbox can be checked and this issue can be closed ?

**Comment by avekens** [comment]
Done by PR #2827
