### ISSUE TITLE
Add order types to iset.mm

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#2212]
Specifically, as described in #2203 we want to define an equivalent of http://us.metamath.org/mpeuni/dfoi.html which says that `OrdIso` isomorphically maps a set+relation to an ordinal. R and A should satisfy http://us.metamath.org/ileuni/df-se.html and `R We A` as defined in https://github.com/metamath/set.mm/pull/2211 (the most important part of this definition being http://us.metamath.org/ileuni/df-frfor.html ).

Here's what the set.mm definition looks like (slightly trimmed down in inessential ways):

```
    dfoi.1 $e |- C = { w e. A | A. j e. ran h j R w } $.
    dfoi.2 $e |- G = ( h e. _V |-> ( iota_ v e. C A. u e. C -. u R v ) ) $.
    dfoi.3 $e |- F = recs ( G ) $.
    dfoi $p |- OrdIso ( R , A ) = ( F |`
       { x e. On | E. t e. A A. z e. ( F " x ) z R t } ) $=
```

which can be summarized as "Given a partial mapping h from ordinals to a subset of A, let C be the set of upper bounds for that subset. Then choose the least upper bound (which exists due to the set.mm definition of We) and map the next ordinal to that" (I realize "next ordinal" is perhaps not great wording because this works for limit ordinals as well as successors).

The definition we need is something like "Given a partial mapping h from ordinals to a subset of A, ...... ". Oh, fudge. I know it involves some kind of induction over some kind of property or class or something, but I'm having trouble stating it informally, much less the exact definition we'll use.

Notes:

* since we aren't using the set.mm definition anyway, I'm not sure there is much point in keeping the if expression, since `( R We A /\ R Se A )` won't be decidable.

**Comment by digama0** [comment]
This actually looks rather bleak, and probably we need some more assumptions.

* Can we prove extensionality for `R`? i.e. `A. z e. A ( z R x <-> z R y )` implies `x = y`. This is obviously true for ordinals because of extensionality, and it is true for set.mm well orders because of trichotomy, but I don't see any way to derive it from `Fr` directly.
* We will probably also need a way to talk about the equivalent of `C_` for `R`, and there are two candidates - `A. z e. A ( z R x -> z R y )` and `A. z e. A ( y R z -> x R z )`; extensionality is needed to derive useful properties of this relation. This would be used instead of `-. u R v` in the iota.
* Assuming these things, we can basically prove that the iota is unique (least upper bounds are unique). But in fact the existence part is not a given, and if you look at the proof you will see that it is actually expected to fail - this happens when `A` runs out of elements, and the ordinal where this happens is exactly the order type. This looks uncomfortably LEM-like.

I suspect that we won't be able to prove ordtype at all without an assumption that basically assumes what we want to prove. That is, we will have a predicate that asserts that the order type of a particular well order exists and is equal to some ordinal, and in certain cases (like finite sets) we can prove it. I will think on this some more.

**Comment by jkingdon** [comment]
> I will think on this some more

OK. I'll try to prove a few things related to the first two bullet points and/or other theorems which might come in handy.

So far I have:

```
    nnwetri $p |- ( A e. _om -> ( _E We A /\
        A. x e. A A. y e. A ( x _E y \/ x = y \/ y _E x ) ) ) $=
```

as well as zfregfr , ordfr , ordwe (stated the same as in set.mm, but proved via ax-setind). My work so far is on the https://github.com/jkingdon/set.mm/tree/iset-trifr branch.

**Comment by jkingdon** [comment]
I'm going to treat https://us.metamath.org/ileuni/exmidonfin.html as having answered the question in the negative, as this derives a taboo from the existence of order types (at least, ones which have the full power that they have in set.mm).

If there is any way to redefine "order type" to make sense in iset.mm, feel free to make a new issue.
