### ISSUE TITLE
vncan in nf.mm has an invalid proof

### ISSUE THREAD

**Issue by jamesjer** [metamath/set.mm#2334]
While looking at nf.mm in git head:
```
MM> verify proof *
0 10%  20%  30%  40%  50%  60%  70%  80%  90% 100%
..................................................
?Error on line 62644 of file "nf.mm" at statement 24462, label "vncan", type
"$p":
    ( cvv ccan wcel cnc cltc wbr ltcirr cpw canltpw pwv nceqi syl6breq mto ) AB
                                 ^^^^^^
This token is not the label of an assertion or optional hypothesis.
```

**Comment by nmegill** [comment]
@sctfn Could you look at this problem?

@david-a-wheeler or anyone:  are the CI scripts not checking "verify proof \*" for nf.mm?

**Comment by david-a-wheeler** [comment]
@nmegill: Correct, nf.mm isn't being checked.

The file `.github/workflows/verifiers.yml` defines the CI script workflow. The process that uses cmetamathexe runs a number of steps, including:

      - run: scripts/verify --top_date_skip --extra 'write bibliography mmbiblio.html' set.mm
      - run: scripts/verify --top_date_skip iset.mm

but there is no step that verifies the other databases. In general, currently only set.mm and iset.mm are checked.

We could add verification of other databases, but we should make sure they pass first :-).

**Comment by benjub** [comment]
From the tentative proof of vncan, the statement should be
> ltcirr $p |- -. A <_c A $= ? $.

It is easily provable from brltc. I can do it if we have no news from @sctfn in the next few days.

**Comment by sctfn** [comment]
I just proved it in a branch. Submitting the PR now.

**Comment by david-a-wheeler** [comment]
Once we're satisfied that `nf.mm` is meeting all criteria, we could modify the workflows to check it.

The `nf.mm` database is relatively small. I think we can just include it in existing jobs, instead of creating a new job. Just add relevant `- run:` statements similar to what we do with `iset.mm`. Let me know if there's a reason we *shouldn't* do that.

I could easily modify the CI workflow to check `nf.mm`, let me know when you think it's ready for that.

Also: We could add other databases too. Is there interest in doing that? There's no point if they aren't getting changed.

**Comment by benjub** [comment]
> Also: We could add other databases too. Is there interest in doing that? There's no point if they aren't getting changed.

Is there an easy way for the CI to see which databases were changed by the PR and check only those ?

**Comment by david-a-wheeler** [comment]
I looked & didn't see any. Also, success is affected by changes to the tools or workflow as well as changes to the databases. So just running them each time is the obvious way to make sure everything is okay.

**Comment by digama0** [comment]
We should be checking every database in the repo. You can do the full suite if you like but I think one verifier is sufficient; in particular don't use a "pathological" database like big_unifier.mm together with a verifier that doesn't handle pathological databases well. I suggest optimizing for total CI time spent on these databases since they don't change much. It should be fine to do them all in a single invocation of metamath.exe or smm3 (both of which have good support for arbitrary mm databases and pathologies).

**Comment by david-a-wheeler** [comment]
@digama0 - fair enough. I added "verifying all databases" as https://github.com/metamath/set.mm/issues/2342 and assigned it to myself.
