### ISSUE TITLE
cbvalv and ax-10

### ISSUE THREAD

**Issue by jamesjer** [metamath/set.mm#2388]
The comment above `cbvalv` says, in part, "Remove dependency on ~ ax-10 ."  However, that is no longer the case:
```
MM-PA> show trace_back cbvalv /essential /match ax*
The proof of statement "cbvalv" uses the following earlier statements:
  ax-mp($a) ax-1($a) ax-2($a) ax-3($a) ax-gen($a) ax-4($a) ax-5($a) ax5e ax5ea
  ax-6($a) ax6v ax6ev ax-7($a) ax7v ax7v1 ax7v2 ax6evr ax7 ax-10($a) ax-11($a)
  ax-12($a) ax12v ax-13($a) ax13v ax13lem1 ax6e
```

A git bisect shows that the dependency on ax-10 appeared with commit https://github.com/metamath/set.mm/commit/6f7ee0b388d3654dad7c3878522b0866808c43ca.  Either the comment is wrong and should be removed (and the proof can be shortened to simply invoke `cbval`), or the dependency on `ax-10` should be removed again.  The dependency chain is `cbvalv` -> `nfal` -> `nf5i` -> `nf5-1`-> `hbe1a` -> `hbn1` -> `ax-10`.

**Comment by benjub** [comment]
The dependency was reintroduced when df-nf was changed (some usages of ax-10 and of ax-12 were added and some (more numerous) were removed). Note that cbvalvw is a weaker form that uses even fewer axioms.

Since F/ does not appear in the statement, the dependency on ax-10 can be removed. I'll try tomorrow (or @wlammen or anyone may).

**Edit:** after a quick try: easy to remove ax-10 by manually proving the version of alrimi we need, but I need ax-11. Can you do without ax-11, @wlammen ?

**Comment by wlammen** [comment]
@benjub No.  hbal A. x ph -> A. y A. x ph seems to depend on ax-11.  If you have a dv condition on  x, y, its a consequence of ax-5.  I remember I tried to start from there, and somehow get rid of the dv condition, but then ax-11 kicks in.

**Comment by wlammen** [comment]
Fixed in PR #2390

**Comment by benjub** [comment]
I also found cbv3 (this will remove ax-10-dependency from cbvaldva, cbvexdva, cbval2v, cbvex2v).
@jamesjer : thanks for signaling this, and please do so if you encounter other cases; @wlammen : do you think there are other cases of unnecessary usages of ax-10 and ax-12 which have either appeared when df-nf, or where we have not yet taken advantage of the new df-nf to remove them ?

**Comment by wlammen** [comment]
I scanned set.mm for possible candidates eligible to such transformations then.  cbvalv was an oversight.  cbv3 (and cbv3h) seems to be difficult to prove without ax-10.
