### ISSUE TITLE
Use git version of mm_100.html on the web site

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#2468]
First of all, no issue on this topic would be complete without mentioning all the hard work that @david-a-wheeler has been putting into updating the web site. I am pleased to report that http://us.metamath.org/ileuni/mmrecent.html and the theorems listed there have been updated recently and http://us.metamath.org/ileuni/mmil.html is also an up to date copy (includes isprm7 for example). I know that David has had other demands on his time and also has been doing a great job of trying to complete this task in a sustainable way (that is, that will not require large amounts of manual effort in the future).

This issue, however, is about http://us.metamath.org/mm_100.html . It lags behind the git copy at https://github.com/metamath/set.mm/blob/develop/mm_100.html . Most concretely, four entries for iset.mm have been added in 2022 and in terms of future work there is some text in the headers that we need to revise concerning how to contact the project and git is the obvious way to coordinate those edits.

Hopefully this is just a simple entry to add to the update script, although if not well these things don't always get done overnight.

Jim

**Comment by david-a-wheeler** [comment]
Thanks for the report!!

I think I've fixed it with a tweak to a download script, and the fix should be visible around 2pm Eastern Time tomorrow.

As far as I can tell, Norm manually copied files to specific places when he noticed something changed, so I'm automating things that weren't automated before using structures I didn't create :-).

Let me know if us2.metamath.org is fixed or isn't fixed by tomorrow afternoon. The rebuild script on us2.metamath.org is run every 9am US Eastern Time and takes a few hours; once it's done, things should be fine on us2.metamath.org. Later on us.metamath.org picks that up. I can force things to be sooner, but I normally want to see if the "standard actions" produce expected behavior, so I'd rather avoid special triggers unless it's important.

**Comment by jkingdon** [comment]
> I think I've fixed it with a tweak to a download script, and the fix should be visible around 2pm Eastern Time tomorrow.

Excellent!

> As far as I can tell, Norm manually copied files to specific places when he noticed something changed, so I'm automating things that weren't automated before using structures I didn't create :-).

That's my impression too and to be fair his habits started well before we were using git, so I suppose I'm not surprised that he didn't have as much of an automation mindset as you or I. Definitely appreciate your automation and desire to keep enough of the existing structure that we don't have things falling through the cracks.

> I can force things to be sooner, but I normally want to see if the "standard actions" produce expected behavior, so I'd rather avoid special triggers unless it's important.

No need for any manual run. We're aiming for "sustainable" and "predictable" here and there's definitely no hurry on this update.

**Comment by david-a-wheeler** [comment]
Yes, in the long term I want this all sustainably automated.

In the short term I'm trying to use the existing structures and automate them just enough so that people can see that we're continuing to maintain things. There's a lot of cleanup/simplification to be done, but "get it working first" is I think the situation right now.

**Comment by jkingdon** [comment]
I see the new content at http://us.metamath.org/mm_100.html so I'm closing this. Feel free to re-open or start a new issue if anyone sees anything which still needs attention.
