### ISSUE TITLE
At least 1 gif does not seem to work

### ISSUE THREAD

**Issue by mazsa** [metamath/set.mm#2503]
Neither in Chrome nor in Firefox. http://us.metamath.org/mpegif/df-xrn.html uses the ALT version of ` " <IMG SRC='ltimes.gif' WIDTH=10 HEIGHT=19 ALT=' |X.' TITLE='|X.'> " ` . http://us.metamath.org/symbols/ltimes.gif is OK.

**Comment by digama0** [comment]
http://us.metamath.org/mpegif/ltimes.gif is a 404, which is why the image
doesn't show up. The GIF files are stored (or maybe symlinked?) to the
mpegif/ directory so that the gif references are as short as possible (the
huge number of gif references contributes significantly to the page weight
of mpegif HTML files).

**Comment by mazsa** [comment]
@digama0 oh I see. Could you please help me with this one or @david-a-wheeler is who has an access to http://us.metamath.org/mpegif/ ?

**Comment by digama0** [comment]
While investigating this issue, I found the following in the build log (emphasis mine):
```diff
 Metamath - Version 0.198 7-Aug-2021           Type HELP for help, EXIT to exit.
 MM> read '../metamath/set.mm'
 Reading source file "../metamath/set.mm"... 42904460 bytes
 42904460 bytes were read into the source buffer.
 The source has 201453 statements; 2656 are $a and 39920 are $p.
 No errors were found.  However, proofs were not checked.  Type VERIFY PROOF *
 if you want to check them.
 MM> write recent_additions mmrecent.html /html /limit 100
 The old file will be renamed mmrecent.html~1.
 Reading definitions from $t statement of ../metamath/set.mm...
 1611 typesetting statements were read from "../metamath/set.mm".
+?Warning: The file "ltimes.gif", which is referenced in an htmldef statement,
+was not found.
 Reading HTML bibliographic tags from file "mmset.html"...
 The 100 most recent theorem(s) were written.
 MM> write recent_additions mmrecent.html /html /limit 1000
 The old file will be renamed mmrecent.html~1.
 The 1000 most recent theorem(s) were written.
 MM> exit
```
So it appears CI is still letting bad things through.

**Comment by digama0** [comment]
The website build has been updated to copy ltimes.gif to the mpegif directory (there is apparently an explicit list that you can find around L612 of http://us.metamath.org/install.sh ), and I also updated the live site so that http://us2.metamath.org:8888/mpegif/df-xrn.html should now show the missing symbol. I believe it should propagate to us.metamath.org eventually, but I am not familiar with how the mirrors work to hurry things along.

**Comment by mazsa** [comment]
thank you @digama0 , I'll write you here next week if it not prapagates.

**Comment by mazsa** [comment]
FYI @digama propagated e.g. http://us.metamath.org/mpegif/brxrn.html thank you again.
