### ISSUE TITLE
Bad importations during `'write source set.mm /split'` process

### ISSUE THREAD

**Issue by amelieled** [metamath/set.mm#2792]
After running `./metamath 'read set.mm' 'write source set.mm /split' exit`, the following command fails:
`./metamath 'read set-class.mm'`  (same for `set-tarskigeom.mm`).

To fix this problem, one can add the following line `$[ set-pred.mm $]` at the beginning of the file `set-class.mm`.

**Comment by benjub** [comment]
Thanks for signaling this issue. Modularity is something we have to work on in Metamath...
I don't use this feature often but I think your solution works: when metamath.c merges the files, the inclusion command `$[ set-pred.mm $]` will be transformed into `$( $[ Skip set-pred.mm $] $)` so that it works both in the split and in the nonsplit cases.
