### ISSUE TITLE
Minor latex issue with dot sign

### ISSUE THREAD

**Issue by GinoGiotto** [metamath/set.mm#2998]
In the <code>$t</code> comment of set.mm there is the LaTeX definition: <code> latexdef "." as "\\."; </code>, but the <code>\\.</code> latex command gives an error message for some Tex editors, so it should be replaced. I was thinking about doing a pull request, but then I realized that the appropriate substitution depends on its task and I'm not sure what is the right one. For example if the dot is a multiplication sign I would replace it with <code>\cdot</code>, but it could also be a period or an accent. Please let me know what the appropriate substitution should be.

**Comment by tirix** [comment]
The dot symbol `.` of set.mm is only used for the decimal point, defined in [df-dp](https://us.metamath.org/mpeuni/df-dp.html), so it is safe to replace it with a dot on the baseline. Would the correct latex be simply a dot, without the backslash?

The center dot (`\cdot` $\cdot$) is used for example for complex multiplication in [df-mul](https://us.metamath.org/mpeuni/df-mul.html), so that one is correct IMO.

**Comment by GinoGiotto** [comment]
Yeah I looked it up and I think that:

The <code>\\.</code> sign represents an accent in LaTeX, but it's probably outdated so editors refuse it (I tested on Texmaker and TeXstudio).

The <code>\\dot</code> sign also represents an accent in LaTeX, this one is accepted and doesn't give an error.

In set.mm there is <code>x.</code> for the multiplication sign, which is already correctly translated into <code>\\cdot</code> for Latex.

In set.mm there is the line: <code>$c . $. $( Decimal point. $)</code> so indeed the single dot is used for decimal numbers, not for accents.

So I agree that the right solution should be replacing <code>latexdef "." as "\\.";</code> into simply <code>latexdef "." as ".";</code>. 

Thanks for your help.

**Comment by tirix** [comment]
Yes : feel free to submit a PR for this change, thank you!
