### ISSUE TITLE
Defining projective space / projective plane

### ISSUE THREAD

**Issue by icecream17** [metamath/set.mm#3035]
## Projective space background

https://en.wikipedia.org/wiki/Projective_space#Definition
> Given a vector space _V_ over a field _K_, the projective space **P**(_V_) is the quotient set of V \ { 0 } by the equivalence _x_ ~ _y_ iff there is a nonzero element _λ_ of _K_ such that _x_ = _λy_.

It's not obvious what properties of a vector space are needed. [benjub mentioned that _K_ need not be commutative (i.e. only need be a division ring)](https://github.com/metamath/set.mm/issues/787#issuecomment-1410974603).

I think the domain of **P** would be _left vector spaces_ then? https://us.metamath.org/mpeuni/df-lvec.html

> An especially common case would be when _V_ = _K_<sup>_n_+1</sup> (i.e. the set of ordered _n_+1–element–tuples of _K_, i.e. singletons pairs triples etc.)
> In such cases, the projective space could be denoted **P**<sub>_n_</sub>(_K_), or **PG**(_n_, _K_).

Would use (n **PG** K) for metamath.

> If _K_ is a finite field with _q_ elements, **P**<sub>_n_</sub>(_K_) is often denoted **PG**(_n_, _q_).

I'm ignoring this but it's unfortunate that the **PG** notation can be ambiguous. I would guess this notation exists because there's an isomorphism between finite projective spaces.

## Projective plane background

> If _n_ is one or two, a projective space of dimension _n_ is called a **projective line** or **projective plane**, respectively.

There are several formulations like the one above, but the defining properties are:
> https://en.wikipedia.org/wiki/Projective_plane#Definition
> (https://ericmoorhouse.org/handouts/projective_planes.pdf)

1. ∀ two distinct points ∃ a unique line containing both
2. ∀ two distinct lines ∃ a unique intersection (point)
3. ∃ four points of which no three are collinear

Note that since projective planes have points (Base) and lines ([LineG](https://us.metamath.org/mpeuni/df-lng.html)) there would have to be some conversion function (say, `toPrPl`).

(Using Word, i.e. 0 --> points, 1 --> lines, 2 --> planes, etc., seems nice for the conversion. Points, lines, planes, etc. are automatically defined for projective spaces, I think: https://en.wikipedia.org/wiki/PG(3,2), though I don't know how. Smth about subspaces, linear independency, dimensions? There's also the definition at https://en.wikipedia.org/wiki/Projective_space#Synthetic_geometry and I don't see how these separate definitions of projective space are the same.)

## Original purpose of definitions

All 3 of the elliptic curve sources I'm using describe elliptic curves using projective _planes_ in some way or another:
> Elliptic Curves, Second Edition by Dale Husemoller
> Rational Points on Elliptic Curves by Joseph H. Silverman
> https://dms.umontreal.ca/~mlalin/WIM2012-ellipticcurves.pdf

I haven't really heard about projective spaces until benjub's comment.
Originally I was just going to define projective plane, construct the real projective plane, etc. But sometimes the rational projective plane is used. And it turns out ``(toPrPl ` (2 PG ℝfld))`` happens to be the real projective plane. So I think defining at least **PG** would be beneficial. Don't know about **P** though.

## resources

note to self: here are some resources

https://webspace.maths.qmul.ac.uk/p.j.cameron/pps/pps1.pdf
https://www.cis.upenn.edu/~jean/gma-v2-chap5.pdf

**Comment by benjub** [comment]
My advice: define the projective space of a vector space (since set.mm allows noncommutative fields, that's good). set.mm has quotients by equivalence relations (df-qs), so I think all the needed ingredients are there. Something like
```
df-projsp $a |- ProjSp = ( v e. LVec |->  ( ( Base ` v ) \ { ( 0+ ` v ) } /
   { <. x , y .> | ( ( x e. ( Base ` v ) /\ y e. ( Base ` v ) ) /\
     E. s e. ( Base ` ( Scalar ` v ) ) x = ( s .r y ) ) } ) $.
```
I'm not sure for the label and token (I'd like to save "proj" for the Proj construction), but for the symbol: $\mathbb{P}$.

If you start with a topological vector space, then you obtain a topological space with the quotient topology, and also you have notions of subspaces that go to the quotient. set.mm has a notion of quotient structures, but I do not know if it is well-suited for the present case. @tirix and @digama0 should know this better.

If necessary, you may then define something like
```
df-??? $a |- ??? = ( n e. NN0 , k e. DivRing |-> ( ProjSp ` ( k FreeLMod ( 1 .. n ) ) ) ) $.
```
(check syntax). But you should prove as many results as possible with ProjSp, and if necessary prove the versions for "???" as a straightforward corollary.

(You also gave the synthetic definition, and the fact that they are related it the fundamental theorem of projective geometry. It is not necessary for now to introduce the synthetic pov.)

**Comment by icecream17** [comment]
(Also note https://us.metamath.org/mpeuni/df-np.html)
https://us.metamath.org/mpeuni/df-prime.html already has \mathbb{P} so I guess maybe:

$$
\begin{align}
\mathbb{P}_1 \\
\mathbb{P}_n
\end{align}
$$

corresponding to

```
cprjsp1 $a class PrjSp1 $.
df-prjsp1 $a |- PrjSp1 = ( v e. LVec |-> [_ ( Base ` v ) / b ]_ ( ( b \ { ( 0g ` v ) } ) /.
  { <. x , y >. | ( ( x e. b /\ y e. b ) /\ E. l e. ( Base ` ( Scalar ` v ) ) x = ( l ( .s ` v ) y ) ) } ) ) $.

cprjsp $a class PrjSp $.
df-prjsp $a |- PrjSp = ( n e. NN0 , k e. DivRing |-> ( PrjSp1 ` ( k FreeLMod ( 1 .. n ) ) ) ) $.
```

**Comment by benjub** [comment]
@icecream17 : Since there are two definitions, I would use token/symbol `PrjSpn` / $\mathbb{P}_n$ for the second, so that expressions will look like e.g. $\mathbb{P}_n(k, \mathbb{R})$. For the first, I would use `PrjSp` / $\mathbb{P}$, and for prime numbers, $\mathbb{Primes}$.

**edit:** it is important that the "n" in subscript be non-italic, since it is not a variable. The LaTeX is not well rendered here, so it appears italic in the above paragraph, but it should be `\mathbb{P}_{\mathrm{n}}`; it should also be non-italic in the unicode version. (FYI @GinoGiotto for LaTeX-related stuff)

Indeed, since $\mathbb{Primes}$ is a "standalone" symbol (it denotes a specific set), it can be longer, while the symbol for projective spaces is used in expressions like $\mathbb{P}(V)$ where $V$ is a vector space, so it would be better to keep it shorter. What does @digama0 think ? If prime numbers should keep being denoted by $\mathbb{P}$, then projective spaces could be denoted $\mathbb{Proj}$ maybe ? (Note that $\mathrm{Proj}$ has another meaning, which is standard, related but different.)

**Comment by avekens** [comment]
> @icecream17 : Since there are two definitions, I would use token/symbol `PrjSpn` / Pn for the second, so that expressions will look like e.g. Pn(k,R). For the first, I would use `PrjSp` / P, and for prime numbers, 𝕣𝕚𝕞𝕖𝕤Primes.

I would like to keep the symbol for primes (a blackboard bold capital P, see Wikipedia https://en.wikipedia.org/wiki/Prime_number), and to use a boldface capital P for projective spaces, see Wikipedia https://en.wikipedia.org/wiki/Projective_space.

**Comment by icecream17** [comment]
Would it be confusing that https://us.metamath.org/mpeuni/df-np.html (bold italic p) is different than (bold p)?

**Comment by benjub** [comment]
> ... use a boldface capital P for projective spaces, see Wikipedia https://en.wikipedia.org/wiki/Projective_space.

Boldface capital is used for projective spaces when it is also used for number systems, e.g., $\mathbf{RP}^2$ Bourbaki-style, but when blackboard boldface is used, it should be used consistently, e.g. $\mathbb{RP}^2$. If it is decided that $\mathbb{P}$ should be saved for the set of prime numbers in $\mathbb{N}$, then my second choice for projective spaces would be $\mathbb{Proj}$ as written above. Thoughts @digama0 ?

> Would it be confusing that https://us.metamath.org/mpeuni/df-np.html (bold italic p) is different than (bold p)?

These are "temporary" sets used in the construction of real numbers, so I would leave them in the non-standard bold italic form.

**Comment by digama0** [comment]
> > ... use a boldface capital P for projective spaces, see Wikipedia https://en.wikipedia.org/wiki/Projective_space.
> 
> Boldface capital is used for projective spaces when it is also used for number systems, e.g., $\mathbf{RP}^2$ Bourbaki-style, but when blackboard boldface is used, it should be used consistently, e.g. $\mathbb{RP}^2$.

I have seen RP used with a different typeface for the two letters (IIRC), probably $\mathbb{R}P^2$. I have no particular preferences in this area.

> Indeed, since $\mathbb{Primes}$ is a "standalone" symbol (it denotes a specific set), it can be longer, while the symbol for projective spaces is used in expressions like $\mathbb{P}(V)$ where $V$ is a vector space, so it would be better to keep it shorter. What does @digama0 think ?

I think it is mostly the other way around: one tends to use `A e. Prime` as a hypothesis or conclusion or step in a proof directly, while something involving extensible structures like ``P = ( ProjSp ` V )`` is likely to show up only once at the beginning of a proof as a definition, so there is less pressure for it to be short.

**Comment by icecream17** [comment]
Maybe instead of $\mathbb{Proj}$ one could have $\mathbb{Prj}$, which matches with the labeling better, and doesn't conflict with `Proj`

(Although, I decided upon the possibly temporary label `df-prjsp` by asking grammarlychatgpt to shorten "projective space" into 5 characters or less.)

Incidentally, we have
⊢ $\mathbb{Prj}_n$ = (𝑛 ∈ ℕ<sub>0</sub>, 𝑘 ∈ DivRing ↦ ($\mathbb{Prj}$‘(𝑘 freeLMod (1...𝑛))))

But based on the notation of $\mathbb{RP}^n$, I think the arguments should be switched?

**Comment by benjub** [comment]
Ok. Then I think `\operatorname{\mathbb{Proj}}` and  `\operatorname{\mathbb{Proj}_\mathrm{n}}` would do... if LaTeX came with lowercase blackboard boldface, but since this is not the case without extra packages, probably
`\operatorname{\mathbb{P}\mathrm{roj}}` and `\operatorname{\mathbb{P}\mathrm{roj}_\mathrm{n}}` will do. (Saving the "o" does not save much, and looks strange. The Proj construction is denoted "Proj" after all.)

> But based on the notation of , I think the arguments should be switched?

No, I think arguments are ok this way. Trying to mimic the notation $\mathbb{RP}^n$ using infix notation seems a bit weird, and $( \mathbb{Proj}_n \quad ' < d , K> )$ looks ok to me, and more readily understood compared to $( K \mathbb{Proj}_n d )$. The display is not great, and the index should use \mathrm, but you get the idea.
