### ISSUE TITLE
Fix apartness LaTeX in iset.mm

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#3050]
Right now iset.mm has

```
htmldef "=//=" as ' # '; 
  althtmldef "=//=" as ' # ';
  latexdef "=//=" as "\apart";
htmldef "#RR" as ' #<SUB>&#8477;</SUB> ';
  althtmldef "#RR" as ' #<SUB>&#8477;</SUB> '; 
  latexdef "#RR" as "\apart_\mathbb{R}";
```

which doesn't work as described in https://github.com/metamath/set.mm/pull/3039#issuecomment-1436105224 . Probably never did work given that generating LaTeX is (we think) a little used feature.

As for the history, I think I just grabbed `\apart` from https://github.com/HoTT/book and didn't really think too much about where it was defined, which apparently is https://github.com/HoTT/book/blob/95ed534fa8ea321b4beacd2ce9184877e95463a8/macros.tex#L615

So maybe we can just change `\apart` to `\mathrel{\#}` both places it appears in iset.mm? (Disclaimer: haven't tried it yet, and also willing to listen to people who know more LaTeX than me).

**Comment by benjub** [comment]
Or you use `\neq\!\!\!\neq` as I suggested above the comment that you quoted.
The displays are a bit different: my solution shows a wider symbol with more slanted lines (same slope as `\neq` ($\neq$) of course); it's more semantic, since "apart" is a bit like "very different" (or "decidedly different").

(\mathrel is there in order to have correct spacing with surrounding operands, but since `\neq` is understood to be a binary relation, there is no need for \mathrel in the second case)

**Comment by benjub** [comment]
Personally, I prefer `\neq\!\!\!\neq` for its greater similarity with `\neq` ($\neq$), both for the diplay and the meaning. I think that the hash symbol is actually an intent to look like a doubly negated equality, but since we can have the real deal, we might as well use it.

**Comment by jkingdon** [comment]
> Personally, I prefer `\neq\!\!\!\neq` for its greater similarity with `\neq` (≠), both for the diplay and the meaning. I think that the hash symbol is actually an intent to look like a doubly negated equality, but since we can have the real deal, we might as well use it.

Ah, thanks for the clarification of what that was about (I didn't notice it among the various comments on the other issue).

Although I'm used to `#` I see the point about making it look similar to not equal, so sure, let's go with the `\neq\!\!\!\neq` one.
