### ISSUE TITLE
Show that real number trichotomy implies LPO

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#3423]
According to https://ncatlab.org/nlab/show/principle+of+omniscience#analytic , real number trichotomy implies the Limited Principle of Omniscience, or in our notation:

```
$( Real number trichotomy implies the Limited Principle of Omniscience (LPO).
   We expect that we'd need some form of countable choice to prove the
   converse.  (Contributed by Jim Kingdon, 23-Aug-2023.) $)
trilpo $p |- ( A. x e. RR A. y e. RR ( x < y \/ x = y \/ y < x )
    -> _om e. Omni ) $=
  (  ) ? $.
```

What we need to prove (per https://us.metamath.org/ileuni/isomnimap.html ) is that given an infinite sequence F of zeroes and ones, either the sequence contains a zero or it is all ones.

Here's one sketch of a proof: Construct a real number A whose representation in base two consists of a zero, a decimal point, and then the numbers of the sequence. Compare with with one using trichotomy. Clearly we can rule out 1 < A . If A = 1 then it must be `0.1111111...` . If A < 1 then it must contain a zero in some position.

Our number would be ``sum_ i e. NN ( ( 1 / ( 2 ^ i ) ) x. ( F ` i ) )`` . See https://us.metamath.org/ileuni/geoihalfsum.html which shows that if the F's are all one, then the sum is one. But do we have a way to prove the reverse: if the sum is one, then the F's are all one?

Likewise, it feels like if A < 1 we can know how far out in the sequence to go, based on the distance between A and one, to get a zero. Chances are we'll need to compute that position in some fairly direct way to be able to prove it exists in the sense of `∃`.

**Comment by digama0** [comment]
> But do we have a way to prove the reverse: if the sum is one, then the F's are all one?

If `F(n)` is zero, then the sum is upper bounded by `1 - 2^(-n)` and hence cannot be `1`. (We are using decidability of the `F(i)` here, they must be 0 or 1.)

Likewise, if `A < 1` then let `n` be such that `2^(-n) < 1 - A`, then we get a contradiction from `A. i < n, F(i) = 1` because then the sum is lower bounded by `1 - 2^(-n) > A`. Here we need decidability of finite forall to show `E. i < n, F(i) = 0`.

**Comment by jkingdon** [comment]
> Here we need decidability of finite forall

We have https://us.metamath.org/ileuni/finomni.html which would appear to be what we need pretty directly.

**Comment by jkingdon** [comment]
Any particular convergence test I should be trying to formalize? I didn't see anything beyond https://us.metamath.org/ileuni/climcvg1n.html which would suffice but might be a lot of work to apply directly. I'm thinking of something like: if the nth term of a series is at least zero and no greater than `( B ^ n )` (where B e. RR and ``0 < B < 1``), then the series converges.

As far as I could tell from a somewhat quick glance, set.mm does this sort of thing via things like cvgcmp which does not specify a rate of convergence.

**Comment by digama0** [comment]
A similar thing in set.mm is rpnnen2lem5 or rpnnen2lem6, which does indeed use cvgcmp. But I would expect that to still apply even if you need a modulus of convergence, because any modulus which works for the bounding series also works for the bounded one.

**Comment by jkingdon** [comment]
> A similar thing in set.mm is rpnnen2lem5 or rpnnen2lem6, which does indeed use cvgcmp. But I would expect that to still apply even if you need a modulus of convergence, because any modulus which works for the bounding series also works for the bounded one.

I'm not sure what you are suggesting but if I correctly understand, https://us.metamath.org/mpeuni/cvgcmp.html as stated in set.mm will not be provable because the bounding sequence ` F ` is only known to be convergent - we don't have a bound on how fast it converges.

What I know we can prove (because I just did it on the https://github.com/jkingdon/set.mm/tree/trilpo branch) is:

```
cvgcmp2n.cl $e |- ( ( ph /\ k e. NN ) -> ( G ` k ) e. RR ) $.
cvgcmp2n.ge0 $e |- ( ( ph /\ k e. NN ) -> 0 <_ ( G ` k ) ) $.
cvgcmp2n.lt $e |- ( ( ph /\ k e. NN ) -> ( G ` k ) <_ ( 1 / ( 2 ^ k ) ) )
      $.
cvgcmp2n $p |- ( ph -> seq 1 ( + , G ) e. dom ~~> ) $= ... $.
```

I should have that branch turned into a pull request once I add the rest of the proof that trichotomy implies LPO which should not be hard from here (as discussed in the comments on this issue).

**Comment by digama0** [comment]
It sounds like there is some kind of loss of information here which makes me suspect that the theorems are not as strong as they should be. Either convergence means convergence with some modulus of convergence, in which case you can transfer this modulus from F to G, or it means convergence without a modulus, in which case you don't need to manifest one for G. As far as I know there is no reason cvgcmp should not be provable with either notion of convergence.

EDIT: After looking more into the foundations you have defined, I see the problem is that ax-caucvg is mismatched with df-clim, since the former uses a modulus of convergence and the latter does not. You can get a modulus of convergence from df-clim if you use the axiom of countable choice, but assuming you want to avoid that you should probably swap the quantifiers in df-clim to say `E. j : RR+ --> ZZ A. x e. RR+` instead of `A. x e. RR+ E. j e. ZZ`. It is also reasonable to keep both versions and call this one "strong convergence" or the like, but I think in most cases you will want to use strong convergence and this is the one that satisfies cvgcmp. AFAICT every convergence theorem you have proven so far is a strong convergence theorem.

**Comment by jkingdon** [comment]
> the problem is that ax-caucvg is mismatched with df-clim, since the former uses a modulus of convergence and the latter does not

Ah, that's an interesting set of questions.  I have submitted this at #3441 and to be honest I'm not completely sure which of the options presented there is best. Probably not something we need to rush to decide soon, but it is good to raise awareness of what our choices are.
