### ISSUE TITLE
df-selv is incorrect?

### ISSUE THREAD

**Issue by icecream17** [metamath/set.mm#3666]
![image](https://github.com/metamath/set.mm/assets/58114641/a6aced21-9e7f-48d4-b609-2500d3e5e3eb)

Let `G` be the function highlighted here. (The last argument to `evalSub` in `selectVars`)

<details><summary>images of theorems</summary>

![image](https://github.com/metamath/set.mm/assets/58114641/c697c209-f318-4042-92c9-9fb9c56c4132)
![image](https://github.com/metamath/set.mm/assets/58114641/70457915-8e65-466f-b0e6-26a6e84871e7)
![image](https://github.com/metamath/set.mm/assets/58114641/bedbf81f-c2b8-4a3c-b062-51d47aeb6dae)

</details>

By selvval2lemn and rhmf, ``(((I evalSub S) ` ran C) : ( Base ` W ) --> ( Base ` T )``

By selvval2lem4 we have ``(C o. F) e. ( Base ` W )``

By pwsbas and elmapg, ``( Base ` T ) = ( B ^m ( B ^m I ) )``, so:

``((((I evalSub S) ` ran C) ` (C o. F)) : (anyfunction I --> B) --> B``.

Which is inconsistent for two reasons. 

1. First the domain doesn't match: `G` is not a function `I --> B`
    <details><summary>~ mvrcl image</summary>
    
    ![image](https://github.com/metamath/set.mm/assets/58114641/30192833-b0f9-4793-a445-5b306d9a295a)

    Note that `C` maps `BaseR` to `BaseS` as seen in step 20 of https://us.metamath.org/mpeuni/selvval2lem4.html

    </details>

    ...rather it is `I --> Base(J mPoly S) or Base(I-J mPoly S)` (where S is `I-J mPoly R`)
 
   1. This could be fixed by changing any result of ``(G`x)`` to ``((G`x)`x)``. That way it would collapse to `I --> Base(S)` i.e. `I --> B`

2. And lastly the purpose of df-selv is to take a subset of indices `J` and a polynomial `F : I --> R` and return a polynomial
    `? : J --> I-J --> R`

    But instead we get a polynomial in ``B = ( Base ` S )`` i.e.
    `? : I-J --> R`, so the range doesn't match either. I'm not sure how this could be fixed

**Comment by tirix** [comment]
Ok, sorry for the long time to answer this, this is not a trivial problem, and I'm not sure about how to solve this either. 
I agree that the signature you obtain is not the correct one.

Best would be to call @digama0 since he is the original author of [`~df-selv`](https://us.metamath.org/mpeuni/df-selv.html).

Here are my thoughts, though, starting back from zero, and not trying to fix the provided definition:
Let's give some names, to the base set `K`, and to the domains of the multivariate polynomials, which are combinations of exponents for the variables:
```
K = ( Base ` R )

C = { f e. ( NN0 ^m J ) | ( `' f " NN ) e. Fin }
D = { f e. ( NN0 ^m ( I \ J ) ) | ( `' f " NN ) e. Fin }
E = { f e. ( NN0 ^m I ) | ( `' f " NN ) e. Fin }
```
With this we have:
```
F e. ( Base ` ( I mPoly R ) )
F : E --> K
```
And we want to have:
```
( ( I selectVars R ) ` J ) : ( Base ` ( I mPoly R ) ) --> ( Base ` ( J mPoly ( ( I \ J ) mPoly R ) ) )
( ( ( I selectVars R ) ` J ) ` F ) : C --> ( Base ` ( ( I \ J ) mPoly R ) )
( ( ( ( I selectVars R ) ` J ) ` F ) ` a ) : D --> K
```
For a `a e. C`.

This means that our ``( ( ( I selectVars R ) ` J ) ` F )`` would look like this:
```
( ( ( I selectVars R ) ` J ) ` F ) = ( a e. C |-> ( b e. D |->  ... ) )
```
Now to fill in the ellipsis `...`, we have:
```
a : J --> NN0
b : ( I \ J ) --> NN0
```
And we know we can apply `F` to some
```
c : I --> NN0
```
Here I think the way to combine `a` and `b` into such a `c` would simply be union as in `c = ( a u. b )`. This gives as a target expression:
```
( ( ( I selectVars R ) ` J ) ` F ) = ( a e. C |-> ( b e. D |-> ( F ` ( a u. b ) ) ) )
```
So to put it all together, I get something like:
```
selectVars = ( i e. _V , r e. _V |-> ( j e. ~P i |-> ( f e. ( Base ` ( i mPoly r ) ) |-> 
      ( a e. { g e. ( NN0 ^m J ) | ( `' g " NN ) e. Fin } |-> b e. { h e. ( NN0 ^m ( i \ j ) ) | ( `' h " NN ) e. Fin } |-> ( f ` ( a u. b ) ) ) ) )
```
This is what I believe would logically be needed, but it needs to be carefully reviewed!

**Comment by tirix** [comment]
PS. We might be more generic and remove the finite support requirements, as in:
```
selectVars = ( i e. _V , r e. _V |-> ( j e. ~P i |-> ( f e. ( Base ` ( i mPoly r ) ) |-> 
      ( a e. ( NN0 ^m J ) |-> b e. ( NN0 ^m ( i \ j ) ) |-> ( f ` ( a u. b ) ) ) ) )
```
But then this might go as far as:
```
selectVars = ( i e. _V , r e. _V |-> ( j e. _V |-> ( f e. _V |-> 
      ( a e. _V |-> b e. _V |-> ( f ` ( a u. b ) ) ) ) )
```
I think the result will still be valid, if the domains of the application theorems are chosen correctly.

**Comment by digama0** [comment]
> But then this might go as far as:
> 
> ```
> selectVars = ( i e. _V , r e. _V |-> ( j e. _V |-> ( f e. _V |-> 
>       ( a e. _V |-> b e. _V |-> ( f ` ( a u. b ) ) ) ) )
> ```
> 
> I think the result will still be valid, if the domains of the application theorems are chosen correctly.

No, you can't use `e. _V` for functions returned by functions, because the mapsto operator has to return a set. So only `i` and `r` could have domain `_V` here. We also don't want to remove the finite support requirement because this function itself needs to live in the right type, so that it can be a homomorphism between the appropriate spaces.

---

Here's a re-derivation of the original expression:
```
selectVars = ( i e. _V , r e. _V |-> ( j e. ~P i |-> 
  ( f e. ( Base ` ( i mPoly r ) ) |->
    [_ ( ( i \ j ) mPoly r ) / s ]_
    [_ ( algSc ` s ) / c ]_
    ( ( ( ( i evalSub s ) ` ran c ) ` ( c o. f ) ) `
      ( x e. i |-> if ( x e. j , ( ( j mVar s ) ` x ) ,
        ( c o. ( ( ( i \ j ) mVar r ) ` x ) ) ) ) ) ) ) )
```
hopefully with fewer bugs.

The definitions involved are as follows (writing things in prefix for clarity):
* $mPoly(I, R)$ is the set of multivariate polynomials with index set $I$ and scalar ring `R`. Concretely, the base set is $(I\to_0\Bbb{N})\to R$.
* $algSc(S)$ is the map from the scalar ring to the base set in any algebra. For multivariate polynomials that means the constant polynomial. So this is a function $R\to S$.
* $evalSub(I, R, K)$ is a function $mPoly(I,K)\to(I\to R)\to R$ which evaluates a polynomial with coefficients in $K\subseteq R$ given values for each variable in $I$.
  * For this case we use $K:=\mathrm{ran}(C)$, that is, the scalar ring viewed as a subset of the polynomial ring.
* $mVar(I, R):I\to mPoly(I,R)$ gives the $i\in I$'th variable of the polynomial ring.

Now consider $J\subseteq I$ some subset of the index set and $F\in S:=mPoly(I,R)$ an $I$-indexed polynomial in $R$. We want to return a $J$-indexed polynomial in $J\setminus I$-indexed polynomials in $R$.

Let $T':=mPoly(I\setminus J,R)$ and $T:=mPoly(J,T')$, this is the target space. We want to use $evalSub$ to produce elements in this space, but the target space is $T$ and $F$ has codomain $R$. $C_1:=algSc(T):T'\to T$ is a function from $T'$ (the scalar ring of $T$) to $T$ though, so we also have to compose with $C_2:=algSc(T'):R\to T'$. So the application starts with $evalSub(I,T,\mathrm{ran}(C_2\circ C_1))(C_2\circ C_1\circ F)$.

The second argument is a $I\to T$ function giving the evaluation of the variables. The idea is that half of the variables are interpreted as variables, and the other half are constants (where the constant is a variable in the other polynomial space). So suppose we have $i\in I$:

* If $i\in J$, we want to evaluate this to the variable $mVar(J,T')(i)\in T$
* If $i\in I\setminus J$, we want to evaluate this to a constant (so we apply $C_1$ to an element of $T'$) where the element is $mVar(I\setminus J,R)(i)\in T'$.

The result is an element of $T$, which is what we wanted to produce.

All together, we have:

```
fun I ∈ V, R ∈ V, J ⊆ I ↦
fun F ∈ Base(mPoly(I, R)) ↦
let T' := mPoly(I \ J, R)
let T := mPoly(J, T')
let C₁ := algSc(T)
let C₂ := algSc(T')
evalSub(I, T, ran(C₂ ∘ C₁))
  (C₂ ∘ C₁ ∘ F)
  (fun i ∈ I ↦ 
    if i ∈ J then
      mVar(J, T')(i)
    else
      C₁(mVar(I \ J, R)(i)))
```

Or in metamath syntax:
```
selectVars = ( i e. _V , r e. _V |-> ( j e. ~P i |-> 
  ( f e. ( Base ` ( i mPoly r ) ) |->
    [_ ( ( i \ j ) mPoly r ) / u ]_
    [_ ( j mPoly u ) / t ]_ 
    [_ ( algSc ` t ) / c ]_
    [_ ( ( algSc ` u ) o. c ) / d ]_
    ( ( ( ( i evalSub t ) ` ran d ) ` ( d o. f ) ) `
      ( x e. i |-> if ( x e. j , ( ( j mVar u ) ` x ) ,
        ( c ` ( ( ( i \ j ) mVar r ) ` x ) ) ) ) ) ) ) )
```
