### ISSUE TITLE
If not equal implies apart, Markov's principle follows

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#3758]
This is exercise 11.10 of [HoTT]. In our notation:

```
A. x e. RR A. y e. RR ( x =/= y -> x =//= y ) -> _om e. Markov
```

**Comment by benjub** [comment]
Probably the same type of construction as for the omniscience problem of #3757 ? Given a property $P \colon \omega \to 2$, define $x:=\sum_n P_n 2^{-n}$. If $x = 0$, then $\neg \exists n P_n=1$. Therefore, if $\neg\neg \exists n P_n=1$, then $x \neq 0$, so by hypothesis, $x$ is apart from zero, so it is positive (since it is a sum of nonegative numbers, it cannot be negative). Therefore, it is larger than some $2^{-N}$, so there is a natural $n$ (at most $N$) such that $P_n = 1$.

**Comment by jkingdon** [comment]
> Probably the same type of construction as for the omniscience problem of #3757 ? Given a property P:ω→2, define x:=∑nPn2−n. If x=0, then ¬∃nPn=1. Therefore, if ¬¬∃nPn=1, then x≠0, so by hypothesis, x is apart from zero, so it is positive (since it is a sum of nonegative numbers, it cannot be negative). Therefore, it is larger than some 2−N, so there is a natural n (at most N) such that Pn=1.

Although the proof at #4062 uses https://us.metamath.org/ileuni/ismkvmap.html rather than https://us.metamath.org/ileuni/ismkvnex.html and may differ in a few other details, as far as I can tell it is roughly the same proof as the one being described here.
