### ISSUE TITLE
The sine function is decreasing over [2,4]

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#3840]
That is, we would like to prove:

```
  $( The sine function is decreasing between two and four.
     (Contributed by Jim Kingdon, 21-Feb-2024.) $)
  sindec $p |- ( ( A e. ( 2 [,] 4 ) /\ B e. ( 2 [,] 4 ) /\ A < B )
      -> ( sin ` B ) < ( sin ` A ) ) $=
    ? $.
```

using only the theorems now in iset.mm (which include double angle formulas, half angle formulas, formulas for the sine of a sum or difference, etc).

My thought process was that `B - A` is in the range (0,2] and so you'd think that would help us apply theorems like https://us.metamath.org/ileuni/sin02gt0.html . However, unless I missed something, I didn't see how to just expand ``( sin ` ( A + ( B - A ) ) )`` using `sinadd` and have everything just work easily.

Oh and in case the context helps, the larger project is to intuitionize https://us.metamath.org/mpeuni/pilem3.html (or some similar lemma) using the strict monotonic intermediate value theorem from #3837

**Comment by digama0** [comment]
The original definition was to use the first positive root of cos(x) instead of the first positive root of sin(x), which is a bit annoyingly far away for these estimates. Nevertheless, it is possible to do using double angle formulas etc:

* $\cos x$ is negative for $2 < x < 4$, because $\cos(2 + 2x) = \cos 2 \cos^2x - 2 \sin 2 \cos x \sin x - \cos 2 \sin^2 x$ and all terms are negative
* $\sin b<\sin a$ when $2 &lt; a < b < 4$ because if we let $x=\frac{a+b}2$ and $y=\frac{b-a}2$ then $2 &lt; x<4$ and $0 &lt; y<1$ and $\sin a-\sin b=\sin(x+y)-\sin(x-y)=2\cos x\sin y$ which is negative.

You can probably make the bounds weak inequalities, but it would be useful to strengthen cos01gt0 to $-1\le x \le 1$ for that.

**Comment by jkingdon** [comment]
>  $\cos(2 + 2x) = \cos 2 \cos^2x - 2 \sin 2 \cos x \sin x - \cos 2 \sin^2 x$ and all terms are negative

This doesn't seem to be correct as written and I'm not sure how to fix it.

Consider the third term. $\cos 2$ is negative, $\sin^2 x$ is positive, and this term has a negative sign in front of it so the net contribution of this term is positive, not negative.

In fact, the first term and the third term together represent (a constant factor times) $\cos 2x$ which is positive for x = $1/2$ and negative for x = 1, which would appear to doom any attempt to look at the sign of the second term in isolation.

**Comment by benjub** [comment]
> >  $\cos(2 + 2x) = \cos 2 \cos^2x - 2 \sin 2 \cos x \sin x - \cos 2 \sin^2 x$ and all terms are negative

> This doesn't seem to be correct as written and I'm not sure how to fix it.

Looks correct to me: use $\cos(2 + 2x) = \cos 2 \cos 2x - \sin 2 \sin 2x$ and $\cos(2x) = (\cos x)^2 - (\sin x)^2$ and $\sin(2x) = 2 \sin x \cos x$.

**Comment by jkingdon** [comment]
> > > cos⁡(2+2x)=cos⁡2cos2⁡x−2sin⁡2cos⁡xsin⁡x−cos⁡2sin2⁡x and all terms are negative
> 
> > This doesn't seem to be correct as written and I'm not sure how to fix it.
> 
> Looks correct to me: use cos⁡(2+2x)=cos⁡2cos⁡2x−sin⁡2sin⁡2x and cos⁡(2x)=(cos⁡x)2−(sin⁡x)2 and sin⁡(2x)=2sin⁡xcos⁡x.

I got the same thing for that part of the calculation.

The part I'm questioning is "all terms are negative" (which is what is supposed to produce cos⁡(2+2x) < 0).

**Comment by benjub** [comment]
> I got the same thing for that part of the calculation.
> 
> The part I'm questioning is "all terms are negative" (which is what is supposed to produce cos⁡(2+2x) < 0).

Sorry, I read too fast and missed that second part...

**Comment by icecream17** [comment]
cosneg, cosbnd2, cos01bnd, cos01gt0, sin02gt0, sincos2sgn should verify digama0's statement

Note that the first bullet point might be clarified by introducing the variable y:

* ..., because $\cos(2 + 2y) = \cos 2 \cos^2y - 2 \sin 2 \cos y \sin y - \cos 2 \sin^2 y$, (for $0 < y < 1$)

**Comment by jkingdon** [comment]
The main progress I have made so far is to prove ``( 4 / 9 ) < ( sin ` 2 )``.

I suppose the most promising approach is to find bounds on some or all of the terms of $\cos 2 \cos^2x - 2 \sin 2 \cos x \sin x - \cos 2 \sin^2 x$ so that we can show that the positive term offsets the others little enough that the result remains negative.

**Comment by icecream17** [comment]
<details>

We are considering 

$\cos x$ is negative for $2 < x < 4$

$\cos (2 + 2y)$ is negative for $0 < y < 1$

$\cos 2 \cos^2 y - 2 \sin 2 \cos y \sin y - \cos 2 \sin^2 y$ is negative for $0 < y < 1$

$\cos^2 y - \frac{2 \sin 2 \cos y \sin y}{\cos 2} - \sin^2 y$ is positive (dividing by negative number $\cos 2$

(We have the identity $\cos 2y = \cos^2 y - \sin^2 y$ so)
$\cos 2y - \frac{2 \sin 2 \cos y \sin y}{\cos 2}$ is positive

The first term is $\cos 2 \cos^2 y$

$-7/9 < \cos 2 < -1/9$ by cos2bnd
$1/3 < \cos y < 1$ by cos01bnd
$\cos^2 y$ or $\cos \cos y$ is positive by cos01gt0

The second term is $-2 \sin 2 \cos y \sin y$

-2 is negative
$4/9 < \sin 2 < 1$
$1/3 < \cos y < 1$ is positive
$0 < ... < \sin y < y$ by sin01bnd

Finally we have $- \cos 2 \sin^2 y$

$0 < ... < \sin^2 y < \sin y$ by sin01bnd
</details>

**edit** Oh the last term is positive... guess more precise bounds will have to be used, I see

**Comment by digama0** [comment]
Sorry, you are right, that proof was incorrect. Here's another proof:

1. $\cos(2x)=2\cos^2 x-1$ is negative if $-\sqrt{2}/2<\cos x<\sqrt{2}/2$
2. $-\sqrt{2}/2<\cos(2x)=2\cos^2 x-1< \sqrt{2}/2$ for $1/2\le x\le 1$ by bounds on $\cos(x)$:
  * $2\cos^2 x-1< \sqrt{2}/2$ using $\cos x\le 1 - x^2/3$
  * $2\cos^2 x-1> -\sqrt{2}/2$ using $\cos x\ge 1 - x^2/2-x^4\frac{5}{4\cdot 4!}$

For the second part, we have to undo some constant weakening performed in ef01bnd.

---

At this point, the proof is looking like more trouble than it's worth. I think it would be better to first prove the existence of $\pi/2$ as a root of $\cos x$, at which point it becomes a lot easier to do these kind of arguments because lots of terms cancel. The argument for this is similar:

* $\cos(a+b)-\cos(a-b)=-2\sin a\sin b$, so if $0&lt; a,b\le 2$ then $\cos(a+b)&lt;\cos(a-b)$ and hence $\cos$ is strictly decreasing on $(0,2)$. Also $\cos 1&gt; 1/3&gt;0$ and $\cos 2&lt; -1/9&lt;0$.
* Therefore there exists a $1<\rho<2$ (which is actually $\pi/2$) such that $\cos x=0$.
* $\sin(2\rho)=2\cos\rho\sin\rho=0$
* For $\rho&lt; x<2\rho$, $\sin(x)=\sin(2\rho-x)>0$ because $\rho<2$. Therefore $\sin(x)>0$ for the whole range $(0,2\rho)$ so $\pi:=2\rho$ must be the first positive zero of $\sin$.

Note that you still can't prove sin is decreasing on [2,4] given this proof of existence of $\pi$, because if $\rho$ happened to be particularly small, then the crossing of $\cos x$ could occur at any point between $3$ and $6$, so we don't know that [3,4] has no crossings. And of course knowing $\cos x$ has no crossings on [2,3] isn't good enough since we're aiming for a number in the vicinity of 3.14.

**Comment by icecream17** [comment]
the derivative of sin is cos, so an alternate proof could be that cos is negative from [2, 4]

using cos2t and rearranging we have $\cos 4a = 8 (\cos a)^4 - 8 (\cos a)^2 + 1$ (where $\frac{1}{2} \le a \le 1$)

By cos01bnd $\cos a \le \frac{11}{12}$. The difference $(\cos a)^4 - (\cos a)^2$ is minimized the closer `\cos a` is to 1.
So we take `8 * ((11/12)^4 - (11/12)^2) + 1` and get -0.07, tada...

**Edit**: as per the below comment the last line of reasoning doesn't work. We have $\frac{1}{3} \le \cos a$ from cos01bnd but that bound isn't good enough. (A bound of 1/2 would be good enough)

**Comment by digama0** [comment]
I think derivative reasoning is not available yet at this point. It will in any case be proved using the trig addition formula, so that's why they are mostly interchangeable and can be used to prove the same facts.

> The difference $(\cos a)^4 - (\cos a)^2$ is minimized the closer `\cos a` is to 1.

How would you prove this? (Oh, you are saying that $x^4-x^2$ is increasing near 1, and in particular in the range [11/12, 1].) It's actually increasing starting at $\sqrt 2/2$, and factoring it as $8x^4-8x^2+1=2(2x^2-1)^2-1$ makes that most obvious (and conveniently, this is also the expression you originally get when applying $\cos(2x)=2\cos^2x-1$ twice).

**Comment by jkingdon** [comment]
> the derivative of sin is cos, so an alternate proof could be that cos is negative from [2, 4]
> 
> using cos2t and rearranging we have cos⁡4a=8(cos⁡a)4−8(cos⁡a)2+1 (where 12≤a≤1)
> 
> By cos01bnd cos⁡a≤1112. The difference (cos⁡a)4−(cos⁡a)2 is minimized the closer `\cos a` is to 1. So we take `8 * ((11/12)^4 - (11/12)^2) + 1` and get -0.07, tada...

I have formalized this except for the lemma

```
  $( Lemma for ~ cos24lt0 .  (Contributed by Jim Kingdon, 5-Mar-2024.) $)
  cos24lt0lemcalc $p |- ( A e. ( 0 (,) ( ; 1 1 / ; 1 2 ) )
      -> ( ( 2 x. ( ( ( 2 x. ( A ^ 2 ) ) - 1 ) ^ 2 ) ) - 1 ) < 0 ) $=
    (  ) ? $.
```

(the lower bound, here shown as zero, could be higher if need be).

What I have so far is at https://github.com/metamath/set.mm/compare/develop...jkingdon:set.mm:cos24lt0

**Comment by digama0** [comment]
Are you sure you don't want to try the [alternative proof](https://github.com/metamath/set.mm/issues/3840#issuecomment-1975755985)? There is a lot less numerical computation in that one.

**Comment by jkingdon** [comment]
> Are you sure you don't want to try the [alternative proof](https://github.com/metamath/set.mm/issues/3840#issuecomment-1975755985)? There is a lot less numerical computation in that one.

Not really sure about anything at this point.

In some ways the proof from `cos24lt0lemcalc` is the most straightforward, but in addition to the numerical computation as you point out, I'm not sure it works (when I tried sketching out a proof I thought maybe I needed a lower bound of `sqrt 2 / 2` in place of zero given there, but that's not possible because ``cos ` 1`` is about 0.5403).

The alternative proof linked above does have some conceptual bits to figure out which I suppose might be what you had in mind with "more trouble than it's worth". I'd probably have to start formalizing at least parts of it to even understand what would be involved.

The proof in terms of the first positive zero of the cosine (rather than the sine) was not my first impulse, just because it diverges a bit more than the others from set.mm. But it might be looking like the best one right now. I think once we formalize all the material in the second half of https://github.com/metamath/set.mm/issues/3840#issuecomment-1975755985 we're basically back in line with the set.mm development. (And I'm not worried about proving that sine is decreasing over [2,4] in particular - I only proposed it as a means to the end of https://us.metamath.org/mpeuni/sinpi.html , https://us.metamath.org/mpeuni/pigt2lt4.html , and https://us.metamath.org/mpeuni/pire.html ).

**Comment by icecream17** [comment]
> ```
>   $( Lemma for ~ cos24lt0 .  (Contributed by Jim Kingdon, 5-Mar-2024.) $)
>   cos24lt0lemcalc $p |- ( A e. ( 0 (,) ( ; 1 1 / ; 1 2 ) )
>       -> ( ( 2 x. ( ( ( 2 x. ( A ^ 2 ) ) - 1 ) ^ 2 ) ) - 1 ) < 0 ) $=
>     (  ) ? $.
> ```

unfortunately this is impossible since if A = 1/3 you get some positive number... the actual bound is ~~sqrt(2)/2~~ [sqrt(2-sqrt2)/2](https://mathsolver.microsoft.com/en/solve-problem/2%20%7B%20%60left(2%20%7B%20x%20%20%7D%5E%7B%202%20%20%7D%20%20-1%20%60right)%20%7D%5E%7B%202%20%20%7D%20%20-1%20%3D%20%200) to 11/12

Edit: Wow I shouldn't comment when I just woke up, this was already said
Edit 2: There is also the problem of showing that `cos 1` is at least the lower bound. Currently the lower bound for `cos 1` is 1/3, which is not good enough. So perhaps that is more of an indication of proving more library theorems like establishing $\pi/2$ as a root of $\cos$, as said above.

**Comment by digama0** [comment]
> The proof in terms of the first positive zero of the cosine (rather than the sine) was not my first impulse, just because it diverges a bit more than the others from set.mm. But it might be looking like the best one right now. I think once we formalize all the material in the second half of [#3840 (comment)](https://github.com/metamath/set.mm/issues/3840#issuecomment-1975755985) we're basically back in line with the set.mm development. (And I'm not worried about proving that sine is decreasing over [2,4] in particular - I only proposed it as a means to the end of https://us.metamath.org/mpeuni/sinpi.html , https://us.metamath.org/mpeuni/pigt2lt4.html , and https://us.metamath.org/mpeuni/pire.html ).

Right, I assumed as much (that you only cared about proving the existence and bounds on pi), and not so much that sine is decreasing on [2,4] per se. And just to be clear the alternative proof I was referring to was the one in the second half of that post. I think that the proof might also be useful for set.mm, and would even go so far as to define pi as 2 * min({x > 0 | cos(x)=0}) instead of min({x > 0 | sin(x)=0}), because it saves work in this proof (I'm not even sure there is a reason to compute bounds on sin(4) and cos(4) in set.mm if not for this proof).

**Comment by jkingdon** [comment]
> Right, I assumed as much (that you only cared about proving the existence and bounds on pi), and not so much that sine is decreasing on [2,4] per se

For that reason I'll close this issue now that #3859 is merged.
