### ISSUE TITLE
</table> tags in AS's mathbox are outside <html> blocks

### ISSUE THREAD

**Issue by CatsAreFluffy** [metamath/set.mm#3928]
The </table> tags in the descriptions of many theorems in Alan Sare's (eg [~hbra2VD](https://us.metamath.org/mpeuni/hbra2VD.html) are outside of the <html> blocks, which causes problems for software that interprets <html> blocks, like mm-web-rs.

**Comment by digama0** [comment]
ideally this would be caught by `verify markup`, although I'm not sure exactly what it should look for. Something tag-looking outside `<HTML>`? Or an unclosed tag inside `<HTML>`?

**Comment by icecream17** [comment]
Semantically, `<html>` represents the root element of an entire webpage.

I don't think using it wrong has an effect though, despite breaking [various "not permitted" structures](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/html#technical_summary).

So it's ehh, but if the workaround of adding html tags is necessary, that's alright.

**edit**: see below comment

**Comment by digama0** [comment]
`<HTML>` in metamath comments has a special meaning. It is not itself interpreted as an HTML element, but it delimits sections where HTML tags are transmitted as-is to the generated webpage. Just think of them as really elaborate quote marks for HTML code. Obviously it wouldn't make any sense to interpret them literally as `<html>` tags, because as you say there is only supposed to be one of these and it is most certainly not located in the `Description:` element of the webpage. (The fact that well formed HTML snippets will never contain `</html>` makes them a convenient choice for delimiters though.)
