### ISSUE TITLE
Contributor code RM is used twice

### ISSUE THREAD

**Issue by CatsAreFluffy** [metamath/set.mm#3987]
Both Rodolfo Medina and Remy have contributor code RM (and Remy's isn't in the right place in the list).

**Comment by wlammen** [comment]
Thanks.  Both persons assigned this code have fortunately never used it in set.mm.  Rudolfo Medina has contributed since 2010, Remi appears only in theorems marked with 25-Oct-2023.  So the shorthand RM was originally assigned Rudolfo Medina, and I think this should be kept.  I assigned Remi RMI instead, and ordered the entries again alphabetically.  See #3988 .
RM is also used in changes-set.txt.  These all belong to Rudolfo Medina.
