### ISSUE TITLE
Strengthen exmidpw from equinumerosity to equality

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#4090]
[exmidpw](https://us.metamath.org/ileuni/exmidpw.html) is `EXMID ↔ 𝒫 1o ≈ 2o`

But we could easily prove `EXMID ↔ 𝒫 1o = 2o` as well. This is a passing remark in https://mathoverflow.net/questions/452678/does-negative-trichotomy-hold-for-constructive-ordinals/475265#475265 (worded as "Note that 𝖫𝖤𝖬 is equivalent to the statement Ω=2").

The proof of exmidpw already has most of what is needed to prove this, so it shouldn't be hard.

**Comment by benjub** [comment]
@jkingdon : It would probably be more economical to prove exmidpweq in terms of exmidpw or conversely. Especially since both current proofs prove independently each implication. You only need to prove three implications, and not four, and one of them is simply "equality implies equinumerosity".

Relatedly (and it may be used in the above proof), if A is a subset of a finite set B and is equinumerous to it, then it is equal to it.  I do not know if it is in iset.mm.

**Comment by jkingdon** [comment]
> @jkingdon : It would probably be more economical to prove exmidpweq in terms of exmidpw or conversely. Especially since both current proofs prove independently each implication. You only need to prove three implications, and not four, and one of them is simply "equality implies equinumerosity".

I don't have much of an opinion about how we prove these things. So I'm unlikely to object if someone wants to revise the proofs.

> Relatedly (and it may be used in the above proof), if A is a subset of a finite set B and is equinumerous to it, then it is equal to it. I do not know if it is in iset.mm.

We have https://us.metamath.org/ileuni/fisseneq.html

This might be a bit of a tangent, but reading this does make me notice one theorem we don't have: `EXMID <-> ~P 1o e. Fin`, which I have posed as a problem at #4110 .
