### ISSUE TITLE
Add support for Euclidean Geometry

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/set.mm#49]
I think it'd be possible to select some well-known set of "axioms" defining 2D/3D Euclidean Geometry, e.g., those by [Hilbert](https://en.wikipedia.org/wiki/Hilbert's_axioms), [Tarski](https://en.wikipedia.org/wiki/Tarski's_axioms), or [Birkhoff](https://en.wikipedia.org/wiki/Birkhoff's_axioms).  Then you can build up to usual Side-Angle-Side (SAS), Angle-Side-Angle (SAS), Side-Side-Side (SSS), and CPCTC... and then many other proofs would become much easier (because they can be expressed as traditional Euclidean geometry proofs).  E.g., the isosceles triangle theorem would be trivial to prove with these tools.  It seems to me it'd be possible to connect existing axioms to Euclidean geometry, just as numbers are "created" from set and logic axioms.  I'm sure there are implications I'm not thinking of, but I thought I'd record the idea here.

**Comment by sctfn** [comment]
I've got Tarski's axioms in my mathbox already except for the upper
dimensional axiom (it needs full linear algebra for the N-dimensional
version).

**Comment by sorear** [comment]
Yeah, Tarski's axioms look like the best bet for me too.  Is upper dimension 2 doable with complex numbers?

**Comment by sctfn** [comment]
Should be - I can do it in any concrete dimension w/o LA, but I need
something like inverse matrices for the general case.

**Comment by david-a-wheeler** [comment]
@sctfn : Very interesting - I didn't realize you did that!  I was thinking that it'd be easier to prove things like the isosceles triangle theorem if I had Euclidean geometry.  However, I was thinking about using SSS and CPCTC, e.g., "side-side-side proves that these two triangles are congruent, and so by CPCTC these two corresponding angles are congruent."  I don't see anything in the Euclidean construction that defines SSS and CPCTC... am I missing them?

**Comment by sctfn** [comment]
They're not there at the moment - I haven't even defined angle yet! I
burned out a bit back since the only textbook using Tarski's Axioms is in
Germany, which I don't speak ☺️. I'll get back to it sometime soon, now
that my life is quieter.
On Jul 3, 2016 7:33 PM, "David A. Wheeler" <notifications@github.com> wrote:

@sctfn <https://github.com/sctfn> : Very interesting - I didn't realize you
did that! I was thinking that it'd be easier to prove things like the
isosceles triangle theorem if I had Euclidean geometry. However, I was
thinking about using SSS and CPCTC, e.g., "side-side-side proves that these
two triangles are congruent, and so by CPCTC these two corresponding angles
are congruent." I don't see anything in the Euclidean construction that
defines SSS and CPCTC... am I missing them?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/metamath/set.mm/issues/49#issuecomment-230182151>, or mute
the thread
<https://github.com/notifications/unsubscribe/AA80WJHM37Wk9BXQx6_eJhGmGEbHHCfzks5qSEa_gaJpZM4JD9rc>
.

**Comment by david-a-wheeler** [comment]
(This is especailly for @nmegill  @digama0 ): To my untrained eye, this axiomatic expression of Euclidean space (with arbitrary dimensions) looks pretty neat, especially if it can be expanded to the point where Euclidean proofs can be done (e.g., proofs such as those in a typical high school text that use SSS, SAS, CPCTC, etc.).  Is this a plausible addition to the *regular* set.mm proofs, or is there a fundamental weakness of them that means that they need to stay permanently in a mathbox?

**Comment by digama0** [comment]
Strictly speaking, it's not an *axiomatic proof*. Instead, it proves the Tarski axioms for R^n (and uses them to prove derived theorems?), so that in fact all the proofs only apply to R^n, not an arbitrary space satisfying the Tarski axioms.

Also, this is blocked somewhat by #52, since the Tarkski axiom stuff uses ``( EE ` n )`` extensively, and I'd like to see all that merged into extensible structure style.

**Comment by sctfn** [comment]
The thing is, any space that satisfies the Tarski axioms *must* be
isomorphic to RR^n. The continuity axiom guarantees that. The only
differences are the choice of origin point and the construction of the
reals. I figured it wasn't worth it to do the structure work for such a
small difference.

**Comment by digama0** [comment]
@sctfn That would then be a "fundamental theorem" for Tarksi spaces then, which is certainly worth proving. The lack of an origin is also a significant difference; "affine spaces" are not currently formalized in Metamath.

In general, showing that two apparently different axiomatizations are equivalent is a nontrivial and worthwhile venture. This is most cleanly done by having DefnA = <some definition> and DefnB = <something else>, with the culminating theorem being DefnA = DefnB. If the equivalence proof is sufficiently simple, you can omit DefnB, and just have DefnA = <something else> as the final result, which avoids the creation of redundant definitions. During the proof, you can use "D = <something else>" as a temporary hypothesis to substitute for DefnB before its equivalence to DefnA is known.

**Comment by sctfn** [comment]
OK, that would be a useful theorem in that case. I could rephrase the
treatment to be axiomatic in that case. Give me a few days to work out the
details.

**Comment by digama0** [comment]
@sctfn To what degree would your axioms match FL's `df-plig`? If possible I'd like to have only one unifying development for this.

**Comment by sctfn** [comment]
Given that df-plig only concerns incidence, a Tarskian system should
provide a model for it with suitable definitions.

@sctfn <https://github.com/sctfn> To what degree would your axioms match
FL's df-plig? If possible I'd like to have only one unifying development
for this.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/metamath/set.mm/issues/49#issuecomment-230369256>, or mute
the thread
<https://github.com/notifications/unsubscribe/AA80WDEjrdx-0UW2vb4W-I2WcTkJuKdrks5qSa_8gaJpZM4JD9rc>
.

**Comment by sorear** [comment]
plig is just the first chapter.  the last section of FL's mathbox has Aitken's definitions for a much larger fraction of plane geometry, which requires quite a few definitions and long axioms; it is, essentially, Hilbert's axioms.

Tarski's system seems more parsimonious but that might come at the expense of subsetability.

**Comment by sctfn** [comment]
In that case, you can use either for planar geometry. I tend to prefer
Tarski with a stack of definitions. It has fewer primitive notions, a
clearer metalogic (see the continuity axioms), and can be easily
generalized to N dimensions. The last can already be seen in axlowdim.

**Comment by digama0** [comment]
@sorear Since FL has very clearly marked all of his theorems as "don't touch" I'm not sure what if any modifications to it are permissible, but those axioms are much longer than they need to be. For example, df-plig can be written

    df-plig $a |- Plig = { x |
      ( A. a e. U. x A. b e. U. x ( a =/= b -> E! l e. x { a , b } C_ l )
        /\ A. l e. x 2o ~<_ l /\ E. l e. x l C. U. x ) } $.

and df-ibg can be written

    df-ibg $a |- Ibg = { f e. Ig | [ ( PPoints ` f ) / g ]
      [ ( PLines ` f ) / h ] [ ( coln ` f ) / d ] [ ( btw ` f ) / e ]
      A. p e. g A. q e. g
      ( ( p e q ) = ( q e p ) /\
        ( p =/= q -> ( E. a e. g p e. ( a e q ) /\ ( p e q ) =/= (/) ) ) /\
        A. r e. g ( ( ( { p , q , r } e. d /\ { p , q , r } ~~ 3o ) <->
              ( p e. ( q e r ) \/ q e. ( p e r ) \/ r e. ( p e q ) ) ) /\
      /\ A. l e. h ( ( ( ( ( p e q ) u. ( q e r ) ) i^i l ) = (/) 
              -> ( ( p e q ) i^i l ) = (/) ) /\
     ( ( q e/ l /\ ( ( p e q ) i^i l ) =/= (/) /\ ( ( q e r ) i^i l ) =/= (/) )
                     -> ( ( p e r ) i^i l ) = (/) ) ) ) ) } $.

My understanding is that FL is trying to be faithful to the way the axioms were written in Aitken, but the simplest way to write them in Metamath is not necessarily the simplest for Aitken and vice-versa.

**Comment by sorear** [comment]
Should this be moved to the mailing list?  Ideally FL would be included in any discussion of what to do with this section.

**Comment by digama0** [comment]
(FL has been notified of this conversation.) On further reflection, I think that both Aitken's (Hilbert's?) axioms and Tarski's are worth formalizing, preferably in a way which makes it easy to have a structure satisfying both systems so that we can draw parallels (ha!) between them.

Here's a proposal for Tarski's axioms as an extensible structure:

* ``P = ( Base ` X )`` is the set of points.
* ``D = ( dist ` X )`` is the "measure" of distance between points. Unlike the usage in metric spaces, we do not require that it take values in `RR`, but instead let it take values in any set whatsoever, with only equality being meaningful. Thus the primitive expression is `( x D y ) = ( z D w )`, which substitutes for `<. x , y >. Cgr <. z , w >.`. This transformation is valid for any congruence relation, because for any equivalence relation on `( P X. P )` we can take `D` to be the map from `<. x , y >.` to its equivalence class. This way, we don't need to make a new slot for a four-place relation, particularly since in all cases of interest which are metric spaces, the congruence relation *is* just  `( x D y ) = ( z D w )`.
* ``I = ( Ivl ` X )`` is a slot, which maps x,y to the closed line segment from x to y. The Tarskian betweenness relation Bxyz is `y e. ( x I z )`.
* ``L = ( Lines ` X )`` is a slot, but in Tarski's axioms it is not primitive, so we force it to equal

        L = ran ( x e. P , y e. ( P \ { x } ) |-> U. { i e. ran I | { x , y } C_ i } )
  so that it will be compatible with planar incidence geometry.

For planar incidence geometry:

* ``P = ( Base ` X )`` is the set of points.
* ``L = ( Lines ` X )`` is a slot, the set of lines.
* ``I = ( Ivl ` X )`` is a slot, which maps x,y to the closed line segment from x to y. For compatibility with Tarski's axioms above, this is *inclusive* on the endpoints; the theory of `df-plig` must be reworked to use an inclusive betweenness relation, but like the case of partial orders with `<` vs `<_`, the theory is basically the same either way.

There is an alternative base representation, which is more useful for projective geometry (which includes the hierarchy of higher objects, that is planes and volumes, plus hyperplanes/coatoms): ``B = ( Base ` L )`` is an atomic lattice (in the sense of df-lat), and the atoms are the points, the join of two distinct atoms are the lines, and so on, with the elements of `B` being the "affine subspaces" of `X`. One can make maps to and from this representation from the above.

**Comment by digama0** [comment]
FL writes:

> I have nothing to say about all that. I agree with everything. I don't know Tarski's axiomatic. It's true that Euclid's axiomatic has the drawback that we can't scale it. The dimension is fixed in stone.
It's also true that R^n is, up to isomorphisms, the only euclidean plane and if you do something in RR^N you do it in *the* euclidean plane. But, as you noted, the definition of the plane is no longer axiomatic. And you also can't compare euclidean and non-euclidean planes which was an important thread in the mathematics of the XIXth century.
 
> Your fix to my axiomatic seems to amount to a trick to mean that the points are distinct. It's a good one. Obvioulsy it couldn't be Euclid's one. He had a very little conscience of what a set is. As you noted, I've tried to be faithful to Aitken's text, which in turn is faithfull to Hilbert's one which in turn is fidel to Euclid's text with the amendments made by the geometers in the XIXth century to have a true axiomatic system. Doing this has the davantage that you can compare the different texts and their formalization easily. I will consider your suggestion carefully but I can't swear I will use it.

> Concerning ( EE `N ) I know that you want to build a complete structure with all the whistles and bells in one shot but I also know that if you do that you can't expect to build alternative structures using more fundamental ones. And the only one we will have will be the standard one.
 
> I would prefer you refrain from doing this, and you just build a complete hierarchy of
structures. More work I agree but then more amenable.

**Comment by jkingdon** [comment]
In case people aren't aware of it, there's a lot of development of formalized geometry (especially from the Tarski axioms although there is some reference to the others) at http://geocoq.github.io/GeoCoq/ . I once translated about 8 chapters of that into a metamath-like system (my proofs and writeups are archived at https://github.com/jkingdon/wikiproofs although the software which displays wiki pages or verifies the proofs is to a significant extent unmaintained/unfinished).

**Comment by tirix** [comment]
I've been recently working on [this thread of development](https://groups.google.com/d/msg/metamath/BSOOYEw2sjU/HSW8x7AQAQAJ) (which had [Mario's blessings](https://groups.google.com/d/msg/metamath/BSOOYEw2sjU/2GUw4TEpAQAJ)).
The idea is to define a generic structure with a base set and two relations (actually, operations) (betweenness and distance/congurence), and to require it to fulfill Tarski's axioms.
I hope I can release it soon!

**Comment by jkingdon** [comment]
Sounds exciting. It would be very nice to have one (or more, perhaps, but we can start with this one) formalization of the Tarski geometry axioms. Please do ask if there are any particular points you'd like help or feedback on.

**Comment by tirix** [comment]
Ok, first pull request is there: #782
Comments are welcome. 

-  lower dimension/upper dimension axioms are not yet developed
-  ` CCfld ` could be extended with the necessary slot to make it a geometry, is that a good idea? Or shall I keep a separated ` CCG ` like defined now? (in comments)
- I found it quite easy to follow [Schabhauser], more of his proofs could be added.

**Comment by avekens** [comment]
I think there is enough support for Euclidean Geometry available now, so that this issue can be closed. To show the Independence of the Parallel Postulate, we need support for Hyperbolic Geometry, as mentioned by @tirix. This can/should be tracked with #787 or a separate new issue.

Or is there anything important missing for Euclidean Geometry ?

**Comment by jkingdon** [comment]
> I think there is enough support for Euclidean Geometry available now, so that this issue can be closed.

Sounds good to me. I will confess that I haven't looked through https://us.metamath.org/mpeuni/df-trkg.html and the following sections very much so I don't have detailed comments on what is there, but at this point I think it would be more productive to open new issues for ongoing topics rather than try to keep this one open.

**Comment by david-a-wheeler** [comment]
I agree, this has been done! We've not only added Euclidean Geometry, but thanks to the Tarski geometry work have gone beyond it. Regarding the specifics in my initial issue;

* Side-Angle-Side (SAS) is proven as `tgsas` and related theorems.
* Side-Side-Side (SSS) is proven as `tgsss1` and related theorems.
* Corresponding parts of congruent triangles are congruent (CPCTC) is proved by various theorems. For segments this includes `trgcgrg`, `cgr3simp1`, and friends (for segments). For angles this seems covered by at least `cgrcgra`. It might be useful to note this in a comment.
*  isosceles triangle theorem is proven in `isoas`

YES! It's done! I mean, there's always more that could be added, but the "basic support for Euclidean Geometry" is clearly available in set.mm. Awesome!

Since I'm the one who created the issue, and I think there's agreement it's done, I shall close it. My thanks to everyone who made this happen!

**Comment by benjub** [comment]
> * `CCfld` could be extended with the necessary slot to make it a geometry, is that a good idea? Or shall I keep a separated `CCG` like defined now? (in comments)

To answer @tirix's latest question above: I think that the "geometry" should stay separate, and not be added to the extensible structure CCfld, because this Tarskian synthetic geometry is a very specific topic, well separated from the rest of set.mm.

I agree with @avekens and I think we can close this issue, unless there are reactions here in the next few days.

**edit:** looks like I didn't see the two previous messages, which already closed this issue. Still, I leave the message here since I think it was important not to leave its latest question (by Thierry) unanswered.

**Comment by tirix** [comment]
Yes this issue can be closed, thank you David!

About @benjub 's comment, I think I later defined the [` toTG `](https://us.metamath.org/mpeuni/df-ttg.html) operator which transforms any subcomplex Hilbert space to a Tarski Geometry by adding the required components. This operator can in particular be used on ` CCfld `, which fulfils the same purpose.
