### ISSUE TITLE
Request: Document how to "Intuitionize" in iset.mm's documentation

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/set.mm#594]
I would love to see the iset.mm documentation explain more about how to "intuitionize", including citations pointing to especially good books/papers and specific explanations of how to do it in metamath ("when you see X, you often need to convert to Y by following steps Z").  Pointing to a few examples of theorems that are especially good at explaining the changes (and how to do something similar) would be great.

This is probably especially a request to @jkingdon ... but anyone else's input would be welcome.

I am intrigued by intuitionistic logic, but I am hopelessly steeped in classical logic :-).  A little more explanation of what you have to change would be helpful for me, and probably for others.

**Comment by jkingdon** [comment]
Hmm, if I gave some sketchy outlines, would that be enough for you to find references in iset.mm and turn it into documentation?

1. If you see pm2.61 you'll probably end up with two theorems for the two cases. In particular, if the cases were A e. _V and -. A e. _V you probably just care about the A e. _V case.

2. Non-empty almost always needs to be changed to inhabited.

3. If the original proof relied on propositional/predicate logic which isn't a theorem of intuitionistic logic, maybe there is a way of expressing it more directly (for example, keep things as E. rather than translating to A. and negation, e.g. cbvrexcsf , sbcrext ). This is perhaps the hardest one to put in cookbook form: sometimes I just try some things and see if anything works.

4. If you are dealing with a definition, try to find the best constructive definition from the literature (HoTT book, Stanford Encyclopedia of Philosophy, Brauer, etc). Once you pick a definition, that'll affect the proofs which rely on that definition.

5. If there is case elimination on whether variables are distinct, most of the time you just need the variant with distinct variables. Sometimes you can then remove the constraint with a temporary variable (e.g. the various sbco2* variants, nfrabya).

6. Sometimes one direction of a biconditional holds, or subset holds instead of equality. You might be able to keep the easy direction and worry about the other one later.

7. If your proof relies on dveeq2 try dveeq2or and likewise for the other things downstream of ax-i12 or ax-bnd . In these cases, and perhaps others involving disjunction, jaoi is your friend.

8. If your proof is doing tricky things perhaps in the interest of shortness, try just expanding the definitions and applying logic in a straightforward way. See if this gets you a working (although perhaps longer) proof.

9. If your proof relies on a biconditional in set.mm which isn't in iset.mm, see if one direction is in iset.mm and see which direction your proof is using. For example 19.35-1 or exnalim .

10. If you are doing things with inhabited classes, you may be able to dig up some predicate logic you haven't used in a while (e.g. raaan).

11. Consider the possibility of giving up. Some things just won't have intuitionistic proofs. The more it looks like excluded middle or other non-intuitionistic statements, the more likely you are dealing with one of these. But it can be hard to have good intuition about this and rubrics like "can I use this statement to prove ph or not ph for an arbitrary proposition" are not always easy to apply.

12. Switching between 2th and 2false might help (e.g. dfnul2 , dfnul3 , rab0 ).

13. In many cases statements which are equivalent in classical logic become several non-equivalent statements (e.g. xor, ordinals, non-empty versus inhabited, apartness versus negated equality). This is usually a good place to look for a literature reference, but don't be afraid to change the statement being proved to "what you really meant is X" as appropriate.

14. If a statement has multiple equivalences in set.mm (e.g. mo2 and mo3 ) and only some of them in iset.mm, sometimes a pretty similar proof will work (that is, which one to use in the original proof may have been a fairly arbitrary choice).

15. If all else fails, ask Mario. I'm only half joking on this one.

**Comment by jkingdon** [comment]
I expanded the suggestions about disjunction a bit. Just ran into that in a proof I am working on intuitionizing today (preleq).

**Comment by jkingdon** [comment]
A lightly edited version of the above text has been merged via #732 . If anyone has further ideas or questions about intuitionization, just ask - we can always continue to improve that section.
