### ISSUE TITLE
Expand ordinals in iset.mm

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#629]
This is based on https://github.com/metamath/set.mm/pull/626#issuecomment-436090878 but omits most theorems which are described there as not provable. It also omits theorems which have been proved since that comment was written.

* ~~`onprc: provable (and this is an important one, the Burali-Forti paradox). Follows easily from ordon.` (haven't spotted this proof yet. The set.mm proof of onprc depends on ordon and ordirr and we don't yet have the latter in iset.mm)~~ has been proved

* ~~`onint: provable if you assume A is inhabited` (looks like we need a variant of tz7.5 for inhabited rather than non-empty)~~ not provable

* ~~onint0: not in original comment but looks like in addition to onint it may need a bit more work~~ not provable

* ~~`onssmin: provable if you assume A is inhabited (this will substitute for most proofs by well foundedness)` set.mm proof uses onint~~ not provable

* ~~`onminesb, onminsb: provable` set.mm proof uses onint~~ not provable

* `oninton` (with non-empty changed to inhabited): This one I think can still be salvaged though. From the fact that it is inhabited you get that it exists, and is a subset of an ordinal x. It is an intersection of transitive sets so it is transitive, and of course all its members are members of x so they are transitive too. And E. Fr A falls to subsets.

* `onintrab, onintrab2: provable` set.mm proof uses oninton

* `onnmin`: May be able to replace trichotomy with irreflexibility. If B e. A and B e. |^| A, then |^| A C_ B so B e. B, violating ordirr.

* `onminsb` set.mm proof relies on trichotomy

* `oneqmin: provable if B is inhabited, and you replace -. x e. B with B C_ x`

* `onminex` falls as written because it implies onint, but it might be useful to keep the reverse direction for subsets that do have a minimum.

* `sucon: provable` The set.mm proof will work if we get `onprc`

* ~~ordsuc. The set.mm proof relies on case elimination (on whether A is a proper class).~~ Proved for the  `A e. _V` case in #641

* `ordpwsuc: not provable, but interesting. I think suc' A = ( ~P A i^i On ) may play a role later on, it might be worth having both notions. suc A C_ suc' A, and both are ordinals.` Not sure I have an opinion yet about introducing a notation for suc' but at a minimum we can prove a variant of ordpwsuc which has subset rather than equality in the consequent.

* ~~`sucelon`~~ see #641

* `onpsssuc: provable (for both suc's)`

* ~~`ordsucss`, `ordelsuc`~~ see #636

* `onsucmin: provable for suc, not suc'`

* `ordsucelsuc: provable with suc on the left and suc' on the right. This could be a problem... there might be 
some one directional versions here too.`

* `ordsucsssuc: provable for suc, the proof is a bit complicated and uses injectivity of suc. For suc' it is provable and easy.`

* `ordsucuniel: provable`

* `ordsucun: not provable in the forward direction (implies some order totality)`

* `ordunisuc: provable`

* `orduniss2: provable (hey look, it's ordunisuc')`

* `onsucuni2: provable for both suc's`

* `0elsuc: provable for both suc's`

* ~~`limon`~~ now proved, see #634

* `onuninsuci, ordununsuc: not provable in the reverse direction` We should prove the forward direction if we can then.

* `onsucssi: provable`

* `nlimsucg: provable`

* `ordunisuc2: provable (and nicely intuitionistic), works for both suc's` see comments below

* ~~`A e. B <-> suc A C_ B` for ordinals. See comment below.~~ proved as ordelsuc in #636 

* `ord0eln0` seems like this should hold when non-empty is changed to inhabited but how to prove it? set.mm proof relies on trichotomy.

* `dflim4: use this as the definition`

* `limsuc: provable`

* `limsssuc: provable`

* `limuni: provable if you assume A is inhabited`

**Comment by digama0** [comment]
Here's some work at the non-provability assertions. Consider `X = { x e. 1o | ph }`. This is an ordinal which is `1o` if `ph` is true and `(/)` if it is false. Various properties of `X` reduce to deciding `ph` as a result.

* Trichotomy `A e. B \/ A = B \/ B e. A` is not provable: compare `X` with `(/)`. `X e. (/)` is impossible, `X = (/)` implies `-. ph`, and `(/) e. X` implies `ph`.

* Weak trichotomy `A C_ B \/ B C_ A` is not provable: If `suc A C_ suc B \/ suc B C_ suc A`, then `A e. suc B` (so `A e. B \/ A = B`) or `B e. suc A` (so `B e. A \/ A = B`).

* `A =/= (/) -> |^| A e. A` doesn't hold: take `A = { B , C }` and then it says `B i^i C = B` (so `B C_ C`) or `B i^i C = C` (so `C C_ B`).

* `A =/= (/) -> (/) e. A` is not provable, even with inhabited: `suc X` is inhabited since `X e. suc X`, but if `(/) e. suc X` then `X = (/)` so `-. ph`, or `(/) e. X` so `ph`.

* This means `C e. On /\ C C_ B /\ B e. A -> C e. A` also doesn't hold, which I was assuming in some of my earlier arguments.

**Comment by jkingdon** [comment]
@digama0 I'm trying to formalize the proof of ordunisuc2 which was sketched out as:

> If A = U. A and x e. A, then x e. y for some y e. A, so suc x C_ y e. A and hence suc x e. A. Conversely, U. A C_ A holds unconditionally, and if x e. A then x e. suc x e. A so x e. U. A.

I have it done except for the step `so suc x C_ y e. A and hence suc x e. A`. I don't see either how to get `suc x C_ y` nor how that would imply `suc x e. A`.

Glad to share more about my proof in progress if that would help.

**Comment by jkingdon** [comment]
@digama0 I'm trying to formalize (at least one of) the proofs of non-provability at https://github.com/metamath/set.mm/issues/629#issuecomment-436954329 and I'm stuck at trying to prove that `{ x e. 1o | ph }` is an ordinal. `trssord` would suffice if we can prove `{ x e. 1o | ph }` is transitive. Do you know have a proof that `{ x e. 1o | ph }` is an ordinal.

**Comment by digama0** [comment]
Isn't it obviously transitive? If `x e. X` then `x = (/)` so `x C_ X`.

**Comment by digama0** [comment]
For ordunisuc2, you can show `A e. B <-> suc A C_ B` for ordinals: the reverse is easy, and if `A e. B` then `A C_ B` because `B` is transitive. Thus we have `suc x C_ y` in that argument, but the proof falls down at deducing `suc x e. A`. I didn't look carefully enough at `C C_ B /\ B e. A -> C e. A` and it has a counterexample now, so maybe we should try to disprove this one as well.

**Comment by jkingdon** [comment]
> Isn't it obviously transitive? If `x e. X` then `x = (/)` so `x C_ X`.

Thanks, that works (what is obvious to you may or may not be to me :-)). I have this part formalized and I'm closing in on formalizing the rest of the proof that trichotomy implies excluded middle.

**Comment by jkingdon** [comment]
> For ordunisuc2, you can show `A e. B <-> suc A C_ B` for ordinals: the reverse is easy, and if `A e. B` then `A C_ B` because `B` is transitive.

The easy (reverse) direction we already had, as sucssel . The forward direction is called ordsucss in set.mm and the biconditional is called ordelsuc in set.mm. The proof sketched above proves the latter two and I formalized it as part of #636 .

> . . . maybe we should try to disprove [ordunisuc2] as well.

Could be. Whether it can be proved has implications for dflim4 . For now, I've formalized the proof of the reverse direction, also as part of #636 .

**Comment by digama0** [comment]
ordunisuc2 can't be proved. Let `om'` be the set of all finite iterations of `suc' A = ( ~P A i^i On )` on `(/)`. (We can formalize this proof but not until we have `om` and at least finite induction.) Then `om = U. om` because if `x e. om'` then `x = suc'^n (/)` for some `n`, and then `x C_ suc'^n (/)` implies `x e. suc'^(n+1) (/) e. om'` so `x e. U. om'`.

Now supposing the theorem, we know that `A. x e. om' suc x e. om'`, so in particular `2o e. om'`, that is, `2o = suc'^n (/)` for some `n`. (Note that `1o = suc' (/)`.) For `n = 0` and `n = 1` this is clearly false, and for `n = m+3` we have `1o e. suc' suc' (/)` , so `2o C_ suc' suc' (/)`, so `2o e. suc' suc' suc' (/) C_ suc' suc' suc' suc'^m (/) = 2o`, contradicting ordirr.

Thus `2o = suc' suc' (/) = suc' 1o`. Applying this to `X` we have `X C_ 1o` implies `X e. suc' 1o = 2o` and hence `X = (/) \/ X = 1o`, and LEM follows.
