### ISSUE TITLE
How handle CSS in .raw.html?

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/set.mm#696]
Do we want to use the new "/CSS" option when generating files from .raw.html? If so, what CSS should be removed?  What should be kept?  Should we modify set.mm so that more goes into the CSS there?

@nmegill - do you have a strong feeling about any of this?

**Comment by nmegill** [comment]
It might be best to always use /CSS.

A typical HTML page may have some custom CSS, that could look like this:
```
<STYLE TYPE="text/css">
<!--
.p { font-family: "Arial Narrow";
     font-size: x-small;
     color: #FA8072;
   }
.r { font-family: "Arial Narrow";
     font-size: x-small;
   }
.i { font-family: "Arial Narrow";
     font-size: x-small;
     color: gray;
   }
/* Math symbol images are shifted down 4 pixels to align with
   normal text.  All other images must override this shift with
   STYLE="margin-bottom:0px" */
img { margin-bottom: -4px }
-->
</STYLE>
```

You can tell because it differs from the CSS specified by "htmlcss" in the $t of set.mm.  It should _not_ be removed.

The CSS automatically generated by /CSS comes from "htmlcss" and is exactly the following in the current set.mm:

```
<STYLE TYPE="text/css">
<!--
  .set { color: red; }
  .wff { color: blue; }
  .class { color: #C3C; }
  .symvar { border-bottom:1px dotted;color:#C3C}
  .typecode { color: gray }
  .hidden { color: gray }
  @font-face {
    font-family: XITSMath-Regular;
    src: url(xits-math.woff);
  }
  .math { font-family: XITSMath-Regular }
-->
</STYLE>
<LINK href="mmset.css" title="mmset"
    rel="stylesheet" type="text/css">
<LINK href="mmsetalt.css" title="mmsetalt"
    rel="alternate stylesheet" type="text/css">
```

If it is already present (because it was inserted by hand sometime in the past), then take it out and let /CSS put it in.

If it isn't already present (because the page originally used GIFs), you will need it for the Unicode version.  But I see no harm in using /CSS all the time even for the GIF version - that will give us flexibility to use a mixture of GIF and Unicode in some cases e.g. if no GIF is available for the symbol. 

So maybe we should use /CSS all the time. 
 
The $t htmlcss can vary from one .mm to another, and also might be tweeked over time in a given .mm.  The original purpose of htmlcss was to avoid hard coding this in the theorem page generation code, in order to provide the flexibility to customize it for any .mm file.

Norm

**Comment by david-a-wheeler** [comment]
I think this has been resolved, so I'm closing this.
