### ISSUE TITLE
Rename some numbered axioms in set.mm / iset.mm

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/set.mm#703]
I think we should rename some of the numbered axioms. "ax-6" doesn't really hint at what it is, and the axioms aren't presented in that order in mmset.raw.html. The risk of renaming is that we miss some link... but once we use /label on .raw.html we can catch many problems automatically. See https://github.com/metamath/set.mm/issues/698 which would do that.

Norm made a renaming proposal in 2017:
https://groups.google.com/d/msg/metamath/G1xyJb6RjfI/JSNXPIkVAwAJ

He still agrees with it.

**Comment by david-a-wheeler** [comment]
Norm, I realize that you thought long and hard about numbers vs names. I still think very short names would be better, because they would at least give a hint to what the intent is. Even two letters are a better mnemonic than a number.

**Comment by nmegill** [comment]
> Norm, I realize that you thought long and hard about numbers vs names. I still think very short names would be better, because they would at least give a hint to what the intent is. Even two letters are a better mnemonic than a number.

@david-a-wheeler I am unlikely to change my mind on this.  Textbooks describing Hilbert-style systems almost always number the axioms of logic (I can't think of any that doesn't).  Tarski's paper on his system S2 uses axiom numbers.  So we are conforming to the literature, which is a strong argument.  I prefer to see the axiom list in mmset.html displayed as one would find in a book or paper, giving it a more serious and professional appearance instead of looking like computer code.  Unlike mnemonics, a fixed sequential axiom numbering (without gaps) conveys a feeling of permanence and authority that can be depended on, which is important at the foundational level (at least in my opinion).

Moreover, with my proposed renumbering, if in text prose we write:

  "...Tarksi's axioms (ax-4 through ax-9)..."

this tells us there are 6 axioms, and we know exactly what their names are:  ax-4, ax-5, ax-6, ax-7, ax-8, and ax-9.  It doesn't matter where or in what order they appear in set.mm.


If we write:

  "...Tarski's axioms (ax-qi through ax-re)..."

we have no idea how many axioms there are nor what the missing axioms are named.  If the order of ax-qi and ax-di are swapped in the database (for various technical reasons), then this description would become wrong.


If we write:

  "...Tarski's axioms (ax-qi, ax-di, ax-ex, ax-eq, ax-le, and ax-re)..."

in addition to being verbose, it's hard to remember and ugly to read.


If I see "ax-8" mentioned somewhere, I'll immediately know that it is a Tarski axiom.  If I see "ax-le", I won't know until I've memorized the mnemonics.

As a practical matter, it is relatively uncommon that we reference most axioms directly, which means their names don't really matter for most users (and when they do, we provide an alternate name like hbn1 for the current ax-6).

*I will offer you the following compromise,* if it is important to you:  you can restate the axioms as theorems (with 1-step proofs) with whatever names you want, like we do for theorem hbn1 as an alternate name for ax-6.  You can prefix them with "ax" if you want (but not "ax-", which would be confusing; "ax_" might be ok).  You can even reference your alternate-name theorems in place of the direct axioms throughout set.mm if you want, putting to rest any concern that the users may be confused by axiom numbers.  Then if I get hit by a bus, you will be all set to switch the official axioms to your chosen names immediately. :)  But until then I want to be able to say "Tarksi's axioms (ax-4 through ax-9)".

**Comment by jkingdon** [comment]
Good point about bundling and "metalogical completeness" - unless/until this gets a lot more attention, we don't really know where iset.mm stands on any of it (my guess would be "noticeably different from set.mm" but that's speculation as much as anything else).

And Norm's statement about "isn't any urgency" is oddly calming. Oddly in the sense that the perfectionist in me wants to rush in and make everything right. But calming in the sense that, well, it'll happen if/when it happens and I also want other things like constructive real numbers and whatever other things would take my iset.mm time.

**Comment by david-a-wheeler** [comment]
@nmegill - Once you're done renaming the set.mm axioms (including maybe swapping 12/13), I hope you'll update the metamath book to match.  Newcomers will find things a lot easier to follow if the book and actual set.mm file match :-).

**Comment by david-a-wheeler** [comment]
Nit: mmset.raw.html has the following text that I think should be deleted: "The above axioms evolved over time as redundancies and simplifications were discovered. As a result, the axiom numbering isn't sequential. We may rename them in the future."

**Comment by nmegill** [comment]
> Nit: mmset.raw.html has the following text that I think should be deleted: "The above axioms evolved over time as redundancies and simplifications were discovered. As a result, the axiom numbering isn't sequential. We may rename them in the future."

It has already been removed on us2. although not on github yet.

**Comment by david-a-wheeler** [comment]
I believe this has been completely resolved in set.mm (and with the matching book), and there's already agreement to let iset.mm grow in whatever form it naturally takes.

So I'm closing this as resolved.  If that's in error, please reopen!

**Comment by jkingdon** [comment]
> I believe this has been completely resolved in set.mm (and with the matching book), and there's already agreement to let iset.mm grow in whatever form it naturally takes.
> 
> So I'm closing this as resolved. If that's in error, please reopen!

I've moved the iset.mm question to #756 . There seems to be some level of agreement as to what might make sense, but on the other hand maybe doing nothing (for now at least) is also an option.
