### ISSUE TITLE
Document iset.mm divergence from set.mm

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#726]
It would be good to document theorems in set.mm which don't exist in iset.mm. Especially those which will never exist.

Something like:

set.mm | closest iset.mm equivalents | comments
---------- | ---------- | --------------
19.35 | 19.35-1 | the converse of 19.35-1 does not hold intuitionistically
relimasn | imasng | 
fvex | funfvex, 1stexg, 2ndexg |
opex | opexg, sopex |

Any suggestions on the format of this documentation and where to put it? @david-a-wheeler ? Anyone else? Should it be a long alphabetical list or organized by section or topic? Is there a way to have it more in the body of the theorems (maybe places like http://us2.metamath.org/ileuni/moexexdc.html ) and if so is that good or bad? I think I can supply a lot of the content if we decide this is useful and what it should look like.

Perhaps the "where do we put this?" part is also related to the similar question asked in #594 .

**Comment by david-a-wheeler** [comment]
> Any suggestions on the format of this documentation and where to put it?

It's probably most important to collect it at all.  Once it's collected, it can be moved.

Historically it would really *have* to be in iset.mm, because formula generation was hard.  Now that we can generate .html, you could also put it in an .html file like mmiset.html.

> Should it be a long alphabetical list or organized by section or topic?

I think it should be organized by section or topic, and then use HTML's "id" (or "name") to create hyperlink anchors (to make it easy for people to jump to a specific name).  It would be a lot easier to follow by section, and in many cases I think the same answer would apply to many things in the same section.

**Comment by jkingdon** [comment]
> It's probably most important to collect it at all. Once it's collected, it can be moved.

Makes sense. That's part of why i just got it started (in #742 ) rather than agonizing further about details (which can be changed later as desired).

> I think it should be organized by section or topic

Yeah, that sounds about right. We could probably just implement it as "list them in the same order they are listed in iset.mm", although I'm not necessarily opposed to some other kind of topical order.
