### ISSUE TITLE
Change typecode "set" to "setvar"?

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/set.mm#759]
I vaguely remember there was some discussion about renaming the "set" typecode into "setvar".  The "set" typecode, of course, doesn't really represent just any set - it only represents set variables, and that is potentially confusing.

I mention this now because I'd like for something like that change to be either accepted or rejected before the "final" version of the book for 2019 (so people can bring printed versions to the beach or mountains in the summer).

Has that been decided one way or another?  I'd just it resolved.

Sorry if this discussion was elsewhere, I couldn't find it.

**Comment by jkingdon** [comment]
Pretty sure this has been discussed multiple times and I'm not sure there is one canonical summary, but https://groups.google.com/d/msg/metamath/VKKsx60aq_E/TKWHo9XzAAAJ was the best wrap-up I could find in a small amount of searching. To me, `setvar` makes sense and there seems to be a fairly high degree of consensus that `set` is confusing (which of course does not automatically mean that we should change it, but if we can find a replacement which people don't hate, seems like there's a fair bit of sentiment in favor of it).

**Comment by digama0** [comment]
👍 ❤️

**Comment by nmegill** [comment]
The discussions you mention are here:

10/6/17 https://groups.google.com/d/msg/metamath/VKKsx60aq_E/7lsD_UEUBAAJ
10/11/17 https://groups.google.com/d/msg/metamath/KJ-j7JRcmNE/wfz0OqCiBQAJ
1/29/18 https://groups.google.com/d/msg/metamath/Fvj4JUWqUjM/HCqCWnPsBQAJ

Those discussions didn't have a conclusion or agreement.  More discussion will be needed to resolve this, if there is anything to resolve, so now is not the time to change this in the book or in set.mm.

I still like "wff", "set", "class" as simple, clean, and easy to remember.  These names are meant as easily recognizable hints, not complete descriptions.

I think "setvar" is ugly.  If, as some have proposed, we change "set" to the generic "var", then "class" becomes a kind of odd thing with no "set" to contrast it against.  In that case, it might be better to dispense with "class" and replace it with the more generic word "term", so we would have "wff", "var", "term".  I don't know whether this increased abstractness will be better for a beginner.

**Comment by jkingdon** [comment]
I guess we close this issue then. Especially since the context is 'the "final" version of the book for 2019'.

I do agree that we shouldn't try to find something which is short enough to be a typecode yet long enough to be self-explanatory. There will be explanation required no matter what we do, and term vs variable and set vs class are subtle enough concepts that this sort of explanation will always be part of the learning curve for a lot of people (even those with mathematical background).

**Comment by david-a-wheeler** [comment]
I have a preference for `setvar` but it's not a big deal.  My point was that if it *was* going to change, then it needs to change soon so we can make everything match.

Sounds like we're not going to change, so I'll close this!

**Comment by nmegill** [comment]
I think I'd be willing to consider wff, var, term.  Something to think about.

**Comment by david-a-wheeler** [comment]
Hmm. One advantage of that is that the syntax tokens and the underlying constructs have different names.

**Comment by david-a-wheeler** [comment]
I have reopened this so that people can keep commenting more easily.

**Comment by benjub** [comment]
For the record, my preference goes to wff / var / class.  I think that "setvar" does not add anything: what kind of variables could it be other than set variables, in the file set.mm implementing ZF set theory?  On the other hand, I would stick to "class" rather than "term", since one could think that, as in most first-order theories, variables vary over all terms (i.e., terms would be "set terms"), which is not the case.  In other words, the fact of having "class" rather than "term" would remind users of the peculiarity of set.mm in this regard.

**Comment by david-a-wheeler** [comment]
@benjub - the problem is that other constructs are also variables, so ` var ` could also be misleading.  For example, ` A ` is a class variable, and ` ph ` is a wff variable. Saying "setvar" hints that it is a specific kind of variable, and should reduce the risk of someone using the wrong typecode.

**Comment by benjub** [comment]
@david-a-wheeler I would rather say:
wff is for formula metavariables
var is for variable metavariables
class is for class metavariables
I think the viewpoint depends on one's background: logic or computer science.  No one point of view is better than the other, so the choice should depend on the population target of metamath/set.mm: logicians or computer scientists.
Of course, this is only my humble opinion; if there is an agreement on setvar, so be it!

**Comment by nmegill** [comment]
@david-a-wheeler I did this update, and it is causing mmj2 to fail the definition check.  Do you or @digama0 know which parameter sets this?

**Comment by david-a-wheeler** [comment]
On March 24, 2019 11:16:38 AM EDT, nmegill <notifications@github.com> wrote:
>@david-a-wheeler I did this update, and it is causing mmj2 to fail the
>definition check.  Do you or @digama0 know which parameter sets this?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/metamath/set.mm/issues/759#issuecomment-475968678

I don't know, though I'm not surprised. Mario should know.
--- David A.Wheeler

**Comment by digama0** [comment]
`definitionCheck.js` makes several explicit references to the `"set"` typecode. A find/replace of `"set"` with `"setvar"` should do the trick.

**Comment by david-a-wheeler** [comment]
On March 24, 2019 1:18:38 PM EDT, Mario Carneiro <notifications@github.com> wrote:
>`definitionCheck.js` makes several explicit references to the `"set"`
>typecode. A find/replace of `"set"` with `"setvar"` should do the
>trick.

That sounds good. It might be best to check if setvar is a constant, and if it is then use it, otherwise use set. That would make it easier to transition and occasionally use older versions of set.mm.


--- David A.Wheeler

**Comment by nmegill** [comment]
@david-a-wheeler I won't have time soon to fix definitionCheck.js esp. since I would have to go through a learning curve for compiling etc., which I've never done.

The following temporary patch to your script will work:  change /setvar/set/ in set.mm globally and unconditionally, just before running mmj2 (and then revert to the original set.mm if it is needed for something else).  This will allow the mmj2 def check to pass (I checked it locally) so that people can continue working until mmj2 is fixed. 

Could you apply this patch?

The Travis errors are in commit e562d9f  at https://travis-ci.org/metamath/set.mm/builds/510602801?utm_source=github_status&utm_medium=notification.  The missing "setvar.gif" there should now be updated on us.metmath.org.

BTW setvar is now on us2 in set.mm, mmset.html, mmzfcnd.html, and mmcomplex.html, if you have any comments on how I changed it.  We still need to update iset.mm and nf.mm - I don't think there is anything else.

Thanks,
Norm

**Comment by digama0** [comment]
On Sun, Mar 24, 2019 at 8:49 PM nmegill <notifications@github.com> wrote:

> @david-a-wheeler <https://github.com/david-a-wheeler> I won't have time
> soon to fix definitionCheck.js esp. since I would have to go through a
> learning curve for compiling etc., which I've never done.
>
You don't need to recompile, because it's in a script (for exactly this
reason). Just change the .js and reload mmj2.

**Comment by nmegill** [comment]
I looked at definitionCheck.js and am not familiar enough with its classes and methods to properly modify it, without spending more time studying it.  It also has to be packaged into mmj2.zip for distribution.  Unfortunately I need to get back on another project right now.

Unless someone else is able to modify it soon, I think we should put in the script workaround of temporarily modifying set.mm for mmj2, since it will hold up pull requests (it is holding up Benoit's right now).

**Comment by nmegill** [comment]
So that we can move forward, I put in a temporary workaround in .travis.yml to zap set.mm with s/setvar/set/ before the mmj2 call.  I thought it was easier than zapping and restoring definitionCheck.js.  If anyone wants to do it differently, that's fine.

**Comment by digama0** [comment]
Sorry about the delay. I've updated the mmj2 repository with this change, so the travis patch shouldn't be needed anymore.

**Comment by avekens** [comment]
Is there anything open about this issue? Can it be closed?

**Comment by david-a-wheeler** [comment]
All done. Closing.
