### ISSUE TITLE
Rename "Hilbert spaces" to "Generalized Hilbert space"

### ISSUE THREAD

**Issue by tirix** [metamath/set.mm#790]
It seems set.mm's definition of Hilbert space (Hil) does not match the common definition of Hilbert spaces, which are normally defined with only complex or real numbers as a scalar field, for which set.mm has a different definition (CHil).

In this post, Mario answers to a suggestion from Gérard Lang:

> > As "Hilbert space" is generally associated with a certain kind of topological vector spaces and we are there in a purely algebraic structure, maybe another description like "Generalized Hilbert space" or "Algebraic Hilbert space" could be useful as title for section 9.12
> 
> I didn't want to do it in the same update, but if no one objects I will be renaming df-phl to df-ips (IPSp "inner product space"), df-hl to df-oms (OMSp "orthomodular space"), df-cph to df-phl (PreHil "pre-Hilbert space"), and df-hl (CHil) to Hil "Hilbert space". Thus only the concepts involving the complexes have the name "Hilbert", while the algebraic versions have more generic names.

**Comment by tirix** [comment]
...and Frédéric Liné asked for the same in [one of this posts](https://groups.google.com/d/msg/metamath/BWYHUtFIDCw/yR5h2eWEBwAJ), too.

> The definition Hil does not imply any kind of topological completeness, it is only an "algebraic" kind of completeness. It's not totally clear to me what the application is, but Norm has done quite a bit of work with these spaces in the Hilbert space explorer and his mathbox, and I wanted to support that. But perhaps the name is misleading, since what wiki calls "hilbert space" is actually CHil not Hil.

**Comment by benjub** [comment]
I'm not sure what's wrong with the current definitions.  The only change I
would make is df-hl --> df-chl.
As for your first sentence, a Hilbert space need not be over the complex
numbers (although this is by far the most interesting case), but can be
over any field with an absolute value.  For instance, there is some work on
the non-Archimedean case (Monna has a nice booklet on this topic).

**Comment by nmegill** [comment]
The "Hilbert space explorer" is something of a failed experiment because it adds new axioms on top of ZFC rather than using extensible structure builders (which didn't exist then).  I plan to remove it from set.mm eventually.    At this point it doesn't merit being a major feature of MPE compared to much more important things added since then.  I've been keeping there partly because its proofs have served as guides for the structure builder proofs and partly because "Hilbert Space Explorer Home Page" is somewhat intertwined with MPE and I need time to dedicate to separating them.

**Comment by tirix** [comment]
Benoit, if I'm not mistaken, with the current Metamath definition of a Hilbert space, we don't have a norm, and therefore a Hilbert space is not a Banach space. Does that fit with your view?
Shall we e.g. use "algebraic" Hilbert space for the current definition?

Here is [Wikipedia's definition of a Hilbert space](https://en.wikipedia.org/wiki/Hilbert_space#Definition):

> A Hilbert space H is a real or complex inner product space that is also a complete metric space with respect to the distance function induced by the inner product.

**Comment by nmegill** [comment]
I'm getting confused about which definitions we are talking about:  df-hl, df-hil, or the definition implied by the HSE axioms for ~H.

If you mean df-hil, the condition dom ( proj \' h ) = ( CSubSp \` h ) is equivalent to the Wikipedia definition.

**Comment by benjub** [comment]
Maybe I did not look carefully enough at the metamath definitions.  My point is that it is not necessary to restrict to complex scalars to define (pre)Hilbert spaces.  A *-field with absolute value should be enough, and I thought that it's what metamath is currently doing.

**Comment by tirix** [comment]
Sorry if I'm confusing you, let me try to be clearer:

- What I understand is that in set.mm, Hil (~ df-hil), is a pure _algebraic_ concept. 
- On the other hand, I think Gérard and Frédéric complain that they don't see any _topological_ component in Hil (~ df-hil). 

The wikipedia page for example defines a Hilbert space as a _complete_ space, and by definition a Banach space, so it gives necessary _topological_ properties.
In the comment for ~ df-obs, Mario writes: 

> As this is an "algebraic" definition, **before we have topology available**, we express this denseness by saying that the double orthocomplement is the whole space, or equivalently, the single orthocomplement is trivial.

Is that just because this development is missing in set.mm, or because the definition of Hil (df-hil) does not include a topological "component"?

**Comment by tirix** [comment]
Actually I was getting interested in Hilbert spaces because of a suggestion from Gérard to prove that Hilbert spaces fulfil the axioms of Tarski for geometry. 
Unfortunately, the definition of "congruence" suggested by Mario for Tarski's axioms relies on the space's metric, which, in current definition, generalised Hilbert spaces lack.

In set.mm, the function ` toNrmGrp ` ([df-tng](http://us2.metamath.org:88/mpeuni/df-tng.html)) equips any space with a norm and builds a metric, but because it uses the complex "sqr" function, it only works over the complex numbers. I guess I have to decide whether it's worth the effort to makes this more general - this would involve defining a generic square root function for generic rings (which does not always exist (see ℤ/8ℤ). Your advice would be welcome.

**Comment by digama0** [comment]
In my suggestion for using the dist slot for congruence, the target type doesn't have to be the real numbers (meaning that it's not really a metric space). This gives you the flexibility you need for Tarski's axioms, and potentially you can make this work with Norm's more general orthomodular spaces that don't have anything to do with complex numbers.

You may need to wrap df-hil spaces with a function like `toNrmGrp` but with a generalized distance function in order to achieve this. Looking at the definition of `toNrmGrp`, it looks like it is actually usable for your purpose, since it only takes a norm function and constructs a distance function by subtraction, which is fine, without checking the codomain of the input norm. So you can pass it the function `( x e. B |-> ( x ., x ) )`, and while you won't get a metric, you will get a congruence suitable for Tarski (which is invariant under any injective functions applied to the norm, like `sqr`).

**Comment by tirix** [comment]
Thank you Mario. What about Betweenness then?
In order to build a Tarski geometry from a Hilbert space, I wanted to define betweenness as
‘ B Btwn AC <-> |AB|+|BC|=|AC| ‘
(Where |AB| would have used the metric)
I think that instead, I will have to use something like
‘ B Btwn AC <-> E. k e. Scalar ( (B-A) = ( k .x. (C-A) ) /\ .0. <_ k <_ .1. ) ‘
Requiring the scalar field to be an ordered field. What would be your advice?

**Comment by digama0** [comment]
One of the problems with df-hil Hilbert spaces is that there is no ordering on the (*-fixed points of the) scalar field, and pre-Hilbert spaces lack an axiom saying that 0 <= (x, x) because this doesn't even make sense. So you can't talk about the line segment between two points unless you have that ordering, and I'm pretty sure there are even proper counterexamples of things like the Fano plane where there really is no good sense of an order. So perhaps Gerard's suggestion doesn't work as is.

If we are resolved to add an order, then the minimal imposition is to have an order on the *-fixed points of the scalar ring. (The advantage of this over ordering the ring itself is that now CC is also suitably ordered.) Alternatively, you can avoid adding structure by defining nonnegative using existence of square roots, which is roughly what I do for complex Hilbert spaces.

**Comment by tirix** [comment]
The main reason why I opened this issue was my lack of understanding of the Hilbert spaces.

The definition I chose for the function mapping a Tarskian geometry to a Hilbert space is defined in [~ df-ttg](http://us2.metamath.org:88/mpeuni/df-ttg.html), and it is limited to spaces on the real numbers, so I also chose a direction regarding the underlying problem.

I think I can close this issue.
