### ISSUE TITLE
About CONTRIBUTING.md

### ISSUE THREAD

**Issue by benjub** [metamath/set.mm#813]
I understood that from now on, for smaller contributions, one should not change the date on top of set.mm, and the option top_date_skip has been added to "verify markup" to ignore this issue.  Accordingly, the "procedure recommended prior to submitting a pull request" in CONTRIBUTING.md should be changed to incorporate the "top_date_skip" option, shouldn't it?

Also, is it necessary the "read" then "erase" then "read" again?  In other words, is it ok to do the following:

./metamath
MM> read set.mm
MM> save proof */compressed/fast
MM> verify markup */file_skip/top_date_skip
MM> verify proof *
MM> write source set.mm/rewrap
MM> quit

The single bash command should also be updated.  If the above procedure is ok, I can update both myself.

**Comment by nmegill** [comment]
Yes, we should start using the new '/top_date_skip' instead of '/date_skip' so that at least the dates in the set.mm body can be checked for consistency.

However, 'save proof */compressed/fast' needs to be done after 'write source set.mm/rewrap' because the latter may shift indentations (if they weren't indented per our convention) and thus may affect the indentation of the proofs.

Please go ahead and modify CONTRIBUTING.md with the above in mind.

For the longer term (on my to-do list) I plan to have a separate rewrap command that is independent of 'write source'.  The reason it was originally done with a 'write source' qualifier was because the original internal structure had no way to store modified source (other than the proof), so the wrapped source could be modified only when it was written out.  Last year I put in the necessary hooks so that any part of the source can now be modified, so it is a matter of coding the 'rewrap' command to use that when I get some free time.
