### ISSUE TITLE
Define iset.mm recursive definition generator

### ISSUE THREAD

**Issue by jkingdon** [metamath/set.mm#847]
Now that iset.mm has http://us2.metamath.org/ileuni/tfri1.html , http://us2.metamath.org/ileuni/tfri2.html , and http://us2.metamath.org/ileuni/tfri3.html , the next step is the recursive definition generator which makes it easier to define recursive functions given an initial value and characteristic function (that is, function for giving the value at a successor).

The current generator in set.mm, http://us2.metamath.org/mpeuni/df-rdg.html , is based on case elimination, in particular between the limit ordinal and successor ordinal cases. The initial value could presumably be handled with `( <. (/) , I >. u. something )` where `something` is what we end up using for successor/limit.

So the basic question is: is there a practical way to come up with an expression which combines limit and successor? It would presumably be something along the lines of "apply the characteristic function for all ordinals less than the current one, then take the union of all the results".

Another path would be to go down the path of trying to define finite recursion next, as it would only need a successor case not a limit case. Presumably this would be via a new notation such as `frec(𝐹, 𝐴)` rather than using `(rec(𝐹, 𝐴) ↾ 𝜔)` as in set.mm finite recursion theorems such as http://us2.metamath.org/mpeuni/frsuc.html . And if this is the chosen path, is there a way to avoid re-proving http://us2.metamath.org/ileuni/tfri1.html and the like for `𝜔` (or maybe for arbitrary ordinals) in place of `On`?

By way of motivation, the key thing we want out of this is positive integer addition - http://us2.metamath.org/mpeuni/df-pli.html - which is part of the construction of real numbers.

**Comment by digama0** [comment]
For increasing and continuous ordinal functions, it's not so hard; it's like you said - define `G(x) = sup y<x F(G(y))`. That should be enough for most of the applications in set.mm, although there is a caveat for ordinal exponentiation, which is not increasing when the base is 0 and is handled by a case analysis. If you skip the case analysis, then you get 0^alpha = 1 for all alpha. Maybe this is fine, although you can still basically recover the traditional function using `a^b = { y | ( E. x x e. a \/ a = (/) ) /\ y e. a ^' b }` where `a ^' b` is the inductive definition.

For finite recursion, you don't want to assume the function is increasing. In this case, something like `G(n) = { x | E. m ( n = suc m /\ x e. F(G(m)) ) \/ ( n = 0 /\ x e. I ) }` is desirable. This is a strong disjunction, but we will be primarily interested in omega here and so we want the elements to be nicely separated. You can actually also throw in the limit case so that you get basically the definition rec(F, A); I'm not sure if this works completely but at least it looks like set.mm and degrades correctly to the finite case.

**Comment by digama0** [comment]
By the way, I don't see df-if in iset.mm. I suggest you bring over the definition from set.mm basically verbatim, and use it to define df-rdg (as the disjunctive recursive definition generator). Just because case analysis doesn't work quite the same way in iset.mm doesn't mean this isn't a useful definition anyway. In particular the if theorems all continue to hold provided the proposition is decidable, and there are some new things you can say, like if `if ( ph , A , B )` is inhabited then `ph` is decidable. Also `if ( ph , A , B ) C_ ( A u. B )` without assuming decidability, so `if` is a set if `A` and `B` are.

**Comment by jkingdon** [comment]
I'm going to take a stab at the "increasing and continuous ordinal functions" solution as described above.

The other parts all seem to be about defining finite recursion without the "increasing and continuous ordinal functions" condition. That would include the musings about `if` since (more or less) the only place we can prove decidable equality is in the finite case (or so is my attempt to summarize the Remark in section 2 of https://ncatlab.org/nlab/show/decidable+equality - that page is rather more careful about how they state things). I don't really object to any of that, but if I can get the increasing and continuous ordinal function method working, it looks like it might be less work.

**Comment by jkingdon** [comment]
So here's where I am so far. I am working with the following definition:

```
df-irdg $a |- rec ( F , I ) = recs ( ( g e. _V |-> ( I u.
  U_ x e. dom g ( F ` ( g ` x ) ) ) ) ) $.
```

From that rdgfun is straightforward, and for rdgfnon I assume we'll need two new hypotheses: `I e. On` and `F Fn On`. But even with that the question is how we know that `g` produces an ordinal. I guess it is going to be some flavor of set induction (with base case of `I` and with the indexed union making the inductive step work). Does that all sound right? Any hints about how that induction would be structured (if that is the right approach, that is)? I'm not sure I quite see how to put that all in symbols (beyond a few pieces like funmpt and dmmpt).

**Comment by digama0** [comment]
I think you should reconsider proving `fvex`. It's possible to prove everything is in domain here, but it really does simplify a lot of things to have unconditional closure. What can be proven is that if A F x implies `x C_ B`, then ``( F ` A ) C_ B`` as well. That means in particular that ``( F ` A ) C_ ran F``, and so ``( F ` A ) e. _V`` if `F e. _V`. (Using the axiom of replacement you can also prove this given `dom F e. _V`.) The reason this is helpful in this case is because if `F` is a function on `_V`, then ``( F ` ( g ` x ) )`` is defined because `g` is a set so ``( g ` x )`` exists.

**Comment by jkingdon** [comment]
So I'm trying to show ``( F ` ( g ` x ) )`` exists, based on the previous comment. How do we know that `g` is a function (or in the case of relrnfvex, a relation)?

**Comment by digama0** [comment]
There's another fvex theorem that I didn't prove, the most obvious one:

    fvexg $p |- ( ( F e. V /\ A e. W ) -> ( F ` A ) e. _V )
    fvex $e |- F e. _V $e |- A e. _V $p |- ( F ` A ) e. _V

**Comment by jkingdon** [comment]
So I'm beginning to wonder if the "increasing and continuous" approach is a dead end in light of http://us2.metamath.org/ileuni/onsucelsucexmid.html and http://us2.metamath.org/ileuni/onsucsssucexmid.html . Now, I'm not completely sure it is required for `suc` to be increasing in the sense of those theorems but they do match the usual meaning of "increasing" and they did come up in some of my attempts to prove theorems like `oasuc`. I spent less time investigating whether defining ordinal addition in terms of `(𝒫 A ∩ On)` in place of `suc` would work any better.

Whether or not that can be saved, my eye has turned to finite recursion. Based on the discussion above, I'm thinking of adding
```
    df-frec $a |- frec ( F , I ) = recs ( ( g e. _V |-> { x |
      ( E. m ( dom g = suc m /\ x e. ( F ` ( g ` x ) ) ) \/
      ( dom g = (/) /\ x e. I ) ) } ) ) $.
```
and then trying to define theorems like fr0g and frsuc (as modified to use frec instead of rec restricted to omega).

**Comment by digama0** [comment]
This is interesting. From rdgival, you can prove that

    ( A +o B ) = ( A u. U_ x e. B suc ( A +o x ) )

So at the very least, we do get that `A +o 1o = A u. suc A = suc A`. More generally, for `oasuc`, we get that

    A +o suc B = A u. U_ x e. B suc ( A +o x ) u. suc ( A +o B )
               = ( A +o B ) u. suc ( A +o B )
               = suc ( A +o B )

so I think it works out. I don't know if you've defined a limit ordinal but I think that also works; you just have to prove that a limit ordinal is inhabited to remove the `A u.` part of the definition.

As for finite recursion, I would suggest that you keep the restriction to omega. (I think there is a typo in your definition, you probably want ``( g ` m )`` instead of ``( g ` x )``.) That definition has garbage behavior past omega, since it is `(/)` at omega, ``( F ` (/) )`` at omega+1, and so on, which is ignoring the initial value `I` so it probably makes no sense. However with that definition you should be able to prove the successor theorem

    ( A e. On -> ( frec ( F , I ) ` suc A ) = ( F ` ( frec ( F , I ) ` A ) ) )

without additional assumptions on the ordinal.

**Comment by jkingdon** [comment]
As for finite recursion, agreed about the restriction to omega making sense. I've put that back (and fixed the ` ( g `` m ) ` typo) at #1049 .

Next I'll look into the `oasuc` material above (no reactions on that yet).

**Comment by jkingdon** [comment]
For `oasuc`, the proof sketched above works and is formalized at #1051 . Good work.

Regarding limit ordinals, we do have http://us2.metamath.org/ileuni/df-ilim.html and a few of the limit ordinal theorems but we haven't really used them much. Not sure I follow the relevance to `oasuc` but maybe since the above proof works it isn't important?

I think the next steps are relatively obvious on both the `rec` and `frec` fronts but I'll post if I have further questions.

**Comment by digama0** [comment]
I meant that `oalim` should be provable, and indeed the proof should not differ much from the original proof. In fact, most theorems about limit ordinals should carry over - stuff I would like to see include that a limit contains successors of its elements, omega is the intersection of all limit ordinals, a successor is not a limit, `A +o B` is a limit iff `B` is. Because being a limit is a positive statement I expect no major issues with the set.mm theorems.

It is probably a task for later but I would also be interested to see how much of cofinality carries over, which is a big topic in set theory and leads to regular and inaccessible cardinals.

**Comment by jkingdon** [comment]
Cool, I've moved the limit ordinal stuff to https://github.com/metamath/set.mm/issues/1052 . Should be easier to manage if it has its own issue (since this one is already large in scope, what with both transfinite and finite recursion).

For me, the number one focus remains construction of the reals. But if I get inspired by limit ordinals (or someone else does), it appears there is some low hanging fruit there.

**Comment by jkingdon** [comment]
I'm willing to declare this issue done based on having oasuc , omsuc , and all the good stuff at #1070 (and other recent pull requests like #1069 which aren't directly about `rec` or `frec` but which do show that what we have seems to be sufficient to define natural number addition and multiplication).

We can always open new issues if there are additional topics.
