### ISSUE TITLE
Discourage use of ax-4: use alim instead

### ISSUE THREAD

**Issue by benjub** [metamath/set.mm#856]
Following the recent renumbering of axioms, ax-4 and alim are now the same statement, and both are used by later theorems.  Since alim should be kept for labelling consistency, I propose to make alim the only theorem directly referencing ax-4, and discourage use of ax-4 in favor of alim.  I'll do it when I have Norm's green light.

**Comment by nmegill** [comment]
I agree.  You can go ahead and do this.  BTW the reason alim exists was because ax-4 wasn't originally an axiom.

The date of 5-Aug-1993 on ax-4 and ax-10 is wrong, because these 2 axioms were added later.    I researched this, and the correct date for both ax-4 and ax-10 should be 21-May-2008.  You may as well fix the date for these at the same time.

(Originally axioms and definitions had no dates.  My one-off script to insert them was based on the date of the earliest theorem referencing them.  This worked most of the time but wasn't perfect.)

**Comment by benjub** [comment]
Proposed in PR #859
