### ISSUE TITLE
Ring of integers

### ISSUE THREAD

**Issue by avekens** [metamath/set.mm#866]
I need the ring of integers ` ( CCfld |`s ZZ ) ` as (counter) examples for some theorems in linear algebra. There is already some material in different places (esp. mathboxes):

- First appearance in section "10.11 The complex numbers as an algebraic extensible structure"
- Section "The ordered commutative ring of integers" in TA's mathbox contains basic properties.

I would like to move section "The ordered commutative ring of integers" in TA's mathbox into the main part, maybe as section "10.8.6 Ring of integers" after "10.8.5  Left regular elements. More kinds of rings" (since ` ( CCfld |`s ZZ ) e. LPIR `, see ~ zlpir), and to add more theorems I have not commited yet.

Any objections?

**Comment by nmegill** [comment]
I have no objections.

**Comment by tirix** [comment]
No objections here either!

**Comment by avekens** [comment]
With PR #872/#876 I moved the section "The ordered commutative ring of integers" in TA's mathbox into the main part, as section "10.11.2  Ring of integers" (in contrast to the expected/planned section 10.8.6) , because CCfld is defined in section 10.11.1 only. 

With hindsight  I think it would be practicable to give it an own definition, maybe 
df-rngz $a |- RingZ = ( CCfld |s ZZ ) 

Unfortunately, there is already a definition df-zrng $a |- ZRing = ... in Mario's Mathbox (subring of integral elements in a ring), so ZRing cannot be used for the "Ring of Integers" (or Mario's definition must be changed).

What do you think about this?

@benjub I added the word "unital" in the comment of the header of section "Ring of integers", as you propoed in #872. I put it in square brackets, however, because my text is a citation taken from Wikipedia.

**Comment by benjub** [comment]
@avekens As for the HTML symbol (and also in the tokens), I would use "Ring/ring" instead of "Rng/rng".  The reason is that the term "rng" has become quite popular for "non-necessarily unital rings" (they are "rings" that lost the "i" of "identity").  I don't know what @nmegill and @digama0 think of it.

**Comment by avekens** [comment]
@benjub Thank you for this hint - I didn't know that. But also in Wikipedia the differentiation is made, see [https://en.wikipedia.org/wiki/Rng_(algebra)](https://en.wikipedia.org/wiki/Rng_(algebra)). So my suggestion woud be the following: 

Definition: `df-zzring $a |- ZZRing = ( CCfld |``s ZZ )`
Symbol: &#8484;<SUB>ring</SUB> (`htmldef "ZZRing" as "&#8484;<SUB>ring</SUB>";` )

If nobody objects, I will put this definition into section "Ring of integers" and replace the 27 occurences of  `( CCfld |``s ZZ )` by `ZZRing`.

@nmegill @digama0 @david-a-wheeler @tirix  @sorear OK?

**Comment by benjub** [comment]
This sounds perfect. The sooner the better since I will have to use ZZRing soon.  (What you described is the "althtmldef", not the "htmldef", of course.)

**Comment by nmegill** [comment]
I'm fine with ZZRing.

@benjub Yes, that would be the althtmldef.  Since htmldef is slowly becoming obsolete as browsers' Unicode rendering has improved, we have often been making the two identical for new symbols when existing GIF images aren't available, rather than creating new GIF images.  E.g.

```
htmldef "|`s" as " &#8638;<SUB>s</SUB> ";
  althtmldef "|`s" as " &#8638;<SUB>s</SUB> ";
```

It might be tempting to mix GIFs and Unicode for htmldef, but the tooltips and copy/paste may produce unexpected results.  An advantage of pure GIF is that copy/paste results in the ASCII version used in set.mm, so expressions can be copied from the browser screen to insert in a proof under development.  Sometimes people have concatenated existing GIFs as in

```
htmldef "*r" as "<IMG SRC='ast.gif' WIDTH=7 HEIGHT=19 ALT=' *' TITLE='*'>" +
    "<IMG SRC='subr.gif' WIDTH=5 HEIGHT=19 ALT=' r' TITLE='r'>";
```

Here the tool tip displays only one symbol at a time but copy/paste should work.  [I see there is a minor error here:  ALT=' r' should be ALT='r' to prevent a space between "*" and "r" after copy/paste.   I will fix this.]

**Comment by benjub** [comment]
Regarding unicode/GIF:
I've been contemplating the idea that GIF could be completely dispensed with, and the two available versions be unicode and ascii.  I mean something like:
* for the html pages, you would have directories mpeuni/ and mpeascii/
* the metamath program would have the options (for "show statement" or "write theorem_list") /unicode and /ascii (instead of /html and /alt_html)
* in the .mm files, only unicode (currently "althtmldef") would be needed (together with latexdef).

What do you think ?

**Comment by tirix** [comment]
About the notation for the ring of integers: I see ` ZZRing ` has an uppercase R while ` CCfld ` has a lowercase f. If we could be consistent, it would be easier to remember the rules.

**Comment by nmegill** [comment]
> Regarding unicode/GIF:
> I've been contemplating the idea that GIF could be completely dispensed with, and the two available versions be unicode and ascii. 

I also have considered this off and on.  I would want feedback from the google group, over a period of a month or two, before making such a drastic change.  

> I mean something like:
> 
> * for the html pages, you would have directories mpeuni/ and mpeascii/
> * the metamath program would have the options (for "show statement" or "write theorem_list") /unicode and /ascii (instead of /html and /alt_html)

The initial approach I suggest would be just to specify "\<TT>...\</TT>" in the htmldefs.  That would let us test it without changing any code and would be easy to revert if people don't like it.

Note that unless we change the build script to always use the Unicode version, mmset.html and related pages would have ascii tokens rendered in the mpegif versions, since they come from the markup in mmset.raw.html etc.  But if we use the Unicode versions we would lose the ability to copy/paste the ascii tokens.  So would people accept ascii tokens on mmset.html etc.?

> * in the .mm files, only unicode (currently "althtmldef") would be needed (together with latexdef).

Unless we want to eliminate the colors, we will either need something like htmldef (maybe renamed to asciidef) to specify them (requiring few program changes), or we will need some other syntax that specifies lists of tokens with specific colors (bigger program changes to parse and error-check).

An important question is whether people will use this, and if so, for what purpose.  If it is only to be able to copy/paste the ascii, a small cleanup of the htmldefs (fixing any bad ALT tags and using GIFs for several now using Unicode) can make such copying faithful.

**Comment by avekens** [comment]
@tirix you are right, I'll change the symbol to ZZring in my next contribution.

**Comment by avekens** [comment]
Phase 2 is finished with my latest pull request.

Open issues:
- 16 (not discouraged) usages of ( CCfld |`s ZZ ) ( 3 definitions, 2 in mathboxes):
-- df-zrh $a |- ZRHom = ( r e. _V |-> U. ( ( CCfld |`s ZZ ) RingHom r ) ) $.
-- df-zlm $a ...  sSet <. ( Scalar ` ndx ) , ( CCfld |`s ZZ ) >. )
-- df-zn $a |- Z/nZ = ( n e. NN0 |-> [_ ( CCfld |`s ZZ ) / z ]_
-- mulgghm2.1 $e |- Z = ( CCfld |`s ZZ ) $.
-- zrhval.1 $e |- Z = ( CCfld |`s ZZ ) $.
--  zlmval.z $e |- Z = ( CCfld |`s ZZ ) $.
-- zlmsca.2 $e |- Z = ( CCfld |`s ZZ ) $.
--  znval.z $e |- Z = ( CCfld |`s ZZ ) $.
--  znval2.z $e |- Z = ( CCfld |`s ZZ ) $.
--  znbas.z $e |- Z = ( CCfld |`s ZZ ) $.
--  znzrh2.z $e |- Z = ( CCfld |`s ZZ ) $.
--  znf1o.z $e |- Z = ( CCfld |`s ZZ ) $.
--  zzngim $p |- L e. ( ( CCfld |`s ZZ ) GrpIso Y ) $=
--  znle2.z $e |- Z = ( CCfld |`s ZZ ) $.
--  zzsnm.1 $e |- Z = ( CCfld |`s ZZ ) $.
-- mzpmfp $p |- ( mzPoly ` I ) = ran ( I eval ( CCfld |`s ZZ ) ) $=
- Not used discouraged theorems:
-- New usage of "dfprm2OLD" is discouraged (0 uses).
-- New usage of "prmirredOLD" is discouraged (0 uses).
-- New usage of "prmirredlemOLD" is discouraged (2 uses).
--- is used by "dfprm2OLD" and "prmirredOLD" only!
-- New usage of "zlpir" is discouraged (0 uses).
-- New usage of "zrngmulg" is discouraged (0 uses).
-- New usage of "zcyg" is discouraged (0 uses).
- not discouraged theorems using discouraged theorems:
-- "dvdsrz" is used by "zndvds".
--"expghm" is used by "lgseisenlem4".
-- "zrng0" is used by "zrhf1ker".
-- "zrngbas" is used by "cnzh", "elzrhunit", "nmmulg", "qqhf", "qqhghm", "qqhnm", "qqhrhm", "qqhval2lem", "rezh", "zrhf1ker", "zrhunitpreima", "zrnginvg".
-- "zrngmulr" is used by "qqhghm", "qqhrhm", "qqhval2lem".
-- "zrngplusg" is used by "qqhghm", "qqhrhm".
-- "zrngunit" is used by "qqhval2lem".

**Comment by avekens** [comment]
How shall I proceed?

- Shall I replace ( CCfld |s ZZ ) vy ZZring in the remaining 16 (not discouraged) usages?  All of them, or should some of them be kept?
- Shall I delete the not used discouraged theorems? I would like to do this, unless there are no good arguments for keeping them.
- Shall I replace the  discouraged theorems used in not discouraged theorems by the new theorems, and delete the discouraged theorems afterwards?
- Shall I document anything of these changes in the history at the top of set.mm?

@nmegill what's your opinion?

**Comment by tirix** [comment]
@avekens I assume several of these are in my mathbox. No problem for me, you can do the change. 
Please just make sure to notice me so I take it over and don’t overwrite it with some local file!

**Comment by nmegill** [comment]
> How shall I proceed?
> 
> * Shall I replace ( CCfld |s ZZ ) vy ZZring in the remaining 16 (not discouraged) usages?  All of them, or should some of them be kept?

I don't see any reason not to do this.

> * Shall I delete the not used discouraged theorems? I would like to do this, unless there are no good arguments for keeping them.

Our practice has been to keep obsolete theorems (suffixed with OLD) for a year.  For that to happen, we add the comment "Obsolete as of dd-mm-yyyy. " or "Obsolete version of ~ xxx as of dd-mm-yyyy. ".  I periodically go through and manually look for "mm-yyyy. " (note space after period) at the end of mm-(yyyy+1) or later, and when "Obsolete" is also there, I will delete the theorem.  (There is no automation of this because it infrequent and doesn't take much time.)

A year should provide ample time for people to notice what was done and possibly revert if there is some reason to do so.

Theorems that are marked obsolete should not be used by anything and should be marked as discouraged.  If a theorem is obsolete but still has uses, they can still be marked obsolete if those uses will be removed within a year, otherwise maybe add a "TODO:..."

If you think a lot of *OLDs are distracting for editing, you can move them somewhere else like the end of the section.  I typically leave them in place under their replacements.

> * Shall I replace the  discouraged theorems used in not discouraged theorems by the new theorems, and delete the discouraged theorems afterwards?

I think we should keep the discouraged ones (suffixed with OLD and marked obsolete) for a year as I described.

> * Shall I document anything of these changes in the history at the top of set.mm?

We have been doing so except in extreme cases of some massive global change.  The entry in the "Notes" field can be "replaced ( CCfld |\`s ZZ ) by ZZring".

If the theorems are in mathboxes, it is optional to document them at top, but they can be if you wish.  In that case we often indicate the mathbox as in "replaced CCfld |\`s ZZ by ZZring (TA's mathbox)"

**Comment by nmegill** [comment]
dd-mm-yyyy should be dd-mmm-yyyy in my previous comment, to avoid the mm-dd/dd-mm American ambiguity. :)

**Comment by nmegill** [comment]
> If the theorems are in mathboxes, it is optional to document them at top, but they can be if you wish. In that case we often indicate the mathbox as in "replaced CCfld |`s ZZ by ZZring (TA's mathbox)"

I should mention that none of the *OLD/obsolete/discouraged stuff is necessary for anything in your own mathbox; just edit it directly if you want.  It's also optional in someone else's mathbox if they are aware of what you are doing and permission to make the changes is understood.

Essentially we assume the main set.mm is stable, with changes documented, whereas anything in a mathbox is volatile and subject to change.

**Comment by avekens** [comment]
Thank you for all the hints!
With PR #924, I almost finished the replavement of ( CCfld |`s ZZ ) by ZZring:

- Theorems/definions still using ( CCfld |`s ZZ ) duplicated (with suffix OLD) and marked as obsolete.
- all remaining occurences of ( CCfld |`s ZZ ) replaced by ZZring (except in obsolete theorems/definitions)
- many usages of obsolete theorems/definitions in proofs replaced by corresponding theorems/definitions using ZZring
-- remaining usages of "zlmvalOLD" (2), "zrhmulgOLD" (8) and "zrhrhmOLD" (25) will be replaced soon
-- also the other usages of obsolete theorems mentioned in my comment on 11-Jun-2019 will be replaced then

It was a lot of work, much more than I expected, and without the help of mmj2 (some mass editing functions like "select/delete all" or "find&replace" would have been very helpful!) it would have taken much more time. Especially the estimated 16 replacements (mentioned in my comment on 11-Jun-2019) became 33 replacements (because the hypotheses where used for several theorems within a block). And there were about 100 proofs to be updated.

@tirix : Theorems ~ zzsnm ( ( CCfld |`s ZZ ) replaced by ZZring) and the following theorems  (proofs modified) of your mathbox are affected (please do not change them until I am completely finished):
- nmmulg
- zlmds 
- zlmtset 
- nmmulg 
- cnzh 
- rezh 
- zrhre 
- zrhchr 
- zrhnm
- isarchiofld
- rearchi
- zrhf1ker
- zrhunitpreima
- elzrhunit
- qqhval2lem
- qqhf
- qqhghm
- qqhrhm
- qqhnm

@sorear : Theorem mzpmfp ( ( CCfld |`s ZZ ) replaced by ZZring) of your mathbox is affected

**Comment by tirix** [comment]
Thank Alexander, got it!

FYI, I’ve created a plugin for Eclipse, which basically provides all functions from MMJ2 (except for search utility, but with a few more too).
http://emetamath.tirix.org/
It relies on the Eclipse built-in editor, so it has e.g. “replace all” functions (including regexp), and allows to open different proofs in different windows, so it might be handy for this kind of things.

**Comment by avekens** [comment]
By PR #927, this isue is done.
It was really a hard work, much harder than I expected, and I think I need a break now (before I continue with #809, which will be even harder ... ;-) ).
There are currently 12 occurences of ( CCfld |`s ZZ ) in set.mm now: 1 in df-zring (of course) and 11 in obsolete theorems (which will be deleted within the next year).

Thanks everybody for your support!
