### ISSUE TITLE
Conventions: Update table of abbreviations, theorem forms

### ISSUE THREAD

**Issue by avekens** [metamath/set.mm#949]
I just committed an enhancement of the comment for ~ conventions (table of abbreviations used in labels) and an update of the section comment for "Logical implication", see PR #948 (@nmegill you were too fast merging my PR into metamath:develop - I originally wanted you and @david-a-wheeler  to review my changes first...).

Here some remarks on and questions about these changes:

- **Conventions/Table of abbreviations used in labels**: Although the number of entries in the table is more than doubled now, I think it is far from being complete. I wonder what should actually be contained in this list (what does "complete" mean?): all exceptions to the general conventions (of course), prefixes/suffixes not being names of definitions (df-NAME), e.g. ALT, com, simp, and the names (NAME part of df-NAME) of (some?/all?) definitions. In question is the last point: which definitions should be included? Only "important"/"often used"/"familiar" ones (this might be very subjective)? All (this will be a lot!)? Or are there certain rules? For example, I did not include an entry for "oprab", although there is a definition df-oprab, because this name is composed of "op" and "rab" for which entries already exist. Similar with "gra" (for graph): there is no definition df-gra for a "graph", but definitions df-usgra, df-umgra etc. for special kinds of graphs, containing this abbreviation. Nevertheless, I added most entries relying on definitions on personal taste. @david-a-wheeler please feel free to remove some of the entries I added if they are not appropriate for the table!
- **Section comment for "Logical implication"**: I replaced the paragraph about "forms of theorems" by a (slightly modified) text from the (new version of the) Metamath book. I wonder, however, if it should be placed there, because there is a similar paragraph ("Theorem forms") in the "conventions". Maybe the paragraph in the comment for "Logical implication" can be removed completely, and the paragraph "Theorem forms" in the "conventions" can be revised accordingly.

@nmegill @david-a-wheeler what is your opinion?

**Comment by nmegill** [comment]
> I just committed an enhancement of the comment for ~ conventions (table of abbreviations used in labels) and an update of the section comment for "Logical implication", see PR #948 (@nmegill you were too fast merging my PR into metamath:develop - I originally wanted you and @david-a-wheeler to review my changes first...).

I did read "logical implication", which is fine, but I only checked a few in the conventions table.  I find it hard to render HTML source code in my head, :) so actually regenerating it on us2 is helpful to review it.

> 
> Here some remarks on and questions about these changes:
> 
> * **Conventions/Table of abbreviations used in labels**: Although the number of entries in the table is more than doubled now, I think it is far from being complete. I wonder what should actually be contained in this list (what does "complete" mean?): 

I think you've done a great job of filling in the table!  I don't think it will ever be complete, and it's probably not necessary, especially for rarely used concepts (although there's probably no harm putting them in).  One could argue that too many entries overwhelms the reader, but no one is being asked to memorize it, and the main point of the table is to show that we try to have a consistent naming convention in mind when adding a new concept.  Choosing good names often isn't easy, because there is almost always a compromise between being brief (usually, the shorter the better) and being too ambiguous or too obscure.

The table is also something we should point to for new users adding theorems to their mathboxes.  When I import theorems into set.mm main, one thing I sometimes don't look forward to is figuring out how to rename them to conform to our conventions.  In mathboxes there are now theorem names like "aiffnbandciffatnotciffb".  In the past I've also imported theorems that followed an initialism convention:  e.g. something like "reurex" (easy to remember, "reu"+"rex") might be named "rueire" meaning "Restricted unique existence implies restricted existence" in their mathbox.  I don't know how they remembered these even for their own use. :)  And there are the bnj* numbered theorems, but I think I've imported and renamed most of the ones that are generally useful.

> all exceptions to the general conventions (of course), prefixes/suffixes not being names of definitions (df-NAME), e.g. ALT, com, simp, and the names (NAME part of df-NAME) of (some?/all?) definitions. In question is the last point: which definitions should be included? Only "important"/"often used"/"familiar" ones (this might be very subjective)? All (this will be a lot!)? Or are there certain rules? For example, I did not include an entry for "oprab", although there is a definition df-oprab, because this name is composed of "op" and "rab" for which entries already exist. Similar with "gra" (for graph): there is no definition df-gra for a "graph", but definitions df-usgra, df-umgra etc. for special kinds of graphs, containing this abbreviation.

It will always be subjective, but I think you've done the right thing, and we don't need to put in definitions that have names compounded from abbreviations already in the table.  Indeed you (and David!) have done quite a good job of sorting this out and recognizing the sometimes imperfect gestalt of what we are trying to accomplish with labels.

> Nevertheless, I added most entries relying on definitions on personal taste. @david-a-wheeler please feel free to remove some of the entries I added if they are not appropriate for the table!
> * **Section comment for "Logical implication"**: I replaced the paragraph about "forms of theorems" by a (slightly modified) text from the (new version of the) Metamath book. I wonder, however, if it should be placed there, because there is a similar paragraph ("Theorem forms") in the "conventions". Maybe the paragraph in the comment for "Logical implication" can be removed completely, and the paragraph "Theorem forms" in the "conventions" can be revised accordingly.

Maybe that's a good idea.  People who need to study the "Logical implication" section are probably not ready to care about theorem forms, and those who are more advanced probably won't be reading "Logical impliciation" and will miss the explanation.  So a pointer there to the conventions might be better.

> 
> @nmegill @david-a-wheeler what is your opinion?

**Comment by david-a-wheeler** [comment]
I don't think there's a strong need for a "complete" table (if there is, then I think it should be generated from the shorter table).  We must document our exceptions anyway, so also including a list of "common" label fragments (which we do) is probably enough. That's a judgment call, but that's okay.

If something might go in multiple places in set.mm, I think we should pick its "canonical" location and then add links to it from everywhere else.  The great thing about hypertext is that you can quickly end up in an unexpected place.  The bad thing about hypertext is that you can easily lose context, so links for relevant context are really useful.

**Comment by avekens** [comment]
Done with PR #951
