### ISSUE TITLE
Change mpt2 to mpo

### ISSUE THREAD

**Issue by digama0** [metamath/set.mm#98]
Does anyone object to changing the label fragment for two-argument mapping from `mpt2` to `mpo`? The former often conflicts with numbered theorems about single argument mapping. It has also been mentioned as a proposal at the top of set.mm for many years, where it is also accompanied by a proposal to change `mpt` to `mpf`. How do people feel about these changes?

Current status (August 2023, by @jkingdon ): `mpt2` to `mpo` rename is underway. Remaining tasks:

* [x] finish renaming theorems in set.mm
* [x] finish renaming theorems in iset.mm (there's at least one which isn't also in set.mm)
* [x] update comment for section "Special maps-to operations" above opeliunxp2f - both set.mm and iset.mm
* [ ] update proposed renames entry in changes-set.txt
* [ ] update references in missing theorems list in mmil.html
* [ ] update reference in mmnatded.raw.html
* [ ] update references in mmnotes.txt

**Comment by david-a-wheeler** [comment]
No objection, makes sense to me.  However, please include in the df-... comment a note explaining what the abbreviation stands for (in general).  We have several cases where the abbreviation is a mystery for native English speakers, and I expect it's worse for non-native speakers.

**Comment by nmegill** [comment]
On 1/7/17 3:20 PM, Mario Carneiro wrote:
> Does anyone object to changing the label fragment for two-argument
> mapping from |mpt2| to |mpo|? The former often conflicts with numbered
> theorems about single argument mapping. It has also been mentioned as a
> proposal at the top of set.mm for many years, where it is also
> accompanied by a proposal to change |mpt| to |mpf|. How do people feel
> about these changes?

I don't have any objection, but I was the one who proposed it.:)  Of 
course we would document all renames in the change list at the top of 
set.mm, as usual.

Norm

**Comment by jkingdon** [comment]
I'm all for changing `mpt2` to `mpo` and would be in favor of doing this change in iset.mm as well (keeping track of `mpt` versus `mpt2` has been mildly confusing when intuitionizing the `mpt2` theorems).

**Comment by nmegill** [comment]
The current proposals at the top of set.mm are:

proposed  *mpt*     *mpf* or *mptf* (maps-to for functions)
proposed  *mpt2*    *mpo* or *mpto* (maps-to for operations

The 4-letter prefix alternatives are ok but may be slightly longer than necessary.  mpto* conflicts with modus ponendo tollens, mpto1 and mpto2, but those can be renamed.

For the 3-letter alternatives above, "mp.." stands for MaPs-to.  But "mt..." might be more logical, standing for Maps-To.  The only conflicts with "mto.." are the 4 modus tollens theorems mto, mtod, mtoi, mtord (other modus tollens theorems begin with just "mt").  There are no conflicts with "mtf".

I am thinking I might prefer "mtf", "mto" (Maps-To Function, Maps-To Operation).  Some other function prefixes (fn, fun, f, f1, f1o) are similarly brief; even though potentially ambiguous, I think they have served us well (less typing).  Any other thoughts?

Norm

**Comment by avekens** [comment]
I would be glad if we can find a good, final naming for these important concepts.

In contrast to Norm, I would prefer the 4-letter alternatives "mptf" and "mpto", because "MaP" is the the main term and shoud be derivable from the abbreviation ("mt" could also stand for "moves to", "migrates to", etc.). Concerning the length: it's not longer for the "operation" case (mpt2<->mpto), and for the "function" case it would be acceptable for me. Actually, there are no conflicts (anymore), because mpto1 and mpto2 were already renamed on 20-Apr-2019 (to mptnan and mptxor)!

By the way: currently, we have "mpt" as abbreviation for "modus ponendo tollens" and for "maps-to" for functions, so that it would be even more necessary to find a proper naming convention for these cases.

**Comment by avekens** [comment]
Maybe we can agree on the following as a compromise: Let's leave "mpt" standing for "MaPs-To notation (of a function)", and use "mpto" for "MaPs-To notation of an Operation" as a special case, because operations are special cases of functions. This will leave the lengths unchanged, reduces the effort for updating set.mm, and is still consistent. That "mpt" stands for both "modus ponendo tollens" and "maps-to notation of a function)" can be acceptable because these are concepts of different subject areas, and there is no definition for "modus ponendo tollens" (like df-mpt for "maps-to"). 

This corresponds to Mario's suggestion of 7-Jan-2017 to replace mpt2 only.

**Comment by benjub** [comment]
Just browsing through old issues... I agree with @avekens's proposal to leave `mpt` as is, at least for now, and change `mpt2` to `mpto` : this 4-letter version is less ambiguous and clearer, and mpto-theorems are not as ubiquitous as mpt-theorems, so it is less important to compress things at all cost to 3 letters instead of 4.
